-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity phase2_rpm_cnn_dense_q_Pipeline_VITIS_LOOP_105_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_1_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_2_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_3_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_4_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_5_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_6_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_7_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_8_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_9_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_10_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_11_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_12_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_13_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_14_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_15_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_16_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_17_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_18_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_19_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_20_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_21_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_22_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_23_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_24_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_25_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_26_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_27_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_28_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_29_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_30_val : IN STD_LOGIC_VECTOR (17 downto 0);
    input_31_val : IN STD_LOGIC_VECTOR (17 downto 0);
    tmp_31 : IN STD_LOGIC_VECTOR (8 downto 0);
    acc_02_out : OUT STD_LOGIC_VECTOR (39 downto 0);
    acc_02_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of phase2_rpm_cnn_dense_q_Pipeline_VITIS_LOOP_105_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv40_0 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv40_7FFFFFFFFF : STD_LOGIC_VECTOR (39 downto 0) := "0111111111111111111111111111111111111111";
    constant ap_const_lv40_8000000000 : STD_LOGIC_VECTOR (39 downto 0) := "1000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln105_fu_445_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal fc1_weight_q_address0 : STD_LOGIC_VECTOR (8 downto 0);
    signal fc1_weight_q_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_465_p67 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_s_reg_834 : STD_LOGIC_VECTOR (17 downto 0);
    signal fc1_weight_q_load_reg_844 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mul_ln107_fu_428_p2 : STD_LOGIC_VECTOR (47 downto 0);
    signal mul_ln107_reg_849 : STD_LOGIC_VECTOR (47 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_49_reg_854 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_2_fu_702_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal acc_2_reg_859 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal and_ln107_1_fu_764_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_1_reg_864 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_2_fu_788_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_2_reg_869 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln107_1_fu_607_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_1_fu_202 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    signal acc_3_fu_801_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_206 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    signal add_ln105_fu_451_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_i_5 : STD_LOGIC_VECTOR (5 downto 0);
    signal fc1_weight_q_ce0_local : STD_LOGIC;
    signal tmp_s_fu_465_p65 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_s_fu_465_p66 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln105_fu_457_p1 : STD_LOGIC_VECTOR (8 downto 0);
    signal add_ln107_fu_601_p2 : STD_LOGIC_VECTOR (8 downto 0);
    signal shl_ln3_fu_617_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln107_3_fu_624_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln107_4_fu_652_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal sext_ln107_2_fu_660_p1 : STD_LOGIC_VECTOR (56 downto 0);
    signal sext_ln107_3_fu_664_p1 : STD_LOGIC_VECTOR (56 downto 0);
    signal add_ln107_1_fu_667_p2 : STD_LOGIC_VECTOR (56 downto 0);
    signal acc_fu_681_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln107_fu_699_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_51_fu_708_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_50_fu_691_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_fu_716_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_1_fu_728_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_673_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_3_fu_746_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_1_fu_734_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_4_fu_752_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_fu_758_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_2_fu_740_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_fu_722_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_3_fu_770_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_5_fu_776_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_2_fu_782_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln107_fu_794_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal tmp_s_fu_465_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p5 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p7 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p9 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p11 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p13 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p15 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p17 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p19 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p21 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p23 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p25 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p27 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p29 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p31 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p33 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p35 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p37 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p39 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p41 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p43 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p45 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p47 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p49 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p51 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p53 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p55 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p57 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p59 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p61 : STD_LOGIC_VECTOR (4 downto 0);
    signal tmp_s_fu_465_p63 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component phase2_rpm_cnn_mul_24s_24s_48_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (23 downto 0);
        dout : OUT STD_LOGIC_VECTOR (47 downto 0) );
    end component;


    component phase2_rpm_cnn_sparsemux_65_5_18_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (4 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (4 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (4 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (4 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (4 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (4 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (4 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (4 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (4 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (4 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (4 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (4 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (4 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (4 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (4 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (4 downto 0);
        din15_WIDTH : INTEGER;
        CASE16 : STD_LOGIC_VECTOR (4 downto 0);
        din16_WIDTH : INTEGER;
        CASE17 : STD_LOGIC_VECTOR (4 downto 0);
        din17_WIDTH : INTEGER;
        CASE18 : STD_LOGIC_VECTOR (4 downto 0);
        din18_WIDTH : INTEGER;
        CASE19 : STD_LOGIC_VECTOR (4 downto 0);
        din19_WIDTH : INTEGER;
        CASE20 : STD_LOGIC_VECTOR (4 downto 0);
        din20_WIDTH : INTEGER;
        CASE21 : STD_LOGIC_VECTOR (4 downto 0);
        din21_WIDTH : INTEGER;
        CASE22 : STD_LOGIC_VECTOR (4 downto 0);
        din22_WIDTH : INTEGER;
        CASE23 : STD_LOGIC_VECTOR (4 downto 0);
        din23_WIDTH : INTEGER;
        CASE24 : STD_LOGIC_VECTOR (4 downto 0);
        din24_WIDTH : INTEGER;
        CASE25 : STD_LOGIC_VECTOR (4 downto 0);
        din25_WIDTH : INTEGER;
        CASE26 : STD_LOGIC_VECTOR (4 downto 0);
        din26_WIDTH : INTEGER;
        CASE27 : STD_LOGIC_VECTOR (4 downto 0);
        din27_WIDTH : INTEGER;
        CASE28 : STD_LOGIC_VECTOR (4 downto 0);
        din28_WIDTH : INTEGER;
        CASE29 : STD_LOGIC_VECTOR (4 downto 0);
        din29_WIDTH : INTEGER;
        CASE30 : STD_LOGIC_VECTOR (4 downto 0);
        din30_WIDTH : INTEGER;
        CASE31 : STD_LOGIC_VECTOR (4 downto 0);
        din31_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (17 downto 0);
        din1 : IN STD_LOGIC_VECTOR (17 downto 0);
        din2 : IN STD_LOGIC_VECTOR (17 downto 0);
        din3 : IN STD_LOGIC_VECTOR (17 downto 0);
        din4 : IN STD_LOGIC_VECTOR (17 downto 0);
        din5 : IN STD_LOGIC_VECTOR (17 downto 0);
        din6 : IN STD_LOGIC_VECTOR (17 downto 0);
        din7 : IN STD_LOGIC_VECTOR (17 downto 0);
        din8 : IN STD_LOGIC_VECTOR (17 downto 0);
        din9 : IN STD_LOGIC_VECTOR (17 downto 0);
        din10 : IN STD_LOGIC_VECTOR (17 downto 0);
        din11 : IN STD_LOGIC_VECTOR (17 downto 0);
        din12 : IN STD_LOGIC_VECTOR (17 downto 0);
        din13 : IN STD_LOGIC_VECTOR (17 downto 0);
        din14 : IN STD_LOGIC_VECTOR (17 downto 0);
        din15 : IN STD_LOGIC_VECTOR (17 downto 0);
        din16 : IN STD_LOGIC_VECTOR (17 downto 0);
        din17 : IN STD_LOGIC_VECTOR (17 downto 0);
        din18 : IN STD_LOGIC_VECTOR (17 downto 0);
        din19 : IN STD_LOGIC_VECTOR (17 downto 0);
        din20 : IN STD_LOGIC_VECTOR (17 downto 0);
        din21 : IN STD_LOGIC_VECTOR (17 downto 0);
        din22 : IN STD_LOGIC_VECTOR (17 downto 0);
        din23 : IN STD_LOGIC_VECTOR (17 downto 0);
        din24 : IN STD_LOGIC_VECTOR (17 downto 0);
        din25 : IN STD_LOGIC_VECTOR (17 downto 0);
        din26 : IN STD_LOGIC_VECTOR (17 downto 0);
        din27 : IN STD_LOGIC_VECTOR (17 downto 0);
        din28 : IN STD_LOGIC_VECTOR (17 downto 0);
        din29 : IN STD_LOGIC_VECTOR (17 downto 0);
        din30 : IN STD_LOGIC_VECTOR (17 downto 0);
        din31 : IN STD_LOGIC_VECTOR (17 downto 0);
        def : IN STD_LOGIC_VECTOR (17 downto 0);
        sel : IN STD_LOGIC_VECTOR (4 downto 0);
        dout : OUT STD_LOGIC_VECTOR (17 downto 0) );
    end component;


    component phase2_rpm_cnn_dense_q_Pipeline_VITIS_LOOP_105_2_fc1_weight_q_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (8 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component phase2_rpm_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fc1_weight_q_U : component phase2_rpm_cnn_dense_q_Pipeline_VITIS_LOOP_105_2_fc1_weight_q_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 512,
        AddressWidth => 9)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fc1_weight_q_address0,
        ce0 => fc1_weight_q_ce0_local,
        q0 => fc1_weight_q_q0);

    mul_24s_24s_48_1_1_U331 : component phase2_rpm_cnn_mul_24s_24s_48_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 24,
        dout_WIDTH => 48)
    port map (
        din0 => shl_ln107_3_fu_624_p3,
        din1 => shl_ln3_fu_617_p3,
        dout => mul_ln107_fu_428_p2);

    sparsemux_65_5_18_1_1_U332 : component phase2_rpm_cnn_sparsemux_65_5_18_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "00000",
        din0_WIDTH => 18,
        CASE1 => "00001",
        din1_WIDTH => 18,
        CASE2 => "00010",
        din2_WIDTH => 18,
        CASE3 => "00011",
        din3_WIDTH => 18,
        CASE4 => "00100",
        din4_WIDTH => 18,
        CASE5 => "00101",
        din5_WIDTH => 18,
        CASE6 => "00110",
        din6_WIDTH => 18,
        CASE7 => "00111",
        din7_WIDTH => 18,
        CASE8 => "01000",
        din8_WIDTH => 18,
        CASE9 => "01001",
        din9_WIDTH => 18,
        CASE10 => "01010",
        din10_WIDTH => 18,
        CASE11 => "01011",
        din11_WIDTH => 18,
        CASE12 => "01100",
        din12_WIDTH => 18,
        CASE13 => "01101",
        din13_WIDTH => 18,
        CASE14 => "01110",
        din14_WIDTH => 18,
        CASE15 => "01111",
        din15_WIDTH => 18,
        CASE16 => "10000",
        din16_WIDTH => 18,
        CASE17 => "10001",
        din17_WIDTH => 18,
        CASE18 => "10010",
        din18_WIDTH => 18,
        CASE19 => "10011",
        din19_WIDTH => 18,
        CASE20 => "10100",
        din20_WIDTH => 18,
        CASE21 => "10101",
        din21_WIDTH => 18,
        CASE22 => "10110",
        din22_WIDTH => 18,
        CASE23 => "10111",
        din23_WIDTH => 18,
        CASE24 => "11000",
        din24_WIDTH => 18,
        CASE25 => "11001",
        din25_WIDTH => 18,
        CASE26 => "11010",
        din26_WIDTH => 18,
        CASE27 => "11011",
        din27_WIDTH => 18,
        CASE28 => "11100",
        din28_WIDTH => 18,
        CASE29 => "11101",
        din29_WIDTH => 18,
        CASE30 => "11110",
        din30_WIDTH => 18,
        CASE31 => "11111",
        din31_WIDTH => 18,
        def_WIDTH => 18,
        sel_WIDTH => 5,
        dout_WIDTH => 18)
    port map (
        din0 => input_0_val,
        din1 => input_1_val,
        din2 => input_2_val,
        din3 => input_3_val,
        din4 => input_4_val,
        din5 => input_5_val,
        din6 => input_6_val,
        din7 => input_7_val,
        din8 => input_8_val,
        din9 => input_9_val,
        din10 => input_10_val,
        din11 => input_11_val,
        din12 => input_12_val,
        din13 => input_13_val,
        din14 => input_14_val,
        din15 => input_15_val,
        din16 => input_16_val,
        din17 => input_17_val,
        din18 => input_18_val,
        din19 => input_19_val,
        din20 => input_20_val,
        din21 => input_21_val,
        din22 => input_22_val,
        din23 => input_23_val,
        din24 => input_24_val,
        din25 => input_25_val,
        din26 => input_26_val,
        din27 => input_27_val,
        din28 => input_28_val,
        din29 => input_29_val,
        din30 => input_30_val,
        din31 => input_31_val,
        def => tmp_s_fu_465_p65,
        sel => tmp_s_fu_465_p66,
        dout => tmp_s_fu_465_p67);

    flow_control_loop_pipe_sequential_init_U : component phase2_rpm_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    acc_1_fu_202_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
                acc_1_fu_202 <= ap_const_lv40_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                acc_1_fu_202 <= acc_3_fu_801_p3;
            end if; 
        end if;
    end process;

    i_fu_206_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln105_fu_445_p2 = ap_const_lv1_0)) then 
                    i_fu_206 <= add_ln105_fu_451_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_206 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                acc_2_reg_859 <= acc_2_fu_702_p2;
                and_ln107_1_reg_864 <= and_ln107_1_fu_764_p2;
                or_ln107_2_reg_869 <= or_ln107_2_fu_788_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                fc1_weight_q_load_reg_844 <= fc1_weight_q_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_ln107_reg_849 <= mul_ln107_fu_428_p2;
                tmp_49_reg_854 <= mul_ln107_fu_428_p2(15 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                tmp_s_reg_834 <= tmp_s_fu_465_p67;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln105_fu_445_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln105_fu_445_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    acc_02_out <= acc_1_fu_202;

    acc_02_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln105_fu_445_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln105_fu_445_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_02_out_ap_vld <= ap_const_logic_1;
        else 
            acc_02_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    acc_2_fu_702_p2 <= std_logic_vector(unsigned(acc_fu_681_p4) + unsigned(zext_ln107_fu_699_p1));
    acc_3_fu_801_p3 <= 
        select_ln107_fu_794_p3 when (or_ln107_2_reg_869(0) = '1') else 
        acc_2_reg_859;
    acc_fu_681_p4 <= add_ln107_1_fu_667_p2(55 downto 16);
    add_ln105_fu_451_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_5) + unsigned(ap_const_lv6_1));
    add_ln107_1_fu_667_p2 <= std_logic_vector(signed(sext_ln107_2_fu_660_p1) + signed(sext_ln107_3_fu_664_p1));
    add_ln107_fu_601_p2 <= std_logic_vector(unsigned(zext_ln105_fu_457_p1) + unsigned(tmp_31));
    and_ln107_1_fu_764_p2 <= (xor_ln107_2_fu_740_p2 and or_ln107_fu_758_p2);
    and_ln107_2_fu_782_p2 <= (xor_ln107_5_fu_776_p2 and tmp_fu_673_p3);
    and_ln107_fu_722_p2 <= (xor_ln107_fu_716_p2 and tmp_50_fu_691_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln105_fu_445_p2)
    begin
        if (((icmp_ln105_fu_445_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_5_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, i_fu_206)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_5 <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_i_5 <= i_fu_206;
        end if; 
    end process;

    fc1_weight_q_address0 <= zext_ln107_1_fu_607_p1(9 - 1 downto 0);

    fc1_weight_q_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            fc1_weight_q_ce0_local <= ap_const_logic_1;
        else 
            fc1_weight_q_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln105_fu_445_p2 <= "1" when (ap_sig_allocacmp_i_5 = ap_const_lv6_20) else "0";
    or_ln107_1_fu_734_p2 <= (xor_ln107_1_fu_728_p2 or tmp_51_fu_708_p3);
    or_ln107_2_fu_788_p2 <= (and_ln107_2_fu_782_p2 or and_ln107_1_fu_764_p2);
    or_ln107_3_fu_770_p2 <= (tmp_51_fu_708_p3 or and_ln107_fu_722_p2);
    or_ln107_fu_758_p2 <= (xor_ln107_4_fu_752_p2 or tmp_51_fu_708_p3);
    select_ln107_fu_794_p3 <= 
        ap_const_lv40_7FFFFFFFFF when (and_ln107_1_reg_864(0) = '1') else 
        ap_const_lv40_8000000000;
        sext_ln107_2_fu_660_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln107_4_fu_652_p3),57));

        sext_ln107_3_fu_664_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln107_reg_849),57));

    shl_ln107_3_fu_624_p3 <= (fc1_weight_q_load_reg_844 & ap_const_lv16_0);
    shl_ln107_4_fu_652_p3 <= (acc_1_fu_202 & ap_const_lv16_0);
    shl_ln3_fu_617_p3 <= (tmp_s_reg_834 & ap_const_lv6_0);
    tmp_50_fu_691_p3 <= add_ln107_1_fu_667_p2(55 downto 55);
    tmp_51_fu_708_p3 <= acc_2_fu_702_p2(39 downto 39);
    tmp_fu_673_p3 <= add_ln107_1_fu_667_p2(56 downto 56);
    tmp_s_fu_465_p65 <= "XXXXXXXXXXXXXXXXXX";
    tmp_s_fu_465_p66 <= ap_sig_allocacmp_i_5(5 - 1 downto 0);
    xor_ln107_1_fu_728_p2 <= (tmp_50_fu_691_p3 xor ap_const_lv1_1);
    xor_ln107_2_fu_740_p2 <= (tmp_fu_673_p3 xor ap_const_lv1_1);
    xor_ln107_3_fu_746_p2 <= (tmp_fu_673_p3 xor ap_const_lv1_1);
    xor_ln107_4_fu_752_p2 <= (xor_ln107_3_fu_746_p2 xor or_ln107_1_fu_734_p2);
    xor_ln107_5_fu_776_p2 <= (or_ln107_3_fu_770_p2 xor ap_const_lv1_1);
    xor_ln107_fu_716_p2 <= (tmp_51_fu_708_p3 xor ap_const_lv1_1);
    zext_ln105_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_5),9));
    zext_ln107_1_fu_607_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln107_fu_601_p2),64));
    zext_ln107_fu_699_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_49_reg_854),40));
end behav;
