-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity phase2_rpm_cnn_conv1d_same_q_conv1_weight_q_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 6; 
             AddressRange    : integer := 56
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of phase2_rpm_cnn_conv1d_same_q_conv1_weight_q_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "01010010", 1 => "01100101", 2 => "11011111", 3 => "01001001", 
    4 => "10111111", 5 => "11010101", 6 => "10101010", 7 => "00110001", 
    8 => "01010110", 9 => "11101011", 10 => "01100011", 11 => "00100101", 
    12 => "01001000", 13 => "00001110", 14 => "00111000", 15 => "11101111", 
    16 => "01010111", 17 => "00001100", 18 => "11000101", 19 => "11111000", 
    20 => "11000011", 21 => "11100001", 22 => "11000110", 23 => "00001001", 
    24 => "10100110", 25 => "10111101", 26 => "11000110", 27 => "10100100", 
    28 => "11111001", 29 => "10011111", 30 => "01001101", 31 => "10101011", 
    32 => "01000100", 33 => "00000110", 34 => "11011001", 35 => "01000000", 
    36 => "00101000", 37 => "01001111", 38 => "00100001", 39 => "00000100", 
    40 => "00010111", 41 => "11110110", 42 => "00110101", 43 => "01111111", 
    44 => "00011001", 45 => "10001010", 46 => "00000100", 47 => "11111100", 
    48 => "00001111", 49 => "10101110", 50 => "10011001", 51 => "11001001", 
    52 => "10100110", 53 => "01010100", 54 => "00101110", 55 => "01001110");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

