-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
-- 67d7842dbbe25473c3c32b93c0da8047785f30d78e8a024de1b57352245f9689

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity phase2_rpm_cnn_bitselect_1ns_32ns_32s_1_1_1 is
generic (
    ADDRWIDTH : INTEGER := 32;
    DATAWIDTH : INTEGER := 32
);
port (

    sel   : in std_logic_vector (ADDRWIDTH-1 downto 0);
    din   : in std_logic_vector (DATAWIDTH-1 downto 0);
    dout  : out std_logic_vector (0 downto 0)
);
end entity;

architecture behav of phase2_rpm_cnn_bitselect_1ns_32ns_32s_1_1_1 is
    signal dout_tmp : std_logic_vector (0 downto 0);


begin

    process(din,sel) is
    begin
        case sel is
            
            when std_logic_vector(to_unsigned(0,sel'length)) =>
                dout_tmp(0) <= din(0);
            
            when std_logic_vector(to_unsigned(1,sel'length)) =>
                dout_tmp(0) <= din(1);
            
            when std_logic_vector(to_unsigned(2,sel'length)) =>
                dout_tmp(0) <= din(2);
            
            when std_logic_vector(to_unsigned(3,sel'length)) =>
                dout_tmp(0) <= din(3);
            
            when std_logic_vector(to_unsigned(4,sel'length)) =>
                dout_tmp(0) <= din(4);
            
            when std_logic_vector(to_unsigned(5,sel'length)) =>
                dout_tmp(0) <= din(5);
            
            when std_logic_vector(to_unsigned(6,sel'length)) =>
                dout_tmp(0) <= din(6);
            
            when std_logic_vector(to_unsigned(7,sel'length)) =>
                dout_tmp(0) <= din(7);
            
            when std_logic_vector(to_unsigned(8,sel'length)) =>
                dout_tmp(0) <= din(8);
            
            when std_logic_vector(to_unsigned(9,sel'length)) =>
                dout_tmp(0) <= din(9);
            
            when std_logic_vector(to_unsigned(10,sel'length)) =>
                dout_tmp(0) <= din(10);
            
            when std_logic_vector(to_unsigned(11,sel'length)) =>
                dout_tmp(0) <= din(11);
            
            when std_logic_vector(to_unsigned(12,sel'length)) =>
                dout_tmp(0) <= din(12);
            
            when std_logic_vector(to_unsigned(13,sel'length)) =>
                dout_tmp(0) <= din(13);
            
            when std_logic_vector(to_unsigned(14,sel'length)) =>
                dout_tmp(0) <= din(14);
            
            when std_logic_vector(to_unsigned(15,sel'length)) =>
                dout_tmp(0) <= din(15);
            
            when std_logic_vector(to_unsigned(16,sel'length)) =>
                dout_tmp(0) <= din(16);
            
            when std_logic_vector(to_unsigned(17,sel'length)) =>
                dout_tmp(0) <= din(17);
            
            when std_logic_vector(to_unsigned(18,sel'length)) =>
                dout_tmp(0) <= din(18);
            
            when std_logic_vector(to_unsigned(19,sel'length)) =>
                dout_tmp(0) <= din(19);
            
            when std_logic_vector(to_unsigned(20,sel'length)) =>
                dout_tmp(0) <= din(20);
            
            when std_logic_vector(to_unsigned(21,sel'length)) =>
                dout_tmp(0) <= din(21);
            
            when std_logic_vector(to_unsigned(22,sel'length)) =>
                dout_tmp(0) <= din(22);
            
            when std_logic_vector(to_unsigned(23,sel'length)) =>
                dout_tmp(0) <= din(23);
            
            when std_logic_vector(to_unsigned(24,sel'length)) =>
                dout_tmp(0) <= din(24);
            
            when std_logic_vector(to_unsigned(25,sel'length)) =>
                dout_tmp(0) <= din(25);
            
            when std_logic_vector(to_unsigned(26,sel'length)) =>
                dout_tmp(0) <= din(26);
            
            when std_logic_vector(to_unsigned(27,sel'length)) =>
                dout_tmp(0) <= din(27);
            
            when std_logic_vector(to_unsigned(28,sel'length)) =>
                dout_tmp(0) <= din(28);
            
            when std_logic_vector(to_unsigned(29,sel'length)) =>
                dout_tmp(0) <= din(29);
            
            when std_logic_vector(to_unsigned(30,sel'length)) =>
                dout_tmp(0) <= din(30);
            
            when std_logic_vector(to_unsigned(31,sel'length)) =>
                dout_tmp(0) <= din(31);
            
            when others => 
                dout_tmp(0) <= 'X';
        end case;
    end process;


    dout <= dout_tmp;




end architecture;
