-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_1_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_2_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_3_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_4_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_5_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_6_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_7_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_8_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_9_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_10_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_11_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_12_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_13_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_14_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_15_val : IN STD_LOGIC_VECTOR (16 downto 0);
    acc_out : OUT STD_LOGIC_VECTOR (39 downto 0);
    acc_out_ap_vld : OUT STD_LOGIC );
end;


architecture behav of phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv40_0 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv5_10 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv16_0 : STD_LOGIC_VECTOR (15 downto 0) := "0000000000000000";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_38 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111000";
    constant ap_const_lv32_10 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010000";
    constant ap_const_lv32_37 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110111";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv40_7FFFFFFFFF : STD_LOGIC_VECTOR (39 downto 0) := "0111111111111111111111111111111111111111";
    constant ap_const_lv40_8000000000 : STD_LOGIC_VECTOR (39 downto 0) := "1000000000000000000000000000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal icmp_ln105_fu_277_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal fc2_weight_q_address0 : STD_LOGIC_VECTOR (3 downto 0);
    signal fc2_weight_q_q0 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_s_fu_298_p35 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_s_reg_592 : STD_LOGIC_VECTOR (16 downto 0);
    signal fc2_weight_q_load_reg_602 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal mul_ln107_fu_260_p2 : STD_LOGIC_VECTOR (46 downto 0);
    signal mul_ln107_reg_607 : STD_LOGIC_VECTOR (46 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal tmp_52_reg_612 : STD_LOGIC_VECTOR (0 downto 0);
    signal acc_4_fu_460_p2 : STD_LOGIC_VECTOR (39 downto 0);
    signal acc_4_reg_617 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal and_ln107_1_fu_522_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_1_reg_622 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_1_fu_546_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_1_reg_627 : STD_LOGIC_VECTOR (0 downto 0);
    signal zext_ln105_fu_289_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal acc_fu_136 : STD_LOGIC_VECTOR (39 downto 0) := "0000000000000000000000000000000000000000";
    signal acc_5_fu_559_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal i_fu_140 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal add_ln105_fu_283_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_sig_allocacmp_i_6 : STD_LOGIC_VECTOR (4 downto 0);
    signal fc2_weight_q_ce0_local : STD_LOGIC;
    signal mul_ln107_fu_260_p1 : STD_LOGIC_VECTOR (22 downto 0);
    signal tmp_s_fu_298_p33 : STD_LOGIC_VECTOR (16 downto 0);
    signal tmp_s_fu_298_p34 : STD_LOGIC_VECTOR (3 downto 0);
    signal shl_ln_fu_375_p3 : STD_LOGIC_VECTOR (22 downto 0);
    signal shl_ln107_1_fu_382_p3 : STD_LOGIC_VECTOR (23 downto 0);
    signal shl_ln107_2_fu_410_p3 : STD_LOGIC_VECTOR (55 downto 0);
    signal sext_ln107_1_fu_418_p1 : STD_LOGIC_VECTOR (56 downto 0);
    signal sext_ln107_2_fu_422_p1 : STD_LOGIC_VECTOR (56 downto 0);
    signal add_ln107_fu_425_p2 : STD_LOGIC_VECTOR (56 downto 0);
    signal acc_1_fu_439_p4 : STD_LOGIC_VECTOR (39 downto 0);
    signal zext_ln107_fu_457_p1 : STD_LOGIC_VECTOR (39 downto 0);
    signal tmp_54_fu_466_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_53_fu_449_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_fu_474_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_2_fu_486_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_fu_431_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_4_fu_504_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_2_fu_492_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_3_fu_510_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_fu_516_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_1_fu_498_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_fu_480_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln107_3_fu_528_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln107_5_fu_534_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln107_2_fu_540_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln107_fu_552_p3 : STD_LOGIC_VECTOR (39 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln107_fu_260_p10 : STD_LOGIC_VECTOR (46 downto 0);
    signal tmp_s_fu_298_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p5 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p7 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p9 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p11 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p13 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p15 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p17 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p19 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p21 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p23 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p25 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p27 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p29 : STD_LOGIC_VECTOR (3 downto 0);
    signal tmp_s_fu_298_p31 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component phase2_rpm_cnn_mul_24s_23ns_47_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (23 downto 0);
        din1 : IN STD_LOGIC_VECTOR (22 downto 0);
        dout : OUT STD_LOGIC_VECTOR (46 downto 0) );
    end component;


    component phase2_rpm_cnn_sparsemux_33_4_17_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        CASE0 : STD_LOGIC_VECTOR (3 downto 0);
        din0_WIDTH : INTEGER;
        CASE1 : STD_LOGIC_VECTOR (3 downto 0);
        din1_WIDTH : INTEGER;
        CASE2 : STD_LOGIC_VECTOR (3 downto 0);
        din2_WIDTH : INTEGER;
        CASE3 : STD_LOGIC_VECTOR (3 downto 0);
        din3_WIDTH : INTEGER;
        CASE4 : STD_LOGIC_VECTOR (3 downto 0);
        din4_WIDTH : INTEGER;
        CASE5 : STD_LOGIC_VECTOR (3 downto 0);
        din5_WIDTH : INTEGER;
        CASE6 : STD_LOGIC_VECTOR (3 downto 0);
        din6_WIDTH : INTEGER;
        CASE7 : STD_LOGIC_VECTOR (3 downto 0);
        din7_WIDTH : INTEGER;
        CASE8 : STD_LOGIC_VECTOR (3 downto 0);
        din8_WIDTH : INTEGER;
        CASE9 : STD_LOGIC_VECTOR (3 downto 0);
        din9_WIDTH : INTEGER;
        CASE10 : STD_LOGIC_VECTOR (3 downto 0);
        din10_WIDTH : INTEGER;
        CASE11 : STD_LOGIC_VECTOR (3 downto 0);
        din11_WIDTH : INTEGER;
        CASE12 : STD_LOGIC_VECTOR (3 downto 0);
        din12_WIDTH : INTEGER;
        CASE13 : STD_LOGIC_VECTOR (3 downto 0);
        din13_WIDTH : INTEGER;
        CASE14 : STD_LOGIC_VECTOR (3 downto 0);
        din14_WIDTH : INTEGER;
        CASE15 : STD_LOGIC_VECTOR (3 downto 0);
        din15_WIDTH : INTEGER;
        def_WIDTH : INTEGER;
        sel_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (16 downto 0);
        din1 : IN STD_LOGIC_VECTOR (16 downto 0);
        din2 : IN STD_LOGIC_VECTOR (16 downto 0);
        din3 : IN STD_LOGIC_VECTOR (16 downto 0);
        din4 : IN STD_LOGIC_VECTOR (16 downto 0);
        din5 : IN STD_LOGIC_VECTOR (16 downto 0);
        din6 : IN STD_LOGIC_VECTOR (16 downto 0);
        din7 : IN STD_LOGIC_VECTOR (16 downto 0);
        din8 : IN STD_LOGIC_VECTOR (16 downto 0);
        din9 : IN STD_LOGIC_VECTOR (16 downto 0);
        din10 : IN STD_LOGIC_VECTOR (16 downto 0);
        din11 : IN STD_LOGIC_VECTOR (16 downto 0);
        din12 : IN STD_LOGIC_VECTOR (16 downto 0);
        din13 : IN STD_LOGIC_VECTOR (16 downto 0);
        din14 : IN STD_LOGIC_VECTOR (16 downto 0);
        din15 : IN STD_LOGIC_VECTOR (16 downto 0);
        def : IN STD_LOGIC_VECTOR (16 downto 0);
        sel : IN STD_LOGIC_VECTOR (3 downto 0);
        dout : OUT STD_LOGIC_VECTOR (16 downto 0) );
    end component;


    component phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2_fc2_weight_q_ROM_AUTO_1R IS
    generic (
        DataWidth : INTEGER;
        AddressRange : INTEGER;
        AddressWidth : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        address0 : IN STD_LOGIC_VECTOR (3 downto 0);
        ce0 : IN STD_LOGIC;
        q0 : OUT STD_LOGIC_VECTOR (7 downto 0) );
    end component;


    component phase2_rpm_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    fc2_weight_q_U : component phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2_fc2_weight_q_ROM_AUTO_1R
    generic map (
        DataWidth => 8,
        AddressRange => 16,
        AddressWidth => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        address0 => fc2_weight_q_address0,
        ce0 => fc2_weight_q_ce0_local,
        q0 => fc2_weight_q_q0);

    mul_24s_23ns_47_1_1_U419 : component phase2_rpm_cnn_mul_24s_23ns_47_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 24,
        din1_WIDTH => 23,
        dout_WIDTH => 47)
    port map (
        din0 => shl_ln107_1_fu_382_p3,
        din1 => mul_ln107_fu_260_p1,
        dout => mul_ln107_fu_260_p2);

    sparsemux_33_4_17_1_1_U420 : component phase2_rpm_cnn_sparsemux_33_4_17_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        CASE0 => "0000",
        din0_WIDTH => 17,
        CASE1 => "0001",
        din1_WIDTH => 17,
        CASE2 => "0010",
        din2_WIDTH => 17,
        CASE3 => "0011",
        din3_WIDTH => 17,
        CASE4 => "0100",
        din4_WIDTH => 17,
        CASE5 => "0101",
        din5_WIDTH => 17,
        CASE6 => "0110",
        din6_WIDTH => 17,
        CASE7 => "0111",
        din7_WIDTH => 17,
        CASE8 => "1000",
        din8_WIDTH => 17,
        CASE9 => "1001",
        din9_WIDTH => 17,
        CASE10 => "1010",
        din10_WIDTH => 17,
        CASE11 => "1011",
        din11_WIDTH => 17,
        CASE12 => "1100",
        din12_WIDTH => 17,
        CASE13 => "1101",
        din13_WIDTH => 17,
        CASE14 => "1110",
        din14_WIDTH => 17,
        CASE15 => "1111",
        din15_WIDTH => 17,
        def_WIDTH => 17,
        sel_WIDTH => 4,
        dout_WIDTH => 17)
    port map (
        din0 => input_0_val,
        din1 => input_1_val,
        din2 => input_2_val,
        din3 => input_3_val,
        din4 => input_4_val,
        din5 => input_5_val,
        din6 => input_6_val,
        din7 => input_7_val,
        din8 => input_8_val,
        din9 => input_9_val,
        din10 => input_10_val,
        din11 => input_11_val,
        din12 => input_12_val,
        din13 => input_13_val,
        din14 => input_14_val,
        din15 => input_15_val,
        def => tmp_s_fu_298_p33,
        sel => tmp_s_fu_298_p34,
        dout => tmp_s_fu_298_p35);

    flow_control_loop_pipe_sequential_init_U : component phase2_rpm_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    acc_fu_136_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
                acc_fu_136 <= ap_const_lv40_0;
            elsif ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
                acc_fu_136 <= acc_5_fu_559_p3;
            end if; 
        end if;
    end process;

    i_fu_140_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                if ((icmp_ln105_fu_277_p2 = ap_const_lv1_0)) then 
                    i_fu_140 <= add_ln105_fu_283_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_140 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                acc_4_reg_617 <= acc_4_fu_460_p2;
                and_ln107_1_reg_622 <= and_ln107_1_fu_522_p2;
                or_ln107_1_reg_627 <= or_ln107_1_fu_546_p2;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state2)) then
                fc2_weight_q_load_reg_602 <= fc2_weight_q_q0;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                mul_ln107_reg_607 <= mul_ln107_fu_260_p2;
                tmp_52_reg_612 <= mul_ln107_fu_260_p2(15 downto 15);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                tmp_s_reg_592 <= tmp_s_fu_298_p35;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln105_fu_277_p2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((icmp_ln105_fu_277_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state1;
                elsif (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                ap_NS_fsm <= ap_ST_fsm_state3;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    acc_1_fu_439_p4 <= add_ln107_fu_425_p2(55 downto 16);
    acc_4_fu_460_p2 <= std_logic_vector(unsigned(acc_1_fu_439_p4) + unsigned(zext_ln107_fu_457_p1));
    acc_5_fu_559_p3 <= 
        select_ln107_fu_552_p3 when (or_ln107_1_reg_627(0) = '1') else 
        acc_4_reg_617;
    acc_out <= acc_fu_136;

    acc_out_ap_vld_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln105_fu_277_p2, ap_loop_exit_ready)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (icmp_ln105_fu_277_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            acc_out_ap_vld <= ap_const_logic_1;
        else 
            acc_out_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    add_ln105_fu_283_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_6) + unsigned(ap_const_lv5_1));
    add_ln107_fu_425_p2 <= std_logic_vector(signed(sext_ln107_1_fu_418_p1) + signed(sext_ln107_2_fu_422_p1));
    and_ln107_1_fu_522_p2 <= (xor_ln107_1_fu_498_p2 and or_ln107_fu_516_p2);
    and_ln107_2_fu_540_p2 <= (xor_ln107_5_fu_534_p2 and tmp_fu_431_p3);
    and_ln107_fu_480_p2 <= (xor_ln107_fu_474_p2 and tmp_53_fu_449_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_block_state1_pp0_stage0_iter0)
    begin
        if ((ap_const_boolean_1 = ap_block_state1_pp0_stage0_iter0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state2_blk <= ap_const_logic_0;
    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_block_state1_pp0_stage0_iter0_assign_proc : process(ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= (ap_start_int = ap_const_logic_0);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, icmp_ln105_fu_277_p2)
    begin
        if (((icmp_ln105_fu_277_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_6_assign_proc : process(ap_CS_fsm_state1, ap_loop_init, i_fu_140)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_6 <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_i_6 <= i_fu_140;
        end if; 
    end process;

    fc2_weight_q_address0 <= zext_ln105_fu_289_p1(4 - 1 downto 0);

    fc2_weight_q_ce0_local_assign_proc : process(ap_CS_fsm_state1, ap_block_state1_pp0_stage0_iter0)
    begin
        if (((ap_const_boolean_0 = ap_block_state1_pp0_stage0_iter0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            fc2_weight_q_ce0_local <= ap_const_logic_1;
        else 
            fc2_weight_q_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    icmp_ln105_fu_277_p2 <= "1" when (ap_sig_allocacmp_i_6 = ap_const_lv5_10) else "0";
    mul_ln107_fu_260_p1 <= mul_ln107_fu_260_p10(23 - 1 downto 0);
    mul_ln107_fu_260_p10 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(shl_ln_fu_375_p3),47));
    or_ln107_1_fu_546_p2 <= (and_ln107_2_fu_540_p2 or and_ln107_1_fu_522_p2);
    or_ln107_2_fu_492_p2 <= (xor_ln107_2_fu_486_p2 or tmp_54_fu_466_p3);
    or_ln107_3_fu_528_p2 <= (tmp_54_fu_466_p3 or and_ln107_fu_480_p2);
    or_ln107_fu_516_p2 <= (xor_ln107_3_fu_510_p2 or tmp_54_fu_466_p3);
    select_ln107_fu_552_p3 <= 
        ap_const_lv40_7FFFFFFFFF when (and_ln107_1_reg_622(0) = '1') else 
        ap_const_lv40_8000000000;
        sext_ln107_1_fu_418_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(shl_ln107_2_fu_410_p3),57));

        sext_ln107_2_fu_422_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(mul_ln107_reg_607),57));

    shl_ln107_1_fu_382_p3 <= (fc2_weight_q_load_reg_602 & ap_const_lv16_0);
    shl_ln107_2_fu_410_p3 <= (acc_fu_136 & ap_const_lv16_0);
    shl_ln_fu_375_p3 <= (tmp_s_reg_592 & ap_const_lv6_0);
    tmp_53_fu_449_p3 <= add_ln107_fu_425_p2(55 downto 55);
    tmp_54_fu_466_p3 <= acc_4_fu_460_p2(39 downto 39);
    tmp_fu_431_p3 <= add_ln107_fu_425_p2(56 downto 56);
    tmp_s_fu_298_p33 <= "XXXXXXXXXXXXXXXXX";
    tmp_s_fu_298_p34 <= ap_sig_allocacmp_i_6(4 - 1 downto 0);
    xor_ln107_1_fu_498_p2 <= (tmp_fu_431_p3 xor ap_const_lv1_1);
    xor_ln107_2_fu_486_p2 <= (tmp_53_fu_449_p3 xor ap_const_lv1_1);
    xor_ln107_3_fu_510_p2 <= (xor_ln107_4_fu_504_p2 xor or_ln107_2_fu_492_p2);
    xor_ln107_4_fu_504_p2 <= (tmp_fu_431_p3 xor ap_const_lv1_1);
    xor_ln107_5_fu_534_p2 <= (or_ln107_3_fu_528_p2 xor ap_const_lv1_1);
    xor_ln107_fu_474_p2 <= (tmp_54_fu_466_p3 xor ap_const_lv1_1);
    zext_ln105_fu_289_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_6),64));
    zext_ln107_fu_457_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_52_reg_612),40));
end behav;
