-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity phase2_rpm_cnn_phase2_rpm_cnn_Pipeline_VITIS_LOOP_67_1_VITIS_LOOP_68_21 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    pool2_out_8_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool2_out_8_ce1 : OUT STD_LOGIC;
    pool2_out_8_we1 : OUT STD_LOGIC;
    pool2_out_8_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    pool2_out_7_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool2_out_7_ce1 : OUT STD_LOGIC;
    pool2_out_7_we1 : OUT STD_LOGIC;
    pool2_out_7_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    pool2_out_6_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool2_out_6_ce1 : OUT STD_LOGIC;
    pool2_out_6_we1 : OUT STD_LOGIC;
    pool2_out_6_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    pool2_out_5_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool2_out_5_ce1 : OUT STD_LOGIC;
    pool2_out_5_we1 : OUT STD_LOGIC;
    pool2_out_5_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    pool2_out_4_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool2_out_4_ce1 : OUT STD_LOGIC;
    pool2_out_4_we1 : OUT STD_LOGIC;
    pool2_out_4_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    pool2_out_3_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool2_out_3_ce1 : OUT STD_LOGIC;
    pool2_out_3_we1 : OUT STD_LOGIC;
    pool2_out_3_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    pool2_out_2_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool2_out_2_ce1 : OUT STD_LOGIC;
    pool2_out_2_we1 : OUT STD_LOGIC;
    pool2_out_2_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    pool2_out_1_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool2_out_1_ce1 : OUT STD_LOGIC;
    pool2_out_1_we1 : OUT STD_LOGIC;
    pool2_out_1_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    pool2_out_address1 : OUT STD_LOGIC_VECTOR (7 downto 0);
    pool2_out_ce1 : OUT STD_LOGIC;
    pool2_out_we1 : OUT STD_LOGIC;
    pool2_out_d1 : OUT STD_LOGIC_VECTOR (17 downto 0);
    conv2_out_address0 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv2_out_ce0 : OUT STD_LOGIC;
    conv2_out_q0 : IN STD_LOGIC_VECTOR (17 downto 0);
    conv2_out_address1 : OUT STD_LOGIC_VECTOR (11 downto 0);
    conv2_out_ce1 : OUT STD_LOGIC;
    conv2_out_q1 : IN STD_LOGIC_VECTOR (17 downto 0) );
end;


architecture behav of phase2_rpm_cnn_phase2_rpm_cnn_Pipeline_VITIS_LOOP_67_1_VITIS_LOOP_68_21 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv5_0 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    constant ap_const_lv12_0 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    constant ap_const_lv4_7 : STD_LOGIC_VECTOR (3 downto 0) := "0111";
    constant ap_const_lv4_6 : STD_LOGIC_VECTOR (3 downto 0) := "0110";
    constant ap_const_lv4_5 : STD_LOGIC_VECTOR (3 downto 0) := "0101";
    constant ap_const_lv4_4 : STD_LOGIC_VECTOR (3 downto 0) := "0100";
    constant ap_const_lv4_3 : STD_LOGIC_VECTOR (3 downto 0) := "0011";
    constant ap_const_lv4_2 : STD_LOGIC_VECTOR (3 downto 0) := "0010";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv12_800 : STD_LOGIC_VECTOR (11 downto 0) := "100000000000";
    constant ap_const_lv12_1 : STD_LOGIC_VECTOR (11 downto 0) := "000000000001";
    constant ap_const_lv8_80 : STD_LOGIC_VECTOR (7 downto 0) := "10000000";
    constant ap_const_lv5_1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_const_lv8_1 : STD_LOGIC_VECTOR (7 downto 0) := "00000001";
    constant ap_const_lv7_0 : STD_LOGIC_VECTOR (6 downto 0) := "0000000";
    constant ap_const_lv8_9 : STD_LOGIC_VECTOR (7 downto 0) := "00001001";
    constant ap_const_lv23_E39 : STD_LOGIC_VECTOR (22 downto 0) := "00000000000111000111001";
    constant ap_const_lv32_F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000001111";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter2 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter3 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter4 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter5 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter6 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter7 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter8 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter9 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter10 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter11 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter12 : STD_LOGIC := '0';
    signal ap_enable_reg_pp0_iter13 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln67_fu_308_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal select_ln67_fu_332_p3 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln67_reg_537 : STD_LOGIC_VECTOR (7 downto 0);
    signal select_ln67_1_fu_346_p3 : STD_LOGIC_VECTOR (4 downto 0);
    signal select_ln67_1_reg_542 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_fu_354_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548 : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter1_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter2_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter3_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter4_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter5_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter6_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter7_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter8_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter9_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal empty_reg_548_pp0_iter10_reg : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln70_fu_358_p1 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555 : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter1_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter2_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter3_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter4_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter5_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter6_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter7_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter8_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter9_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal trunc_ln70_reg_555_pp0_iter10_reg : STD_LOGIC_VECTOR (6 downto 0);
    signal add_ln72_fu_392_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal add_ln72_1_fu_425_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal add_ln72_1_reg_566 : STD_LOGIC_VECTOR (10 downto 0);
    signal tmp_2_reg_571 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter3_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter4_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter5_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter6_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter7_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter8_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter9_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter10_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter11_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_2_reg_571_pp0_iter12_reg : STD_LOGIC_VECTOR (7 downto 0);
    signal trunc_ln72_fu_488_p1 : STD_LOGIC_VECTOR (3 downto 0);
    signal trunc_ln72_reg_586 : STD_LOGIC_VECTOR (3 downto 0);
    signal select_ln72_fu_492_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal select_ln72_reg_590 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln70_fu_464_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln71_fu_477_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln72_3_fu_500_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_100 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    signal add_ln68_fu_362_p2 : STD_LOGIC_VECTOR (7 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (7 downto 0);
    signal c_fu_104 : STD_LOGIC_VECTOR (4 downto 0) := "00000";
    signal ap_sig_allocacmp_c_load : STD_LOGIC_VECTOR (4 downto 0);
    signal indvar_flatten6_fu_108 : STD_LOGIC_VECTOR (11 downto 0) := "000000000000";
    signal add_ln67_fu_314_p2 : STD_LOGIC_VECTOR (11 downto 0);
    signal ap_sig_allocacmp_indvar_flatten6_load : STD_LOGIC_VECTOR (11 downto 0);
    signal conv2_out_ce1_local : STD_LOGIC;
    signal conv2_out_ce0_local : STD_LOGIC;
    signal pool2_out_7_we1_local : STD_LOGIC;
    signal pool2_out_7_ce1_local : STD_LOGIC;
    signal pool2_out_6_we1_local : STD_LOGIC;
    signal pool2_out_6_ce1_local : STD_LOGIC;
    signal pool2_out_5_we1_local : STD_LOGIC;
    signal pool2_out_5_ce1_local : STD_LOGIC;
    signal pool2_out_4_we1_local : STD_LOGIC;
    signal pool2_out_4_ce1_local : STD_LOGIC;
    signal pool2_out_3_we1_local : STD_LOGIC;
    signal pool2_out_3_ce1_local : STD_LOGIC;
    signal pool2_out_2_we1_local : STD_LOGIC;
    signal pool2_out_2_ce1_local : STD_LOGIC;
    signal pool2_out_1_we1_local : STD_LOGIC;
    signal pool2_out_1_ce1_local : STD_LOGIC;
    signal pool2_out_we1_local : STD_LOGIC;
    signal pool2_out_ce1_local : STD_LOGIC;
    signal pool2_out_8_we1_local : STD_LOGIC;
    signal pool2_out_8_ce1_local : STD_LOGIC;
    signal icmp_ln68_fu_326_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln67_1_fu_340_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal empty_62_fu_383_p2 : STD_LOGIC_VECTOR (4 downto 0);
    signal zext_ln68_fu_388_p1 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_fu_408_p3 : STD_LOGIC_VECTOR (5 downto 0);
    signal p_shl_fu_401_p3 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln72_1_fu_415_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal zext_ln72_fu_397_p1 : STD_LOGIC_VECTOR (10 downto 0);
    signal sub_ln72_fu_419_p2 : STD_LOGIC_VECTOR (10 downto 0);
    signal grp_fu_431_p1 : STD_LOGIC_VECTOR (4 downto 0);
    signal mul_ln72_fu_440_p0 : STD_LOGIC_VECTOR (10 downto 0);
    signal mul_ln72_fu_440_p1 : STD_LOGIC_VECTOR (12 downto 0);
    signal mul_ln72_fu_440_p2 : STD_LOGIC_VECTOR (22 downto 0);
    signal add_ln70_1_fu_456_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal or_ln71_1_fu_469_p4 : STD_LOGIC_VECTOR (11 downto 0);
    signal grp_fu_431_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal icmp_ln72_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter1_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter2_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter3_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter4_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter5_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter6_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter7_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter8_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter9_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter10_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter11_reg : STD_LOGIC;
    signal ap_loop_exit_ready_pp0_iter12_reg : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ready_sig : STD_LOGIC;
    signal ap_done_sig : STD_LOGIC;
    signal mul_ln72_fu_440_p00 : STD_LOGIC_VECTOR (22 downto 0);
    signal ap_ce_reg : STD_LOGIC;

    component phase2_rpm_cnn_urem_8ns_5ns_4_12_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        clk : IN STD_LOGIC;
        reset : IN STD_LOGIC;
        din0 : IN STD_LOGIC_VECTOR (7 downto 0);
        din1 : IN STD_LOGIC_VECTOR (4 downto 0);
        ce : IN STD_LOGIC;
        dout : OUT STD_LOGIC_VECTOR (3 downto 0) );
    end component;


    component phase2_rpm_cnn_mul_11ns_13ns_23_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (10 downto 0);
        din1 : IN STD_LOGIC_VECTOR (12 downto 0);
        dout : OUT STD_LOGIC_VECTOR (22 downto 0) );
    end component;


    component phase2_rpm_cnn_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    urem_8ns_5ns_4_12_1_U167 : component phase2_rpm_cnn_urem_8ns_5ns_4_12_1
    generic map (
        ID => 1,
        NUM_STAGE => 12,
        din0_WIDTH => 8,
        din1_WIDTH => 5,
        dout_WIDTH => 4)
    port map (
        clk => ap_clk,
        reset => ap_rst,
        din0 => add_ln72_fu_392_p2,
        din1 => grp_fu_431_p1,
        ce => ap_const_logic_1,
        dout => grp_fu_431_p2);

    mul_11ns_13ns_23_1_1_U168 : component phase2_rpm_cnn_mul_11ns_13ns_23_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 11,
        din1_WIDTH => 13,
        dout_WIDTH => 23)
    port map (
        din0 => mul_ln72_fu_440_p0,
        din1 => mul_ln72_fu_440_p1,
        dout => mul_ln72_fu_440_p2);

    flow_control_loop_pipe_sequential_init_U : component phase2_rpm_cnn_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready_sig,
        ap_done => ap_done_sig,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter10_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter10 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter11_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter11 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter12_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter12 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter13_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter13 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter2_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter2 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter3_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter3 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter4_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter4 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter5_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter5 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter6_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter6 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter7_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter7 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter8_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter8 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter9_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter9 <= ap_const_logic_0;
            else
                if ((ap_const_boolean_0 = ap_block_pp0_stage0_subdone)) then 
                    ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
                end if; 
            end if;
        end if;
    end process;


    c_fu_104_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln67_fu_308_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    c_fu_104 <= select_ln67_1_fu_346_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    c_fu_104 <= ap_const_lv5_0;
                end if;
            end if; 
        end if;
    end process;

    i_fu_100_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln67_fu_308_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_100 <= add_ln68_fu_362_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_100 <= ap_const_lv8_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten6_fu_108_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln67_fu_308_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten6_fu_108 <= add_ln67_fu_314_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten6_fu_108 <= ap_const_lv12_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                add_ln72_1_reg_566 <= add_ln72_1_fu_425_p2;
                ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
                ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
                empty_reg_548 <= empty_fu_354_p1;
                empty_reg_548_pp0_iter1_reg <= empty_reg_548;
                select_ln67_1_reg_542 <= select_ln67_1_fu_346_p3;
                select_ln67_reg_537 <= select_ln67_fu_332_p3;
                trunc_ln70_reg_555 <= trunc_ln70_fu_358_p1;
                trunc_ln70_reg_555_pp0_iter1_reg <= trunc_ln70_reg_555;
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_0 = ap_block_pp0_stage0_11001)) then
                ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
                ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
                ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
                ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
                ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
                ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
                ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
                ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
                ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
                ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
                empty_reg_548_pp0_iter10_reg <= empty_reg_548_pp0_iter9_reg;
                empty_reg_548_pp0_iter2_reg <= empty_reg_548_pp0_iter1_reg;
                empty_reg_548_pp0_iter3_reg <= empty_reg_548_pp0_iter2_reg;
                empty_reg_548_pp0_iter4_reg <= empty_reg_548_pp0_iter3_reg;
                empty_reg_548_pp0_iter5_reg <= empty_reg_548_pp0_iter4_reg;
                empty_reg_548_pp0_iter6_reg <= empty_reg_548_pp0_iter5_reg;
                empty_reg_548_pp0_iter7_reg <= empty_reg_548_pp0_iter6_reg;
                empty_reg_548_pp0_iter8_reg <= empty_reg_548_pp0_iter7_reg;
                empty_reg_548_pp0_iter9_reg <= empty_reg_548_pp0_iter8_reg;
                select_ln72_reg_590 <= select_ln72_fu_492_p3;
                tmp_2_reg_571 <= mul_ln72_fu_440_p2(22 downto 15);
                tmp_2_reg_571_pp0_iter10_reg <= tmp_2_reg_571_pp0_iter9_reg;
                tmp_2_reg_571_pp0_iter11_reg <= tmp_2_reg_571_pp0_iter10_reg;
                tmp_2_reg_571_pp0_iter12_reg <= tmp_2_reg_571_pp0_iter11_reg;
                tmp_2_reg_571_pp0_iter3_reg <= tmp_2_reg_571;
                tmp_2_reg_571_pp0_iter4_reg <= tmp_2_reg_571_pp0_iter3_reg;
                tmp_2_reg_571_pp0_iter5_reg <= tmp_2_reg_571_pp0_iter4_reg;
                tmp_2_reg_571_pp0_iter6_reg <= tmp_2_reg_571_pp0_iter5_reg;
                tmp_2_reg_571_pp0_iter7_reg <= tmp_2_reg_571_pp0_iter6_reg;
                tmp_2_reg_571_pp0_iter8_reg <= tmp_2_reg_571_pp0_iter7_reg;
                tmp_2_reg_571_pp0_iter9_reg <= tmp_2_reg_571_pp0_iter8_reg;
                trunc_ln70_reg_555_pp0_iter10_reg <= trunc_ln70_reg_555_pp0_iter9_reg;
                trunc_ln70_reg_555_pp0_iter2_reg <= trunc_ln70_reg_555_pp0_iter1_reg;
                trunc_ln70_reg_555_pp0_iter3_reg <= trunc_ln70_reg_555_pp0_iter2_reg;
                trunc_ln70_reg_555_pp0_iter4_reg <= trunc_ln70_reg_555_pp0_iter3_reg;
                trunc_ln70_reg_555_pp0_iter5_reg <= trunc_ln70_reg_555_pp0_iter4_reg;
                trunc_ln70_reg_555_pp0_iter6_reg <= trunc_ln70_reg_555_pp0_iter5_reg;
                trunc_ln70_reg_555_pp0_iter7_reg <= trunc_ln70_reg_555_pp0_iter6_reg;
                trunc_ln70_reg_555_pp0_iter8_reg <= trunc_ln70_reg_555_pp0_iter7_reg;
                trunc_ln70_reg_555_pp0_iter9_reg <= trunc_ln70_reg_555_pp0_iter8_reg;
                trunc_ln72_reg_586 <= trunc_ln72_fu_488_p1;
            end if;
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    add_ln67_1_fu_340_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_c_load) + unsigned(ap_const_lv5_1));
    add_ln67_fu_314_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten6_load) + unsigned(ap_const_lv12_1));
    add_ln68_fu_362_p2 <= std_logic_vector(unsigned(select_ln67_fu_332_p3) + unsigned(ap_const_lv8_1));
    add_ln70_1_fu_456_p4 <= ((empty_reg_548_pp0_iter10_reg & trunc_ln70_reg_555_pp0_iter10_reg) & ap_const_lv1_0);
    add_ln72_1_fu_425_p2 <= std_logic_vector(unsigned(zext_ln72_fu_397_p1) + unsigned(sub_ln72_fu_419_p2));
    add_ln72_fu_392_p2 <= std_logic_vector(unsigned(select_ln67_reg_537) + unsigned(zext_ln68_fu_388_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln67_fu_308_p2)
    begin
        if (((icmp_ln67_fu_308_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_done <= ap_done_sig;

    ap_done_int_assign_proc : process(ap_block_pp0_stage0_subdone, ap_done_reg, ap_loop_exit_ready_pp0_iter12_reg)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_loop_exit_ready_pp0_iter12_reg = ap_const_logic_1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_idle_pp0 = ap_const_logic_1) and (ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1, ap_enable_reg_pp0_iter2, ap_enable_reg_pp0_iter3, ap_enable_reg_pp0_iter4, ap_enable_reg_pp0_iter5, ap_enable_reg_pp0_iter6, ap_enable_reg_pp0_iter7, ap_enable_reg_pp0_iter8, ap_enable_reg_pp0_iter9, ap_enable_reg_pp0_iter10, ap_enable_reg_pp0_iter11, ap_enable_reg_pp0_iter12, ap_enable_reg_pp0_iter13)
    begin
        if (((ap_enable_reg_pp0_iter13 = ap_const_logic_0) and (ap_enable_reg_pp0_iter12 = ap_const_logic_0) and (ap_enable_reg_pp0_iter11 = ap_const_logic_0) and (ap_enable_reg_pp0_iter10 = ap_const_logic_0) and (ap_enable_reg_pp0_iter9 = ap_const_logic_0) and (ap_enable_reg_pp0_iter8 = ap_const_logic_0) and (ap_enable_reg_pp0_iter7 = ap_const_logic_0) and (ap_enable_reg_pp0_iter6 = ap_const_logic_0) and (ap_enable_reg_pp0_iter5 = ap_const_logic_0) and (ap_enable_reg_pp0_iter4 = ap_const_logic_0) and (ap_enable_reg_pp0_iter3 = ap_const_logic_0) and (ap_enable_reg_pp0_iter2 = ap_const_logic_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;
    ap_ready <= ap_ready_sig;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_c_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, c_fu_104)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_c_load <= ap_const_lv5_0;
        else 
            ap_sig_allocacmp_c_load <= c_fu_104;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_100, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv8_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_100;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten6_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten6_fu_108)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_loop_init = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten6_load <= ap_const_lv12_0;
        else 
            ap_sig_allocacmp_indvar_flatten6_load <= indvar_flatten6_fu_108;
        end if; 
    end process;

    conv2_out_address0 <= zext_ln71_fu_477_p1(12 - 1 downto 0);
    conv2_out_address1 <= zext_ln70_fu_464_p1(12 - 1 downto 0);
    conv2_out_ce0 <= conv2_out_ce0_local;

    conv2_out_ce0_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            conv2_out_ce0_local <= ap_const_logic_1;
        else 
            conv2_out_ce0_local <= ap_const_logic_0;
        end if; 
    end process;

    conv2_out_ce1 <= conv2_out_ce1_local;

    conv2_out_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter11, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter11 = ap_const_logic_1))) then 
            conv2_out_ce1_local <= ap_const_logic_1;
        else 
            conv2_out_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    empty_62_fu_383_p2 <= std_logic_vector(shift_left(unsigned(select_ln67_1_reg_542),to_integer(unsigned('0' & ap_const_lv5_1(5-1 downto 0)))));
    empty_fu_354_p1 <= select_ln67_1_fu_346_p3(4 - 1 downto 0);
    grp_fu_431_p1 <= ap_const_lv8_9(5 - 1 downto 0);
    icmp_ln67_fu_308_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten6_load = ap_const_lv12_800) else "0";
    icmp_ln68_fu_326_p2 <= "1" when (ap_sig_allocacmp_i_load = ap_const_lv8_80) else "0";
    icmp_ln72_fu_482_p2 <= "1" when (signed(conv2_out_q1) > signed(conv2_out_q0)) else "0";
    mul_ln72_fu_440_p0 <= mul_ln72_fu_440_p00(11 - 1 downto 0);
    mul_ln72_fu_440_p00 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_1_reg_566),23));
    mul_ln72_fu_440_p1 <= ap_const_lv23_E39(13 - 1 downto 0);
    or_ln71_1_fu_469_p4 <= ((empty_reg_548_pp0_iter10_reg & trunc_ln70_reg_555_pp0_iter10_reg) & ap_const_lv1_1);
    p_shl_fu_401_p3 <= (empty_reg_548 & ap_const_lv7_0);
    pool2_out_1_address1 <= zext_ln72_3_fu_500_p1(8 - 1 downto 0);
    pool2_out_1_ce1 <= pool2_out_1_ce1_local;

    pool2_out_1_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_1_ce1_local <= ap_const_logic_1;
        else 
            pool2_out_1_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_1_d1 <= select_ln72_reg_590;
    pool2_out_1_we1 <= pool2_out_1_we1_local;

    pool2_out_1_we1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln72_reg_586)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln72_reg_586 = ap_const_lv4_1))) then 
            pool2_out_1_we1_local <= ap_const_logic_1;
        else 
            pool2_out_1_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_2_address1 <= zext_ln72_3_fu_500_p1(8 - 1 downto 0);
    pool2_out_2_ce1 <= pool2_out_2_ce1_local;

    pool2_out_2_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_2_ce1_local <= ap_const_logic_1;
        else 
            pool2_out_2_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_2_d1 <= select_ln72_reg_590;
    pool2_out_2_we1 <= pool2_out_2_we1_local;

    pool2_out_2_we1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln72_reg_586)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln72_reg_586 = ap_const_lv4_2))) then 
            pool2_out_2_we1_local <= ap_const_logic_1;
        else 
            pool2_out_2_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_3_address1 <= zext_ln72_3_fu_500_p1(8 - 1 downto 0);
    pool2_out_3_ce1 <= pool2_out_3_ce1_local;

    pool2_out_3_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_3_ce1_local <= ap_const_logic_1;
        else 
            pool2_out_3_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_3_d1 <= select_ln72_reg_590;
    pool2_out_3_we1 <= pool2_out_3_we1_local;

    pool2_out_3_we1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln72_reg_586)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln72_reg_586 = ap_const_lv4_3))) then 
            pool2_out_3_we1_local <= ap_const_logic_1;
        else 
            pool2_out_3_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_4_address1 <= zext_ln72_3_fu_500_p1(8 - 1 downto 0);
    pool2_out_4_ce1 <= pool2_out_4_ce1_local;

    pool2_out_4_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_4_ce1_local <= ap_const_logic_1;
        else 
            pool2_out_4_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_4_d1 <= select_ln72_reg_590;
    pool2_out_4_we1 <= pool2_out_4_we1_local;

    pool2_out_4_we1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln72_reg_586)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln72_reg_586 = ap_const_lv4_4))) then 
            pool2_out_4_we1_local <= ap_const_logic_1;
        else 
            pool2_out_4_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_5_address1 <= zext_ln72_3_fu_500_p1(8 - 1 downto 0);
    pool2_out_5_ce1 <= pool2_out_5_ce1_local;

    pool2_out_5_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_5_ce1_local <= ap_const_logic_1;
        else 
            pool2_out_5_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_5_d1 <= select_ln72_reg_590;
    pool2_out_5_we1 <= pool2_out_5_we1_local;

    pool2_out_5_we1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln72_reg_586)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln72_reg_586 = ap_const_lv4_5))) then 
            pool2_out_5_we1_local <= ap_const_logic_1;
        else 
            pool2_out_5_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_6_address1 <= zext_ln72_3_fu_500_p1(8 - 1 downto 0);
    pool2_out_6_ce1 <= pool2_out_6_ce1_local;

    pool2_out_6_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_6_ce1_local <= ap_const_logic_1;
        else 
            pool2_out_6_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_6_d1 <= select_ln72_reg_590;
    pool2_out_6_we1 <= pool2_out_6_we1_local;

    pool2_out_6_we1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln72_reg_586)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln72_reg_586 = ap_const_lv4_6))) then 
            pool2_out_6_we1_local <= ap_const_logic_1;
        else 
            pool2_out_6_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_7_address1 <= zext_ln72_3_fu_500_p1(8 - 1 downto 0);
    pool2_out_7_ce1 <= pool2_out_7_ce1_local;

    pool2_out_7_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_7_ce1_local <= ap_const_logic_1;
        else 
            pool2_out_7_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_7_d1 <= select_ln72_reg_590;
    pool2_out_7_we1 <= pool2_out_7_we1_local;

    pool2_out_7_we1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln72_reg_586)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln72_reg_586 = ap_const_lv4_7))) then 
            pool2_out_7_we1_local <= ap_const_logic_1;
        else 
            pool2_out_7_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_8_address1 <= zext_ln72_3_fu_500_p1(8 - 1 downto 0);
    pool2_out_8_ce1 <= pool2_out_8_ce1_local;

    pool2_out_8_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_8_ce1_local <= ap_const_logic_1;
        else 
            pool2_out_8_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_8_d1 <= select_ln72_reg_590;
    pool2_out_8_we1 <= pool2_out_8_we1_local;

    pool2_out_8_we1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln72_reg_586)
    begin
        if ((not((trunc_ln72_reg_586 = ap_const_lv4_0)) and not((trunc_ln72_reg_586 = ap_const_lv4_1)) and not((trunc_ln72_reg_586 = ap_const_lv4_2)) and not((trunc_ln72_reg_586 = ap_const_lv4_3)) and not((trunc_ln72_reg_586 = ap_const_lv4_4)) and not((trunc_ln72_reg_586 = ap_const_lv4_5)) and not((trunc_ln72_reg_586 = ap_const_lv4_6)) and not((trunc_ln72_reg_586 = ap_const_lv4_7)) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_8_we1_local <= ap_const_logic_1;
        else 
            pool2_out_8_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_address1 <= zext_ln72_3_fu_500_p1(8 - 1 downto 0);
    pool2_out_ce1 <= pool2_out_ce1_local;

    pool2_out_ce1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1))) then 
            pool2_out_ce1_local <= ap_const_logic_1;
        else 
            pool2_out_ce1_local <= ap_const_logic_0;
        end if; 
    end process;

    pool2_out_d1 <= select_ln72_reg_590;
    pool2_out_we1 <= pool2_out_we1_local;

    pool2_out_we1_local_assign_proc : process(ap_enable_reg_pp0_iter13, ap_block_pp0_stage0_11001, trunc_ln72_reg_586)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter13 = ap_const_logic_1) and (trunc_ln72_reg_586 = ap_const_lv4_0))) then 
            pool2_out_we1_local <= ap_const_logic_1;
        else 
            pool2_out_we1_local <= ap_const_logic_0;
        end if; 
    end process;

    select_ln67_1_fu_346_p3 <= 
        add_ln67_1_fu_340_p2 when (icmp_ln68_fu_326_p2(0) = '1') else 
        ap_sig_allocacmp_c_load;
    select_ln67_fu_332_p3 <= 
        ap_const_lv8_0 when (icmp_ln68_fu_326_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln72_fu_492_p3 <= 
        conv2_out_q1 when (icmp_ln72_fu_482_p2(0) = '1') else 
        conv2_out_q0;
    sub_ln72_fu_419_p2 <= std_logic_vector(unsigned(p_shl_fu_401_p3) - unsigned(zext_ln72_1_fu_415_p1));
    tmp_fu_408_p3 <= (select_ln67_1_reg_542 & ap_const_lv1_0);
    trunc_ln70_fu_358_p1 <= select_ln67_fu_332_p3(7 - 1 downto 0);
    trunc_ln72_fu_488_p1 <= grp_fu_431_p2(4 - 1 downto 0);
    zext_ln68_fu_388_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(empty_62_fu_383_p2),8));
    zext_ln70_fu_464_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln70_1_fu_456_p4),64));
    zext_ln71_fu_477_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(or_ln71_1_fu_469_p4),64));
    zext_ln72_1_fu_415_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_fu_408_p3),11));
    zext_ln72_3_fu_500_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_2_reg_571_pp0_iter12_reg),64));
    zext_ln72_fu_397_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(add_ln72_fu_392_p2),11));
end behav;
