-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================
library ieee; 
use ieee.std_logic_1164.all; 
use ieee.std_logic_unsigned.all;

entity phase2_rpm_cnn_conv1d_same_q_3_conv3_bias_q_ROM_AUTO_1R is 
    generic(
             DataWidth     : integer := 8; 
             AddressWidth     : integer := 5; 
             AddressRange    : integer := 32
    ); 
    port (
 
          address0        : in std_logic_vector(AddressWidth-1 downto 0); 
          ce0             : in std_logic; 
          q0              : out std_logic_vector(DataWidth-1 downto 0);

          reset               : in std_logic;
          clk                 : in std_logic
    ); 
end entity; 


architecture rtl of phase2_rpm_cnn_conv1d_same_q_3_conv3_bias_q_ROM_AUTO_1R is 
 
signal address0_tmp : std_logic_vector(AddressWidth-1 downto 0); 

type mem_array is array (0 to AddressRange-1) of std_logic_vector (DataWidth-1 downto 0); 

signal mem0 : mem_array := (
    0 => "11011111", 1 => "11110101", 2 => "11111011", 3 => "10110011", 
    4 => "11000111", 5 => "00001110", 6 => "01110000", 7 => "11100101", 
    8 => "01000101", 9 => "11100011", 10 => "00001111", 11 => "10100011", 
    12 => "01111111", 13 => "01101110", 14 => "11111101", 15 => "01010110", 
    16 => "00110101", 17 => "01101100", 18 => "01010100", 19 => "10100110", 
    20 => "11000100", 21 => "11000110", 22 => "00101001", 23 => "10011111", 
    24 => "11000011", 25 => "11011100", 26 => "10001100", 27 => "00110101", 
    28 => "11100000", 29 => "11100110", 30 => "01100011", 31 => "11010111");



begin 

 
memory_access_guard_0: process (address0) 
begin
      address0_tmp <= address0;
--synthesis translate_off
      if (CONV_INTEGER(address0) > AddressRange-1) then
           address0_tmp <= (others => '0');
      else 
           address0_tmp <= address0;
      end if;
--synthesis translate_on
end process;

p_rom_access: process (clk)  
begin 
    if (clk'event and clk = '1') then
 
        if (ce0 = '1') then  
            q0 <= mem0(CONV_INTEGER(address0_tmp)); 
        end if;

end if;
end process;

end rtl;

