-- ==============================================================
-- Generated by Vitis HLS v2024.2
-- Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
-- ==============================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity phase2_rpm_cnn_dense_q_1 is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    input_0_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_1_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_2_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_3_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_4_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_5_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_6_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_7_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_8_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_9_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_10_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_11_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_12_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_13_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_14_val : IN STD_LOGIC_VECTOR (16 downto 0);
    input_15_val : IN STD_LOGIC_VECTOR (16 downto 0);
    output_r : OUT STD_LOGIC_VECTOR (17 downto 0);
    output_r_ap_vld : OUT STD_LOGIC );
end;


architecture behav of phase2_rpm_cnn_dense_q_1 is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    constant ap_ST_fsm_state2 : STD_LOGIC_VECTOR (4 downto 0) := "00010";
    constant ap_ST_fsm_state3 : STD_LOGIC_VECTOR (4 downto 0) := "00100";
    constant ap_ST_fsm_state4 : STD_LOGIC_VECTOR (4 downto 0) := "01000";
    constant ap_ST_fsm_state5 : STD_LOGIC_VECTOR (4 downto 0) := "10000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";
    constant ap_const_lv32_3 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000011";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv32_4 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000100";
    constant ap_const_lv8_0 : STD_LOGIC_VECTOR (7 downto 0) := "00000000";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv2_0 : STD_LOGIC_VECTOR (1 downto 0) := "00";
    constant ap_const_lv49_1FFFFCEFB0000 : STD_LOGIC_VECTOR (48 downto 0) := "1111111111111111111001110111110110000000000000000";
    constant ap_const_lv32_30 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000110000";
    constant ap_const_lv32_16 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010110";
    constant ap_const_lv32_27 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000100111";
    constant ap_const_lv32_15 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010101";
    constant ap_const_lv32_11 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000010001";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_29 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101001";
    constant ap_const_lv8_FF : STD_LOGIC_VECTOR (7 downto 0) := "11111111";
    constant ap_const_lv32_28 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000101000";
    constant ap_const_lv9_1FF : STD_LOGIC_VECTOR (8 downto 0) := "111111111";
    constant ap_const_lv9_0 : STD_LOGIC_VECTOR (8 downto 0) := "000000000";
    constant ap_const_lv18_1FFFF : STD_LOGIC_VECTOR (17 downto 0) := "011111111111111111";
    constant ap_const_lv18_20000 : STD_LOGIC_VECTOR (17 downto 0) := "100000000000000000";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (4 downto 0) := "00001";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal add_ln109_2_fu_267_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal add_ln109_2_reg_585 : STD_LOGIC_VECTOR (48 downto 0);
    signal ap_CS_fsm_state3 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state3 : signal is "none";
    signal add_ln109_fu_289_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal add_ln109_reg_590 : STD_LOGIC_VECTOR (48 downto 0);
    signal ap_CS_fsm_state4 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state4 : signal is "none";
    signal tmp_57_reg_595 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln109_1_fu_333_p2 : STD_LOGIC_VECTOR (17 downto 0);
    signal add_ln109_1_reg_601 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_60_fu_339_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_60_reg_606 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln109_fu_353_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln109_reg_612 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_fu_369_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_reg_619 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_fu_385_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_1_reg_624 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_2_fu_391_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal icmp_ln109_2_reg_631 : STD_LOGIC_VECTOR (0 downto 0);
    signal grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start : STD_LOGIC;
    signal grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done : STD_LOGIC;
    signal grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_idle : STD_LOGIC;
    signal grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_ready : STD_LOGIC;
    signal grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out : STD_LOGIC_VECTOR (39 downto 0);
    signal grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out_ap_vld : STD_LOGIC;
    signal grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg : STD_LOGIC := '0';
    signal ap_CS_fsm_state2 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state2 : signal is "none";
    signal ap_CS_fsm_state5 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state5 : signal is "none";
    signal tmp_fu_243_p3 : STD_LOGIC_VECTOR (47 downto 0);
    signal tmp_55_fu_255_p3 : STD_LOGIC_VECTOR (43 downto 0);
    signal sext_ln109_fu_251_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal sext_ln109_1_fu_263_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp_56_fu_273_p3 : STD_LOGIC_VECTOR (41 downto 0);
    signal sext_ln109_2_fu_280_p1 : STD_LOGIC_VECTOR (48 downto 0);
    signal sub_ln109_fu_284_p2 : STD_LOGIC_VECTOR (48 downto 0);
    signal tmp_58_fu_313_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal trunc_ln_fu_303_p4 : STD_LOGIC_VECTOR (17 downto 0);
    signal zext_ln109_fu_329_p1 : STD_LOGIC_VECTOR (17 downto 0);
    signal tmp_59_fu_321_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln109_fu_347_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal tmp_23_fu_359_p4 : STD_LOGIC_VECTOR (7 downto 0);
    signal tmp_24_fu_375_p4 : STD_LOGIC_VECTOR (8 downto 0);
    signal tmp_61_fu_397_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln109_1_fu_409_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln109_1_fu_415_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln109_fu_404_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln109_2_fu_430_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln109_fu_436_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln109_3_fu_441_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln109_1_fu_420_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln109_2_fu_426_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln109_4_fu_452_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln109_2_fu_457_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal xor_ln109_4_fu_463_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln109_3_fu_446_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal and_ln109_5_fu_469_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal or_ln109_1_fu_482_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal select_ln109_2_fu_474_p3 : STD_LOGIC_VECTOR (17 downto 0);
    signal ap_NS_fsm : STD_LOGIC_VECTOR (4 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_ST_fsm_state2_blk : STD_LOGIC;
    signal ap_ST_fsm_state3_blk : STD_LOGIC;
    signal ap_ST_fsm_state4_blk : STD_LOGIC;
    signal ap_ST_fsm_state5_blk : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2 IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_idle : OUT STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        input_0_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_1_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_2_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_3_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_4_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_5_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_6_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_7_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_8_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_9_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_10_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_11_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_12_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_13_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_14_val : IN STD_LOGIC_VECTOR (16 downto 0);
        input_15_val : IN STD_LOGIC_VECTOR (16 downto 0);
        acc_out : OUT STD_LOGIC_VECTOR (39 downto 0);
        acc_out_ap_vld : OUT STD_LOGIC );
    end component;



begin
    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201 : component phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start,
        ap_done => grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done,
        ap_idle => grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_idle,
        ap_ready => grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_ready,
        input_0_val => input_0_val,
        input_1_val => input_1_val,
        input_2_val => input_2_val,
        input_3_val => input_3_val,
        input_4_val => input_4_val,
        input_5_val => input_5_val,
        input_6_val => input_6_val,
        input_7_val => input_7_val,
        input_8_val => input_8_val,
        input_9_val => input_9_val,
        input_10_val => input_10_val,
        input_11_val => input_11_val,
        input_12_val => input_12_val,
        input_13_val => input_13_val,
        input_14_val => input_14_val,
        input_15_val => input_15_val,
        acc_out => grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out,
        acc_out_ap_vld => grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out_ap_vld);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg <= ap_const_logic_0;
            else
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then 
                    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg <= ap_const_logic_1;
                elsif ((grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_ready = ap_const_logic_1)) then 
                    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg <= ap_const_logic_0;
                end if; 
            end if;
        end if;
    end process;

    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state4)) then
                add_ln109_1_reg_601 <= add_ln109_1_fu_333_p2;
                    add_ln109_reg_590(48 downto 2) <= add_ln109_fu_289_p2(48 downto 2);
                and_ln109_reg_612 <= and_ln109_fu_353_p2;
                icmp_ln109_1_reg_624 <= icmp_ln109_1_fu_385_p2;
                icmp_ln109_2_reg_631 <= icmp_ln109_2_fu_391_p2;
                icmp_ln109_reg_619 <= icmp_ln109_fu_369_p2;
                tmp_57_reg_595 <= add_ln109_fu_289_p2(48 downto 48);
                tmp_60_reg_606 <= add_ln109_1_fu_333_p2(17 downto 17);
            end if;
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_logic_1 = ap_CS_fsm_state3)) then
                    add_ln109_2_reg_585(48 downto 4) <= add_ln109_2_fu_267_p2(48 downto 4);
            end if;
        end if;
    end process;
    add_ln109_2_reg_585(3 downto 0) <= "0000";
    add_ln109_reg_590(1 downto 0) <= "00";

    ap_NS_fsm_assign_proc : process (ap_start, ap_CS_fsm, ap_CS_fsm_state1, grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done, ap_CS_fsm_state2)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state2;
                else
                    ap_NS_fsm <= ap_ST_fsm_state1;
                end if;
            when ap_ST_fsm_state2 => 
                if (((ap_const_logic_1 = ap_CS_fsm_state2) and (grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done = ap_const_logic_1))) then
                    ap_NS_fsm <= ap_ST_fsm_state3;
                else
                    ap_NS_fsm <= ap_ST_fsm_state2;
                end if;
            when ap_ST_fsm_state3 => 
                ap_NS_fsm <= ap_ST_fsm_state4;
            when ap_ST_fsm_state4 => 
                ap_NS_fsm <= ap_ST_fsm_state5;
            when ap_ST_fsm_state5 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "XXXXX";
        end case;
    end process;
    add_ln109_1_fu_333_p2 <= std_logic_vector(unsigned(trunc_ln_fu_303_p4) + unsigned(zext_ln109_fu_329_p1));
    add_ln109_2_fu_267_p2 <= std_logic_vector(signed(sext_ln109_fu_251_p1) + signed(sext_ln109_1_fu_263_p1));
    add_ln109_fu_289_p2 <= std_logic_vector(unsigned(sub_ln109_fu_284_p2) + unsigned(ap_const_lv49_1FFFFCEFB0000));
    and_ln109_1_fu_415_p2 <= (xor_ln109_1_fu_409_p2 and icmp_ln109_reg_619);
    and_ln109_2_fu_426_p2 <= (icmp_ln109_1_reg_624 and and_ln109_reg_612);
    and_ln109_3_fu_446_p2 <= (xor_ln109_3_fu_441_p2 and or_ln109_fu_436_p2);
    and_ln109_4_fu_452_p2 <= (tmp_60_reg_606 and select_ln109_1_fu_420_p3);
    and_ln109_5_fu_469_p2 <= (xor_ln109_4_fu_463_p2 and tmp_57_reg_595);
    and_ln109_fu_353_p2 <= (xor_ln109_fu_347_p2 and tmp_59_fu_321_p3);
    ap_CS_fsm_state1 <= ap_CS_fsm(0);
    ap_CS_fsm_state2 <= ap_CS_fsm(1);
    ap_CS_fsm_state3 <= ap_CS_fsm(2);
    ap_CS_fsm_state4 <= ap_CS_fsm(3);
    ap_CS_fsm_state5 <= ap_CS_fsm(4);

    ap_ST_fsm_state1_blk_assign_proc : process(ap_start)
    begin
        if ((ap_start = ap_const_logic_0)) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_ST_fsm_state2_blk_assign_proc : process(grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done)
    begin
        if ((grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done = ap_const_logic_0)) then 
            ap_ST_fsm_state2_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state2_blk <= ap_const_logic_0;
        end if; 
    end process;

    ap_ST_fsm_state3_blk <= ap_const_logic_0;
    ap_ST_fsm_state4_blk <= ap_const_logic_0;
    ap_ST_fsm_state5_blk <= ap_const_logic_0;

    ap_done_assign_proc : process(ap_start, ap_CS_fsm_state1, ap_CS_fsm_state5)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state5) or ((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0)))) then 
            ap_done <= ap_const_logic_1;
        else 
            ap_done <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_start, ap_CS_fsm_state1)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_start = ap_const_logic_0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_ready_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            ap_ready <= ap_const_logic_1;
        else 
            ap_ready <= ap_const_logic_0;
        end if; 
    end process;

    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start <= grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg;
    icmp_ln109_1_fu_385_p2 <= "1" when (tmp_24_fu_375_p4 = ap_const_lv9_1FF) else "0";
    icmp_ln109_2_fu_391_p2 <= "1" when (tmp_24_fu_375_p4 = ap_const_lv9_0) else "0";
    icmp_ln109_fu_369_p2 <= "1" when (tmp_23_fu_359_p4 = ap_const_lv8_FF) else "0";
    or_ln109_1_fu_482_p2 <= (and_ln109_5_fu_469_p2 or and_ln109_3_fu_446_p2);
    or_ln109_2_fu_457_p2 <= (and_ln109_4_fu_452_p2 or and_ln109_2_fu_426_p2);
    or_ln109_fu_436_p2 <= (xor_ln109_2_fu_430_p2 or tmp_60_reg_606);
    output_r <= 
        select_ln109_2_fu_474_p3 when (or_ln109_1_fu_482_p2(0) = '1') else 
        add_ln109_1_reg_601;

    output_r_ap_vld_assign_proc : process(ap_CS_fsm_state5)
    begin
        if ((ap_const_logic_1 = ap_CS_fsm_state5)) then 
            output_r_ap_vld <= ap_const_logic_1;
        else 
            output_r_ap_vld <= ap_const_logic_0;
        end if; 
    end process;

    select_ln109_1_fu_420_p3 <= 
        and_ln109_1_fu_415_p2 when (and_ln109_reg_612(0) = '1') else 
        icmp_ln109_1_reg_624;
    select_ln109_2_fu_474_p3 <= 
        ap_const_lv18_1FFFF when (and_ln109_3_fu_446_p2(0) = '1') else 
        ap_const_lv18_20000;
    select_ln109_fu_404_p3 <= 
        icmp_ln109_1_reg_624 when (and_ln109_reg_612(0) = '1') else 
        icmp_ln109_2_reg_631;
        sext_ln109_1_fu_263_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_55_fu_255_p3),49));

        sext_ln109_2_fu_280_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_56_fu_273_p3),49));

        sext_ln109_fu_251_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_fu_243_p3),49));

    sub_ln109_fu_284_p2 <= std_logic_vector(unsigned(add_ln109_2_reg_585) - unsigned(sext_ln109_2_fu_280_p1));
    tmp_23_fu_359_p4 <= add_ln109_fu_289_p2(48 downto 41);
    tmp_24_fu_375_p4 <= add_ln109_fu_289_p2(48 downto 40);
    tmp_55_fu_255_p3 <= (grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out & ap_const_lv4_0);
    tmp_56_fu_273_p3 <= (grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out & ap_const_lv2_0);
    tmp_58_fu_313_p3 <= add_ln109_fu_289_p2(21 downto 21);
    tmp_59_fu_321_p3 <= add_ln109_fu_289_p2(39 downto 39);
    tmp_60_fu_339_p3 <= add_ln109_1_fu_333_p2(17 downto 17);
    tmp_61_fu_397_p3 <= add_ln109_reg_590(40 downto 40);
    tmp_fu_243_p3 <= (grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out & ap_const_lv8_0);
    trunc_ln_fu_303_p4 <= add_ln109_fu_289_p2(39 downto 22);
    xor_ln109_1_fu_409_p2 <= (tmp_61_fu_397_p3 xor ap_const_lv1_1);
    xor_ln109_2_fu_430_p2 <= (select_ln109_fu_404_p3 xor ap_const_lv1_1);
    xor_ln109_3_fu_441_p2 <= (tmp_57_reg_595 xor ap_const_lv1_1);
    xor_ln109_4_fu_463_p2 <= (or_ln109_2_fu_457_p2 xor ap_const_lv1_1);
    xor_ln109_fu_347_p2 <= (tmp_60_fu_339_p3 xor ap_const_lv1_1);
    zext_ln109_fu_329_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(tmp_58_fu_313_p3),18));
end behav;
