// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================
`timescale 1 ns / 1 ps 

module phase2_rpm_cnn_ctlz_32_32_1_1 (din,dout);

parameter din_WIDTH=1;
parameter dout_WIDTH=1;


input [din_WIDTH-1:0] din;
output [dout_WIDTH-1:0] dout;

reg [dout_WIDTH-1:0] dout_tmp;



always @ (din) begin  
    if (din[31] == 1'b1) begin
        dout_tmp = 0; 
    end else if (din[30] == 1'b1) begin
        dout_tmp = 1; 
    end else if (din[29] == 1'b1) begin
        dout_tmp = 2; 
    end else if (din[28] == 1'b1) begin
        dout_tmp = 3; 
    end else if (din[27] == 1'b1) begin
        dout_tmp = 4; 
    end else if (din[26] == 1'b1) begin
        dout_tmp = 5; 
    end else if (din[25] == 1'b1) begin
        dout_tmp = 6; 
    end else if (din[24] == 1'b1) begin
        dout_tmp = 7; 
    end else if (din[23] == 1'b1) begin
        dout_tmp = 8; 
    end else if (din[22] == 1'b1) begin
        dout_tmp = 9; 
    end else if (din[21] == 1'b1) begin
        dout_tmp = 10; 
    end else if (din[20] == 1'b1) begin
        dout_tmp = 11; 
    end else if (din[19] == 1'b1) begin
        dout_tmp = 12; 
    end else if (din[18] == 1'b1) begin
        dout_tmp = 13; 
    end else if (din[17] == 1'b1) begin
        dout_tmp = 14; 
    end else if (din[16] == 1'b1) begin
        dout_tmp = 15; 
    end else if (din[15] == 1'b1) begin
        dout_tmp = 16; 
    end else if (din[14] == 1'b1) begin
        dout_tmp = 17; 
    end else if (din[13] == 1'b1) begin
        dout_tmp = 18; 
    end else if (din[12] == 1'b1) begin
        dout_tmp = 19; 
    end else if (din[11] == 1'b1) begin
        dout_tmp = 20; 
    end else if (din[10] == 1'b1) begin
        dout_tmp = 21; 
    end else if (din[9] == 1'b1) begin
        dout_tmp = 22; 
    end else if (din[8] == 1'b1) begin
        dout_tmp = 23; 
    end else if (din[7] == 1'b1) begin
        dout_tmp = 24; 
    end else if (din[6] == 1'b1) begin
        dout_tmp = 25; 
    end else if (din[5] == 1'b1) begin
        dout_tmp = 26; 
    end else if (din[4] == 1'b1) begin
        dout_tmp = 27; 
    end else if (din[3] == 1'b1) begin
        dout_tmp = 28; 
    end else if (din[2] == 1'b1) begin
        dout_tmp = 29; 
    end else if (din[1] == 1'b1) begin
        dout_tmp = 30; 
    end else if (din[0] == 1'b1) begin
        dout_tmp = 31;
    end else begin
        dout_tmp = 32;
    end
end


assign dout = dout_tmp;




endmodule
