// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_val,
        input_1_val,
        input_2_val,
        input_3_val,
        input_4_val,
        input_5_val,
        input_6_val,
        input_7_val,
        input_8_val,
        input_9_val,
        input_10_val,
        input_11_val,
        input_12_val,
        input_13_val,
        input_14_val,
        input_15_val,
        acc_out,
        acc_out_ap_vld
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [16:0] input_0_val;
input  [16:0] input_1_val;
input  [16:0] input_2_val;
input  [16:0] input_3_val;
input  [16:0] input_4_val;
input  [16:0] input_5_val;
input  [16:0] input_6_val;
input  [16:0] input_7_val;
input  [16:0] input_8_val;
input  [16:0] input_9_val;
input  [16:0] input_10_val;
input  [16:0] input_11_val;
input  [16:0] input_12_val;
input  [16:0] input_13_val;
input  [16:0] input_14_val;
input  [16:0] input_15_val;
output  [39:0] acc_out;
output   acc_out_ap_vld;

reg ap_idle;
reg acc_out_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    ap_block_state1_pp0_stage0_iter0;
wire   [0:0] icmp_ln105_fu_277_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_CS_fsm_state5;
wire   [3:0] fc2_weight_q_address0;
wire   [7:0] fc2_weight_q_q0;
wire   [16:0] tmp_s_fu_298_p35;
reg   [16:0] tmp_s_reg_592;
reg   [7:0] fc2_weight_q_load_reg_602;
wire    ap_CS_fsm_state2;
wire  signed [46:0] mul_ln107_fu_260_p2;
reg  signed [46:0] mul_ln107_reg_607;
wire    ap_CS_fsm_state3;
reg   [0:0] tmp_52_reg_612;
wire   [39:0] acc_4_fu_460_p2;
reg   [39:0] acc_4_reg_617;
wire    ap_CS_fsm_state4;
wire   [0:0] and_ln107_1_fu_522_p2;
reg   [0:0] and_ln107_1_reg_622;
wire   [0:0] or_ln107_1_fu_546_p2;
reg   [0:0] or_ln107_1_reg_627;
wire   [63:0] zext_ln105_fu_289_p1;
reg   [39:0] acc_fu_136;
wire   [39:0] acc_5_fu_559_p3;
wire    ap_loop_init;
reg   [4:0] i_fu_140;
wire   [4:0] add_ln105_fu_283_p2;
reg   [4:0] ap_sig_allocacmp_i_6;
reg    fc2_weight_q_ce0_local;
wire   [22:0] mul_ln107_fu_260_p1;
wire   [16:0] tmp_s_fu_298_p33;
wire   [3:0] tmp_s_fu_298_p34;
wire   [22:0] shl_ln_fu_375_p3;
wire  signed [23:0] shl_ln107_1_fu_382_p3;
wire   [55:0] shl_ln107_2_fu_410_p3;
wire  signed [56:0] sext_ln107_1_fu_418_p1;
wire  signed [56:0] sext_ln107_2_fu_422_p1;
wire   [56:0] add_ln107_fu_425_p2;
wire   [39:0] acc_1_fu_439_p4;
wire   [39:0] zext_ln107_fu_457_p1;
wire   [0:0] tmp_54_fu_466_p3;
wire   [0:0] tmp_53_fu_449_p3;
wire   [0:0] xor_ln107_fu_474_p2;
wire   [0:0] xor_ln107_2_fu_486_p2;
wire   [0:0] tmp_fu_431_p3;
wire   [0:0] xor_ln107_4_fu_504_p2;
wire   [0:0] or_ln107_2_fu_492_p2;
wire   [0:0] xor_ln107_3_fu_510_p2;
wire   [0:0] or_ln107_fu_516_p2;
wire   [0:0] xor_ln107_1_fu_498_p2;
wire   [0:0] and_ln107_fu_480_p2;
wire   [0:0] or_ln107_3_fu_528_p2;
wire   [0:0] xor_ln107_5_fu_534_p2;
wire   [0:0] and_ln107_2_fu_540_p2;
wire   [39:0] select_ln107_fu_552_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [46:0] mul_ln107_fu_260_p10;
wire   [3:0] tmp_s_fu_298_p1;
wire   [3:0] tmp_s_fu_298_p3;
wire   [3:0] tmp_s_fu_298_p5;
wire   [3:0] tmp_s_fu_298_p7;
wire   [3:0] tmp_s_fu_298_p9;
wire   [3:0] tmp_s_fu_298_p11;
wire   [3:0] tmp_s_fu_298_p13;
wire   [3:0] tmp_s_fu_298_p15;
wire  signed [3:0] tmp_s_fu_298_p17;
wire  signed [3:0] tmp_s_fu_298_p19;
wire  signed [3:0] tmp_s_fu_298_p21;
wire  signed [3:0] tmp_s_fu_298_p23;
wire  signed [3:0] tmp_s_fu_298_p25;
wire  signed [3:0] tmp_s_fu_298_p27;
wire  signed [3:0] tmp_s_fu_298_p29;
wire  signed [3:0] tmp_s_fu_298_p31;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 acc_fu_136 = 40'd0;
#0 i_fu_140 = 5'd0;
#0 ap_done_reg = 1'b0;
end

phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2_fc2_weight_q_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
fc2_weight_q_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc2_weight_q_address0),
    .ce0(fc2_weight_q_ce0_local),
    .q0(fc2_weight_q_q0)
);

phase2_rpm_cnn_mul_24s_23ns_47_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 23 ),
    .dout_WIDTH( 47 ))
mul_24s_23ns_47_1_1_U419(
    .din0(shl_ln107_1_fu_382_p3),
    .din1(mul_ln107_fu_260_p1),
    .dout(mul_ln107_fu_260_p2)
);

(* dissolve_hierarchy = "yes" *) phase2_rpm_cnn_sparsemux_33_4_17_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 4'h0 ),
    .din0_WIDTH( 17 ),
    .CASE1( 4'h1 ),
    .din1_WIDTH( 17 ),
    .CASE2( 4'h2 ),
    .din2_WIDTH( 17 ),
    .CASE3( 4'h3 ),
    .din3_WIDTH( 17 ),
    .CASE4( 4'h4 ),
    .din4_WIDTH( 17 ),
    .CASE5( 4'h5 ),
    .din5_WIDTH( 17 ),
    .CASE6( 4'h6 ),
    .din6_WIDTH( 17 ),
    .CASE7( 4'h7 ),
    .din7_WIDTH( 17 ),
    .CASE8( 4'h8 ),
    .din8_WIDTH( 17 ),
    .CASE9( 4'h9 ),
    .din9_WIDTH( 17 ),
    .CASE10( 4'hA ),
    .din10_WIDTH( 17 ),
    .CASE11( 4'hB ),
    .din11_WIDTH( 17 ),
    .CASE12( 4'hC ),
    .din12_WIDTH( 17 ),
    .CASE13( 4'hD ),
    .din13_WIDTH( 17 ),
    .CASE14( 4'hE ),
    .din14_WIDTH( 17 ),
    .CASE15( 4'hF ),
    .din15_WIDTH( 17 ),
    .def_WIDTH( 17 ),
    .sel_WIDTH( 4 ),
    .dout_WIDTH( 17 ))
sparsemux_33_4_17_1_1_U420(
    .din0(input_0_val),
    .din1(input_1_val),
    .din2(input_2_val),
    .din3(input_3_val),
    .din4(input_4_val),
    .din5(input_5_val),
    .din6(input_6_val),
    .din7(input_7_val),
    .din8(input_8_val),
    .din9(input_9_val),
    .din10(input_10_val),
    .din11(input_11_val),
    .din12(input_12_val),
    .din13(input_13_val),
    .din14(input_14_val),
    .din15(input_15_val),
    .def(tmp_s_fu_298_p33),
    .sel(tmp_s_fu_298_p34),
    .dout(tmp_s_fu_298_p35)
);

phase2_rpm_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        acc_fu_136 <= 40'd0;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        acc_fu_136 <= acc_5_fu_559_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        if ((icmp_ln105_fu_277_p2 == 1'd0)) begin
            i_fu_140 <= add_ln105_fu_283_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_140 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        acc_4_reg_617 <= acc_4_fu_460_p2;
        and_ln107_1_reg_622 <= and_ln107_1_fu_522_p2;
        or_ln107_1_reg_627 <= or_ln107_1_fu_546_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc2_weight_q_load_reg_602 <= fc2_weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        mul_ln107_reg_607 <= mul_ln107_fu_260_p2;
        tmp_52_reg_612 <= mul_ln107_fu_260_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_s_reg_592 <= tmp_s_fu_298_p35;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (icmp_ln105_fu_277_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        acc_out_ap_vld = 1'b1;
    end else begin
        acc_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_block_state1_pp0_stage0_iter0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((icmp_ln105_fu_277_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_6 = 5'd0;
    end else begin
        ap_sig_allocacmp_i_6 = i_fu_140;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
        fc2_weight_q_ce0_local = 1'b1;
    end else begin
        fc2_weight_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((icmp_ln105_fu_277_p2 == 1'd1) & (1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else if (((1'b0 == ap_block_state1_pp0_stage0_iter0) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            ap_NS_fsm = ap_ST_fsm_state3;
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_1_fu_439_p4 = {{add_ln107_fu_425_p2[55:16]}};

assign acc_4_fu_460_p2 = (acc_1_fu_439_p4 + zext_ln107_fu_457_p1);

assign acc_5_fu_559_p3 = ((or_ln107_1_reg_627[0:0] == 1'b1) ? select_ln107_fu_552_p3 : acc_4_reg_617);

assign acc_out = acc_fu_136;

assign add_ln105_fu_283_p2 = (ap_sig_allocacmp_i_6 + 5'd1);

assign add_ln107_fu_425_p2 = ($signed(sext_ln107_1_fu_418_p1) + $signed(sext_ln107_2_fu_422_p1));

assign and_ln107_1_fu_522_p2 = (xor_ln107_1_fu_498_p2 & or_ln107_fu_516_p2);

assign and_ln107_2_fu_540_p2 = (xor_ln107_5_fu_534_p2 & tmp_fu_431_p3);

assign and_ln107_fu_480_p2 = (xor_ln107_fu_474_p2 & tmp_53_fu_449_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = (ap_start_int == 1'b0);
end

assign ap_done = ap_done_sig;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign fc2_weight_q_address0 = zext_ln105_fu_289_p1;

assign icmp_ln105_fu_277_p2 = ((ap_sig_allocacmp_i_6 == 5'd16) ? 1'b1 : 1'b0);

assign mul_ln107_fu_260_p1 = mul_ln107_fu_260_p10;

assign mul_ln107_fu_260_p10 = shl_ln_fu_375_p3;

assign or_ln107_1_fu_546_p2 = (and_ln107_2_fu_540_p2 | and_ln107_1_fu_522_p2);

assign or_ln107_2_fu_492_p2 = (xor_ln107_2_fu_486_p2 | tmp_54_fu_466_p3);

assign or_ln107_3_fu_528_p2 = (tmp_54_fu_466_p3 | and_ln107_fu_480_p2);

assign or_ln107_fu_516_p2 = (xor_ln107_3_fu_510_p2 | tmp_54_fu_466_p3);

assign select_ln107_fu_552_p3 = ((and_ln107_1_reg_622[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign sext_ln107_1_fu_418_p1 = $signed(shl_ln107_2_fu_410_p3);

assign sext_ln107_2_fu_422_p1 = mul_ln107_reg_607;

assign shl_ln107_1_fu_382_p3 = {{fc2_weight_q_load_reg_602}, {16'd0}};

assign shl_ln107_2_fu_410_p3 = {{acc_fu_136}, {16'd0}};

assign shl_ln_fu_375_p3 = {{tmp_s_reg_592}, {6'd0}};

assign tmp_53_fu_449_p3 = add_ln107_fu_425_p2[32'd55];

assign tmp_54_fu_466_p3 = acc_4_fu_460_p2[32'd39];

assign tmp_fu_431_p3 = add_ln107_fu_425_p2[32'd56];

assign tmp_s_fu_298_p33 = 'bx;

assign tmp_s_fu_298_p34 = ap_sig_allocacmp_i_6[3:0];

assign xor_ln107_1_fu_498_p2 = (tmp_fu_431_p3 ^ 1'd1);

assign xor_ln107_2_fu_486_p2 = (tmp_53_fu_449_p3 ^ 1'd1);

assign xor_ln107_3_fu_510_p2 = (xor_ln107_4_fu_504_p2 ^ or_ln107_2_fu_492_p2);

assign xor_ln107_4_fu_504_p2 = (tmp_fu_431_p3 ^ 1'd1);

assign xor_ln107_5_fu_534_p2 = (or_ln107_3_fu_528_p2 ^ 1'd1);

assign xor_ln107_fu_474_p2 = (tmp_54_fu_466_p3 ^ 1'd1);

assign zext_ln105_fu_289_p1 = ap_sig_allocacmp_i_6;

assign zext_ln107_fu_457_p1 = tmp_52_reg_612;

endmodule //phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2
