// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module phase2_rpm_cnn_dense_q (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_val,
        input_1_val,
        input_2_val,
        input_3_val,
        input_4_val,
        input_5_val,
        input_6_val,
        input_7_val,
        input_8_val,
        input_9_val,
        input_10_val,
        input_11_val,
        input_12_val,
        input_13_val,
        input_14_val,
        input_15_val,
        input_16_val,
        input_17_val,
        input_18_val,
        input_19_val,
        input_20_val,
        input_21_val,
        input_22_val,
        input_23_val,
        input_24_val,
        input_25_val,
        input_26_val,
        input_27_val,
        input_28_val,
        input_29_val,
        input_30_val,
        input_31_val,
        output_0,
        output_0_ap_vld,
        output_1,
        output_1_ap_vld,
        output_2,
        output_2_ap_vld,
        output_3,
        output_3_ap_vld,
        output_4,
        output_4_ap_vld,
        output_5,
        output_5_ap_vld,
        output_6,
        output_6_ap_vld,
        output_7,
        output_7_ap_vld,
        output_8,
        output_8_ap_vld,
        output_9,
        output_9_ap_vld,
        output_10,
        output_10_ap_vld,
        output_11,
        output_11_ap_vld,
        output_12,
        output_12_ap_vld,
        output_13,
        output_13_ap_vld,
        output_14,
        output_14_ap_vld,
        output_15,
        output_15_ap_vld
);

parameter    ap_ST_fsm_state1 = 6'd1;
parameter    ap_ST_fsm_state2 = 6'd2;
parameter    ap_ST_fsm_state3 = 6'd4;
parameter    ap_ST_fsm_state4 = 6'd8;
parameter    ap_ST_fsm_state5 = 6'd16;
parameter    ap_ST_fsm_state6 = 6'd32;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [17:0] input_0_val;
input  [17:0] input_1_val;
input  [17:0] input_2_val;
input  [17:0] input_3_val;
input  [17:0] input_4_val;
input  [17:0] input_5_val;
input  [17:0] input_6_val;
input  [17:0] input_7_val;
input  [17:0] input_8_val;
input  [17:0] input_9_val;
input  [17:0] input_10_val;
input  [17:0] input_11_val;
input  [17:0] input_12_val;
input  [17:0] input_13_val;
input  [17:0] input_14_val;
input  [17:0] input_15_val;
input  [17:0] input_16_val;
input  [17:0] input_17_val;
input  [17:0] input_18_val;
input  [17:0] input_19_val;
input  [17:0] input_20_val;
input  [17:0] input_21_val;
input  [17:0] input_22_val;
input  [17:0] input_23_val;
input  [17:0] input_24_val;
input  [17:0] input_25_val;
input  [17:0] input_26_val;
input  [17:0] input_27_val;
input  [17:0] input_28_val;
input  [17:0] input_29_val;
input  [17:0] input_30_val;
input  [17:0] input_31_val;
output  [17:0] output_0;
output   output_0_ap_vld;
output  [17:0] output_1;
output   output_1_ap_vld;
output  [17:0] output_2;
output   output_2_ap_vld;
output  [17:0] output_3;
output   output_3_ap_vld;
output  [17:0] output_4;
output   output_4_ap_vld;
output  [17:0] output_5;
output   output_5_ap_vld;
output  [17:0] output_6;
output   output_6_ap_vld;
output  [17:0] output_7;
output   output_7_ap_vld;
output  [17:0] output_8;
output   output_8_ap_vld;
output  [17:0] output_9;
output   output_9_ap_vld;
output  [17:0] output_10;
output   output_10_ap_vld;
output  [17:0] output_11;
output   output_11_ap_vld;
output  [17:0] output_12;
output   output_12_ap_vld;
output  [17:0] output_13;
output   output_13_ap_vld;
output  [17:0] output_14;
output   output_14_ap_vld;
output  [17:0] output_15;
output   output_15_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_0_ap_vld;
reg output_1_ap_vld;
reg output_2_ap_vld;
reg output_3_ap_vld;
reg output_4_ap_vld;
reg output_5_ap_vld;
reg output_6_ap_vld;
reg output_7_ap_vld;
reg output_8_ap_vld;
reg output_9_ap_vld;
reg output_10_ap_vld;
reg output_11_ap_vld;
reg output_12_ap_vld;
reg output_13_ap_vld;
reg output_14_ap_vld;
reg output_15_ap_vld;

(* fsm_encoding = "none" *) reg   [5:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [3:0] fc1_bias_q_address0;
wire   [7:0] fc1_bias_q_q0;
wire   [4:0] add_ln103_fu_605_p2;
reg   [4:0] add_ln103_reg_1164;
wire    ap_CS_fsm_state2;
wire   [3:0] trunc_ln103_fu_616_p1;
reg   [3:0] trunc_ln103_reg_1169;
wire   [8:0] tmp_31_fu_620_p3;
reg   [8:0] tmp_31_reg_1173;
reg   [7:0] fc1_bias_q_load_reg_1183;
wire    ap_CS_fsm_state3;
wire   [48:0] add_ln109_5_fu_688_p2;
reg   [48:0] add_ln109_5_reg_1191;
wire    ap_CS_fsm_state4;
wire   [17:0] add_ln109_fu_737_p2;
reg   [17:0] add_ln109_reg_1196;
wire   [48:0] add_ln109_2_fu_762_p2;
reg   [48:0] add_ln109_2_reg_1201;
wire    ap_CS_fsm_state5;
reg   [0:0] tmp_65_reg_1206;
wire   [17:0] add_ln109_3_fu_806_p2;
reg   [17:0] add_ln109_3_reg_1212;
wire   [0:0] tmp_68_fu_812_p3;
reg   [0:0] tmp_68_reg_1217;
wire   [0:0] and_ln109_fu_826_p2;
reg   [0:0] and_ln109_reg_1223;
wire   [0:0] icmp_ln109_fu_842_p2;
reg   [0:0] icmp_ln109_reg_1230;
wire   [0:0] icmp_ln109_3_fu_858_p2;
reg   [0:0] icmp_ln109_3_reg_1235;
wire   [0:0] icmp_ln109_4_fu_864_p2;
reg   [0:0] icmp_ln109_4_reg_1242;
wire    grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_start;
wire    grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_done;
wire    grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_idle;
wire    grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_ready;
wire   [39:0] grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_acc_02_out;
wire    grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_acc_02_out_ap_vld;
reg    grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_start_reg;
wire   [0:0] icmp_ln103_fu_599_p2;
wire   [63:0] zext_ln103_fu_611_p1;
reg   [4:0] o_fu_226;
wire    ap_CS_fsm_state6;
wire   [17:0] select_ln109_6_fu_961_p3;
reg    fc1_bias_q_ce0_local;
wire  signed [39:0] p_shl_fu_632_p1;
wire  signed [39:0] tmp_fu_640_p1;
wire   [46:0] tmp_fu_640_p3;
wire   [48:0] p_shl_fu_632_p3;
wire  signed [48:0] sext_ln109_4_fu_648_p1;
wire  signed [39:0] tmp_62_fu_658_p1;
wire   [44:0] tmp_62_fu_658_p3;
wire   [48:0] sub_ln109_fu_652_p2;
wire  signed [48:0] sext_ln109_5_fu_666_p1;
wire  signed [39:0] tmp_63_fu_676_p1;
wire   [42:0] tmp_63_fu_676_p3;
wire   [48:0] add_ln109_4_fu_670_p2;
wire  signed [48:0] sext_ln109_6_fu_684_p1;
wire  signed [17:0] shl_ln_fu_694_p3;
wire   [12:0] mul_ln109_fu_705_p1;
wire   [30:0] mul_ln109_fu_705_p2;
wire   [16:0] trunc_ln_fu_711_p4;
wire   [0:0] tmp_64_fu_725_p3;
wire  signed [17:0] sext_ln109_7_fu_721_p1;
wire   [17:0] zext_ln109_fu_733_p1;
wire  signed [39:0] sext_ln109_fu_743_p0;
wire  signed [48:0] sext_ln109_fu_743_p1;
wire   [33:0] shl_ln109_1_fu_751_p3;
wire  signed [48:0] sext_ln109_3_fu_758_p1;
wire   [48:0] add_ln109_6_fu_746_p2;
wire   [0:0] tmp_66_fu_786_p3;
wire   [17:0] trunc_ln109_1_fu_776_p4;
wire   [17:0] zext_ln109_1_fu_802_p1;
wire   [0:0] tmp_67_fu_794_p3;
wire   [0:0] xor_ln109_fu_820_p2;
wire   [7:0] tmp_27_fu_832_p4;
wire   [8:0] tmp_28_fu_848_p4;
wire   [0:0] tmp_69_fu_870_p3;
wire   [0:0] xor_ln109_5_fu_882_p2;
wire   [0:0] and_ln109_6_fu_888_p2;
wire   [0:0] select_ln109_fu_877_p3;
wire   [0:0] xor_ln109_6_fu_903_p2;
wire   [0:0] or_ln109_fu_909_p2;
wire   [0:0] xor_ln109_7_fu_914_p2;
wire   [0:0] select_ln109_4_fu_893_p3;
wire   [0:0] and_ln109_7_fu_899_p2;
wire   [0:0] and_ln109_9_fu_925_p2;
wire   [0:0] or_ln109_3_fu_930_p2;
wire   [0:0] xor_ln109_8_fu_936_p2;
wire   [0:0] and_ln109_8_fu_919_p2;
wire   [0:0] and_ln109_10_fu_942_p2;
wire   [0:0] or_ln109_2_fu_955_p2;
wire   [17:0] select_ln109_5_fu_947_p3;
reg   [5:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ST_fsm_state6_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 6'd1;
#0 grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_start_reg = 1'b0;
#0 o_fu_226 = 5'd0;
end

phase2_rpm_cnn_dense_q_fc1_bias_q_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 16 ),
    .AddressWidth( 4 ))
fc1_bias_q_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(fc1_bias_q_address0),
    .ce0(fc1_bias_q_ce0_local),
    .q0(fc1_bias_q_q0)
);

phase2_rpm_cnn_dense_q_Pipeline_VITIS_LOOP_105_2 grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_start),
    .ap_done(grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_done),
    .ap_idle(grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_idle),
    .ap_ready(grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_ready),
    .input_0_val(input_0_val),
    .input_1_val(input_1_val),
    .input_2_val(input_2_val),
    .input_3_val(input_3_val),
    .input_4_val(input_4_val),
    .input_5_val(input_5_val),
    .input_6_val(input_6_val),
    .input_7_val(input_7_val),
    .input_8_val(input_8_val),
    .input_9_val(input_9_val),
    .input_10_val(input_10_val),
    .input_11_val(input_11_val),
    .input_12_val(input_12_val),
    .input_13_val(input_13_val),
    .input_14_val(input_14_val),
    .input_15_val(input_15_val),
    .input_16_val(input_16_val),
    .input_17_val(input_17_val),
    .input_18_val(input_18_val),
    .input_19_val(input_19_val),
    .input_20_val(input_20_val),
    .input_21_val(input_21_val),
    .input_22_val(input_22_val),
    .input_23_val(input_23_val),
    .input_24_val(input_24_val),
    .input_25_val(input_25_val),
    .input_26_val(input_26_val),
    .input_27_val(input_27_val),
    .input_28_val(input_28_val),
    .input_29_val(input_29_val),
    .input_30_val(input_30_val),
    .input_31_val(input_31_val),
    .tmp_31(tmp_31_reg_1173),
    .acc_02_out(grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_acc_02_out),
    .acc_02_out_ap_vld(grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_acc_02_out_ap_vld)
);

phase2_rpm_cnn_mul_18s_13ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 31 ))
mul_18s_13ns_31_1_1_U369(
    .din0(shl_ln_fu_694_p3),
    .din1(mul_ln109_fu_705_p1),
    .dout(mul_ln109_fu_705_p2)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln103_fu_599_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_start_reg <= 1'b1;
        end else if ((grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_ready == 1'b1)) begin
            grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
        o_fu_226 <= 5'd0;
    end else if ((1'b1 == ap_CS_fsm_state6)) begin
        o_fu_226 <= add_ln103_reg_1164;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        add_ln103_reg_1164 <= add_ln103_fu_605_p2;
        tmp_31_reg_1173[8 : 5] <= tmp_31_fu_620_p3[8 : 5];
        trunc_ln103_reg_1169 <= trunc_ln103_fu_616_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        add_ln109_2_reg_1201 <= add_ln109_2_fu_762_p2;
        add_ln109_3_reg_1212 <= add_ln109_3_fu_806_p2;
        and_ln109_reg_1223 <= and_ln109_fu_826_p2;
        icmp_ln109_3_reg_1235 <= icmp_ln109_3_fu_858_p2;
        icmp_ln109_4_reg_1242 <= icmp_ln109_4_fu_864_p2;
        icmp_ln109_reg_1230 <= icmp_ln109_fu_842_p2;
        tmp_65_reg_1206 <= add_ln109_2_fu_762_p2[32'd48];
        tmp_68_reg_1217 <= add_ln109_3_fu_806_p2[32'd17];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln109_5_reg_1191[48 : 3] <= add_ln109_5_fu_688_p2[48 : 3];
        add_ln109_reg_1196 <= add_ln109_fu_737_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        fc1_bias_q_load_reg_1183 <= fc1_bias_q_q0;
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

assign ap_ST_fsm_state6_blk = 1'b0;

always @ (*) begin
    if ((((icmp_ln103_fu_599_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2)) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln103_fu_599_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        fc1_bias_q_ce0_local = 1'b1;
    end else begin
        fc1_bias_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd0))) begin
        output_0_ap_vld = 1'b1;
    end else begin
        output_0_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd10))) begin
        output_10_ap_vld = 1'b1;
    end else begin
        output_10_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd11))) begin
        output_11_ap_vld = 1'b1;
    end else begin
        output_11_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd12))) begin
        output_12_ap_vld = 1'b1;
    end else begin
        output_12_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd13))) begin
        output_13_ap_vld = 1'b1;
    end else begin
        output_13_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd14))) begin
        output_14_ap_vld = 1'b1;
    end else begin
        output_14_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd15))) begin
        output_15_ap_vld = 1'b1;
    end else begin
        output_15_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd1))) begin
        output_1_ap_vld = 1'b1;
    end else begin
        output_1_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd2))) begin
        output_2_ap_vld = 1'b1;
    end else begin
        output_2_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd3))) begin
        output_3_ap_vld = 1'b1;
    end else begin
        output_3_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd4))) begin
        output_4_ap_vld = 1'b1;
    end else begin
        output_4_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd5))) begin
        output_5_ap_vld = 1'b1;
    end else begin
        output_5_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd6))) begin
        output_6_ap_vld = 1'b1;
    end else begin
        output_6_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd7))) begin
        output_7_ap_vld = 1'b1;
    end else begin
        output_7_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd8))) begin
        output_8_ap_vld = 1'b1;
    end else begin
        output_8_ap_vld = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state6) & (trunc_ln103_reg_1169 == 4'd9))) begin
        output_9_ap_vld = 1'b1;
    end else begin
        output_9_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln103_fu_599_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            ap_NS_fsm = ap_ST_fsm_state2;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln103_fu_605_p2 = (o_fu_226 + 5'd1);

assign add_ln109_2_fu_762_p2 = ($signed(sext_ln109_3_fu_758_p1) + $signed(add_ln109_6_fu_746_p2));

assign add_ln109_3_fu_806_p2 = (trunc_ln109_1_fu_776_p4 + zext_ln109_1_fu_802_p1);

assign add_ln109_4_fu_670_p2 = ($signed(sub_ln109_fu_652_p2) + $signed(sext_ln109_5_fu_666_p1));

assign add_ln109_5_fu_688_p2 = ($signed(add_ln109_4_fu_670_p2) + $signed(sext_ln109_6_fu_684_p1));

assign add_ln109_6_fu_746_p2 = ($signed(add_ln109_5_reg_1191) + $signed(sext_ln109_fu_743_p1));

assign add_ln109_fu_737_p2 = ($signed(sext_ln109_7_fu_721_p1) + $signed(zext_ln109_fu_733_p1));

assign and_ln109_10_fu_942_p2 = (xor_ln109_8_fu_936_p2 & tmp_65_reg_1206);

assign and_ln109_6_fu_888_p2 = (xor_ln109_5_fu_882_p2 & icmp_ln109_reg_1230);

assign and_ln109_7_fu_899_p2 = (icmp_ln109_3_reg_1235 & and_ln109_reg_1223);

assign and_ln109_8_fu_919_p2 = (xor_ln109_7_fu_914_p2 & or_ln109_fu_909_p2);

assign and_ln109_9_fu_925_p2 = (tmp_68_reg_1217 & select_ln109_4_fu_893_p3);

assign and_ln109_fu_826_p2 = (xor_ln109_fu_820_p2 & tmp_67_fu_794_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign fc1_bias_q_address0 = zext_ln103_fu_611_p1;

assign grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_start = grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_ap_start_reg;

assign icmp_ln103_fu_599_p2 = ((o_fu_226 == 5'd16) ? 1'b1 : 1'b0);

assign icmp_ln109_3_fu_858_p2 = ((tmp_28_fu_848_p4 == 9'd511) ? 1'b1 : 1'b0);

assign icmp_ln109_4_fu_864_p2 = ((tmp_28_fu_848_p4 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_842_p2 = ((tmp_27_fu_832_p4 == 8'd255) ? 1'b1 : 1'b0);

assign mul_ln109_fu_705_p1 = 31'd2197;

assign or_ln109_2_fu_955_p2 = (and_ln109_8_fu_919_p2 | and_ln109_10_fu_942_p2);

assign or_ln109_3_fu_930_p2 = (and_ln109_9_fu_925_p2 | and_ln109_7_fu_899_p2);

assign or_ln109_fu_909_p2 = (xor_ln109_6_fu_903_p2 | tmp_68_reg_1217);

assign output_0 = select_ln109_6_fu_961_p3;

assign output_1 = select_ln109_6_fu_961_p3;

assign output_10 = select_ln109_6_fu_961_p3;

assign output_11 = select_ln109_6_fu_961_p3;

assign output_12 = select_ln109_6_fu_961_p3;

assign output_13 = select_ln109_6_fu_961_p3;

assign output_14 = select_ln109_6_fu_961_p3;

assign output_15 = select_ln109_6_fu_961_p3;

assign output_2 = select_ln109_6_fu_961_p3;

assign output_3 = select_ln109_6_fu_961_p3;

assign output_4 = select_ln109_6_fu_961_p3;

assign output_5 = select_ln109_6_fu_961_p3;

assign output_6 = select_ln109_6_fu_961_p3;

assign output_7 = select_ln109_6_fu_961_p3;

assign output_8 = select_ln109_6_fu_961_p3;

assign output_9 = select_ln109_6_fu_961_p3;

assign p_shl_fu_632_p1 = grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_acc_02_out;

assign p_shl_fu_632_p3 = {{p_shl_fu_632_p1}, {9'd0}};

assign select_ln109_4_fu_893_p3 = ((and_ln109_reg_1223[0:0] == 1'b1) ? and_ln109_6_fu_888_p2 : icmp_ln109_3_reg_1235);

assign select_ln109_5_fu_947_p3 = ((and_ln109_8_fu_919_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln109_6_fu_961_p3 = ((or_ln109_2_fu_955_p2[0:0] == 1'b1) ? select_ln109_5_fu_947_p3 : add_ln109_3_reg_1212);

assign select_ln109_fu_877_p3 = ((and_ln109_reg_1223[0:0] == 1'b1) ? icmp_ln109_3_reg_1235 : icmp_ln109_4_reg_1242);

assign sext_ln109_3_fu_758_p1 = $signed(shl_ln109_1_fu_751_p3);

assign sext_ln109_4_fu_648_p1 = $signed(tmp_fu_640_p3);

assign sext_ln109_5_fu_666_p1 = $signed(tmp_62_fu_658_p3);

assign sext_ln109_6_fu_684_p1 = $signed(tmp_63_fu_676_p3);

assign sext_ln109_7_fu_721_p1 = $signed(trunc_ln_fu_711_p4);

assign sext_ln109_fu_743_p0 = grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_acc_02_out;

assign sext_ln109_fu_743_p1 = sext_ln109_fu_743_p0;

assign shl_ln109_1_fu_751_p3 = {{add_ln109_reg_1196}, {16'd0}};

assign shl_ln_fu_694_p3 = {{fc1_bias_q_load_reg_1183}, {10'd0}};

assign sub_ln109_fu_652_p2 = ($signed(p_shl_fu_632_p3) - $signed(sext_ln109_4_fu_648_p1));

assign tmp_27_fu_832_p4 = {{add_ln109_2_fu_762_p2[48:41]}};

assign tmp_28_fu_848_p4 = {{add_ln109_2_fu_762_p2[48:40]}};

assign tmp_31_fu_620_p3 = {{trunc_ln103_fu_616_p1}, {5'd0}};

assign tmp_62_fu_658_p1 = grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_acc_02_out;

assign tmp_62_fu_658_p3 = {{tmp_62_fu_658_p1}, {5'd0}};

assign tmp_63_fu_676_p1 = grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_acc_02_out;

assign tmp_63_fu_676_p3 = {{tmp_63_fu_676_p1}, {3'd0}};

assign tmp_64_fu_725_p3 = mul_ln109_fu_705_p2[32'd13];

assign tmp_66_fu_786_p3 = add_ln109_2_fu_762_p2[32'd21];

assign tmp_67_fu_794_p3 = add_ln109_2_fu_762_p2[32'd39];

assign tmp_68_fu_812_p3 = add_ln109_3_fu_806_p2[32'd17];

assign tmp_69_fu_870_p3 = add_ln109_2_reg_1201[32'd40];

assign tmp_fu_640_p1 = grp_dense_q_Pipeline_VITIS_LOOP_105_2_fu_551_acc_02_out;

assign tmp_fu_640_p3 = {{tmp_fu_640_p1}, {7'd0}};

assign trunc_ln103_fu_616_p1 = o_fu_226[3:0];

assign trunc_ln109_1_fu_776_p4 = {{add_ln109_2_fu_762_p2[39:22]}};

assign trunc_ln_fu_711_p4 = {{mul_ln109_fu_705_p2[30:14]}};

assign xor_ln109_5_fu_882_p2 = (tmp_69_fu_870_p3 ^ 1'd1);

assign xor_ln109_6_fu_903_p2 = (select_ln109_fu_877_p3 ^ 1'd1);

assign xor_ln109_7_fu_914_p2 = (tmp_65_reg_1206 ^ 1'd1);

assign xor_ln109_8_fu_936_p2 = (or_ln109_3_fu_930_p2 ^ 1'd1);

assign xor_ln109_fu_820_p2 = (tmp_68_fu_812_p3 ^ 1'd1);

assign zext_ln103_fu_611_p1 = o_fu_226;

assign zext_ln109_1_fu_802_p1 = tmp_66_fu_786_p3;

assign zext_ln109_fu_733_p1 = tmp_64_fu_725_p3;

always @ (posedge ap_clk) begin
    tmp_31_reg_1173[4:0] <= 5'b00000;
    add_ln109_5_reg_1191[2:0] <= 3'b000;
end

endmodule //phase2_rpm_cnn_dense_q
