// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module phase2_rpm_cnn_conv1d_same_q (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_r_address0,
        input_r_ce0,
        input_r_q0,
        input_r_address1,
        input_r_ce1,
        input_r_q1,
        output_r_address1,
        output_r_ce1,
        output_r_we1,
        output_r_d1
);

parameter    ap_ST_fsm_pp0_stage0 = 8'd1;
parameter    ap_ST_fsm_pp0_stage1 = 8'd2;
parameter    ap_ST_fsm_pp0_stage2 = 8'd4;
parameter    ap_ST_fsm_pp0_stage3 = 8'd8;
parameter    ap_ST_fsm_pp0_stage4 = 8'd16;
parameter    ap_ST_fsm_pp0_stage5 = 8'd32;
parameter    ap_ST_fsm_pp0_stage6 = 8'd64;
parameter    ap_ST_fsm_pp0_stage7 = 8'd128;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] input_r_address0;
output   input_r_ce0;
input  [17:0] input_r_q0;
output  [8:0] input_r_address1;
output   input_r_ce1;
input  [17:0] input_r_q1;
output  [11:0] output_r_address1;
output   output_r_ce1;
output   output_r_we1;
output  [17:0] output_r_d1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [7:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
reg    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_CS_fsm_pp0_stage7;
wire    ap_block_pp0_stage7_subdone;
reg    ap_enable_reg_pp0_iter0_reg;
reg   [0:0] icmp_ln41_reg_2331;
reg    ap_condition_exit_pp0_iter0_stage7;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [2:0] conv1_bias_q_address0;
wire   [7:0] conv1_bias_q_q0;
wire   [7:0] conv1_weight_q_q0;
reg   [7:0] reg_382;
wire    ap_CS_fsm_pp0_stage1;
wire    ap_block_pp0_stage1_11001;
wire    ap_CS_fsm_pp0_stage3;
wire    ap_block_pp0_stage3_11001;
wire    ap_CS_fsm_pp0_stage5;
wire    ap_block_pp0_stage5_11001;
wire    ap_block_pp0_stage7_11001;
reg   [7:0] reg_386;
wire    ap_CS_fsm_pp0_stage2;
wire    ap_block_pp0_stage2_11001;
wire    ap_CS_fsm_pp0_stage4;
wire    ap_block_pp0_stage4_11001;
wire    ap_CS_fsm_pp0_stage6;
wire    ap_block_pp0_stage6_11001;
reg   [17:0] reg_390;
reg   [17:0] reg_394;
wire  signed [47:0] grp_fu_370_p2;
reg  signed [47:0] reg_399;
wire   [0:0] icmp_ln41_fu_421_p2;
wire    ap_block_pp0_stage0_11001;
wire   [9:0] select_ln41_fu_445_p3;
reg   [9:0] select_ln41_reg_2335;
wire   [3:0] select_ln41_3_fu_459_p3;
reg   [3:0] select_ln41_3_reg_2346;
wire   [2:0] empty_fu_471_p1;
reg   [2:0] empty_reg_2351;
wire   [5:0] empty_64_fu_494_p1;
reg   [5:0] empty_64_reg_2356;
reg   [0:0] tmp_587_reg_2386;
reg   [0:0] tmp_588_reg_2391;
reg   [17:0] input_load_3_reg_2402;
reg   [0:0] tmp_594_reg_2412;
reg   [0:0] tmp_603_reg_2423;
wire  signed [31:0] acc_4_fu_682_p3;
reg  signed [31:0] acc_4_reg_2439;
reg   [17:0] input_load_4_reg_2445;
reg   [0:0] tmp_608_reg_2450;
reg   [0:0] tmp_613_reg_2461;
reg   [0:0] tmp_613_reg_2461_pp0_iter1_reg;
wire   [11:0] add_ln55_6_fu_725_p2;
reg   [11:0] add_ln55_6_reg_2472;
reg   [11:0] add_ln55_6_reg_2472_pp0_iter1_reg;
reg   [0:0] tmp_591_reg_2482;
reg   [17:0] input_load_6_reg_2487;
wire   [39:0] acc_265_fu_840_p2;
reg   [39:0] acc_265_reg_2497;
wire   [39:0] select_ln51_fu_932_p3;
reg   [39:0] select_ln51_reg_2502;
wire   [0:0] and_ln51_321_fu_940_p2;
reg   [0:0] and_ln51_321_reg_2507;
reg   [0:0] tmp_596_reg_2512;
wire   [39:0] acc_266_fu_1004_p9;
reg   [39:0] acc_266_reg_2522;
reg   [0:0] tmp_595_reg_2527;
reg   [0:0] tmp_597_reg_2534;
wire   [39:0] acc_268_fu_1073_p2;
reg   [39:0] acc_268_reg_2540;
reg   [0:0] tmp_598_reg_2545;
reg   [0:0] tmp_600_reg_2553;
reg   [0:0] tmp_599_reg_2558;
reg   [39:0] acc_270_reg_2565;
reg   [0:0] tmp_601_reg_2570;
reg   [0:0] tmp_605_reg_2576;
wire   [39:0] acc_272_fu_1386_p3;
reg   [39:0] acc_272_reg_2586;
reg  signed [47:0] mul_ln51_91_reg_2592;
reg   [0:0] tmp_610_reg_2597;
reg   [7:0] conv1_bias_q_load_reg_2602;
wire   [39:0] acc_274_fu_1475_p2;
reg   [39:0] acc_274_reg_2607;
wire   [39:0] select_ln51_112_fu_1567_p3;
reg   [39:0] select_ln51_112_reg_2612;
wire   [0:0] and_ln51_332_fu_1575_p2;
reg   [0:0] and_ln51_332_reg_2617;
reg   [0:0] tmp_615_reg_2622;
reg   [16:0] tmp_70_reg_2627;
reg   [0:0] tmp_reg_2632;
wire   [39:0] acc_275_fu_1647_p9;
reg   [39:0] acc_275_reg_2637;
reg   [0:0] tmp_609_reg_2642;
reg   [0:0] tmp_611_reg_2649;
wire   [39:0] acc_277_fu_1714_p2;
reg   [39:0] acc_277_reg_2655;
reg   [0:0] tmp_612_reg_2660;
wire   [39:0] acc_278_fu_1823_p9;
reg   [39:0] acc_278_reg_2668;
reg   [0:0] tmp_614_reg_2673;
reg   [39:0] acc_279_reg_2680;
reg   [0:0] tmp_616_reg_2685;
wire  signed [39:0] acc_281_fu_2004_p9;
reg  signed [39:0] acc_281_reg_2691;
wire   [17:0] add_i_i_i_i74_fu_2029_p2;
reg   [17:0] add_i_i_i_i74_reg_2699;
wire   [48:0] sub_ln55_fu_2074_p2;
reg   [48:0] sub_ln55_reg_2704;
wire   [48:0] add_ln55_fu_2099_p2;
reg   [48:0] add_ln55_reg_2709;
reg   [0:0] tmp_621_reg_2714;
wire   [17:0] add_ln55_5_fu_2143_p2;
reg   [17:0] add_ln55_5_reg_2720;
wire   [0:0] tmp_624_fu_2149_p3;
reg   [0:0] tmp_624_reg_2725;
wire   [0:0] and_ln55_fu_2163_p2;
reg   [0:0] and_ln55_reg_2731;
wire   [0:0] icmp_ln55_fu_2179_p2;
reg   [0:0] icmp_ln55_reg_2738;
wire   [0:0] icmp_ln55_5_fu_2195_p2;
reg   [0:0] icmp_ln55_5_reg_2743;
wire   [0:0] icmp_ln55_6_fu_2201_p2;
reg   [0:0] icmp_ln55_6_reg_2750;
wire   [63:0] p_cast34_fu_489_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln42_fu_498_p1;
wire   [63:0] p_cast35_fu_518_p1;
wire    ap_block_pp0_stage1;
wire   [63:0] zext_ln48_fu_528_p1;
wire   [63:0] zext_ln48_2_fu_546_p1;
wire   [63:0] p_cast36_fu_564_p1;
wire    ap_block_pp0_stage2;
wire   [63:0] zext_ln48_3_fu_574_p1;
wire   [63:0] zext_ln48_4_fu_592_p1;
wire   [63:0] p_cast37_fu_622_p1;
wire    ap_block_pp0_stage3;
wire   [63:0] zext_ln48_5_fu_694_p1;
wire   [63:0] zext_ln48_6_fu_712_p1;
wire   [63:0] p_cast38_fu_736_p1;
wire    ap_block_pp0_stage4;
wire   [63:0] p_cast39_fu_772_p1;
wire    ap_block_pp0_stage5;
wire   [63:0] p_cast40_fu_990_p1;
wire    ap_block_pp0_stage6;
wire   [63:0] zext_ln41_fu_1285_p1;
wire   [63:0] zext_ln55_3_fu_2306_p1;
wire    ap_block_pp0_stage7;
reg   [9:0] i_fu_198;
wire   [9:0] add_ln47_7_fu_587_p2;
wire    ap_loop_init;
reg   [9:0] ap_sig_allocacmp_i_load;
reg   [3:0] oc_fu_202;
reg   [3:0] ap_sig_allocacmp_oc_load;
reg   [12:0] indvar_flatten_fu_206;
wire   [12:0] add_ln41_fu_427_p2;
reg   [12:0] ap_sig_allocacmp_indvar_flatten_load;
reg    conv1_weight_q_ce0_local;
reg   [5:0] conv1_weight_q_address0_local;
reg    input_r_ce0_local;
reg   [8:0] input_r_address0_local;
reg    input_r_ce1_local;
reg   [8:0] input_r_address1_local;
reg    conv1_bias_q_ce0_local;
reg    output_r_we1_local;
wire   [17:0] select_ln55_9_fu_2298_p3;
reg    output_r_ce1_local;
reg  signed [23:0] grp_fu_370_p0;
wire  signed [47:0] sext_ln51_345_fu_757_p1;
wire  signed [47:0] sext_ln51_350_fu_962_p1;
wire  signed [47:0] sext_ln51_354_fu_1094_p1;
wire  signed [47:0] sext_ln51_357_fu_1275_p1;
wire  signed [47:0] sext_ln51_361_fu_1410_p1;
wire  signed [47:0] sext_ln51_365_fu_1596_p1;
reg  signed [23:0] grp_fu_370_p1;
wire  signed [47:0] sext_ln51_346_fu_762_p1;
wire  signed [47:0] sext_ln51_351_fu_967_p1;
wire  signed [47:0] shl_i_i_i241_3_cast_fu_980_p1;
wire  signed [47:0] sext_ln51_358_fu_1280_p1;
wire  signed [47:0] sext_ln51_362_fu_1415_p1;
wire  signed [47:0] sext_ln51_366_fu_1601_p1;
wire   [0:0] icmp_ln42_fu_439_p2;
wire   [3:0] add_ln41_3_fu_453_p2;
wire   [6:0] p_shl1_fu_475_p3;
wire   [6:0] zext_ln41_1_fu_467_p1;
wire   [6:0] empty_63_fu_483_p2;
wire   [5:0] empty_65_fu_513_p2;
wire   [9:0] add_ln47_fu_523_p2;
wire   [9:0] add_ln47_5_fu_541_p2;
wire   [5:0] empty_66_fu_559_p2;
wire   [9:0] add_ln47_6_fu_569_p2;
wire   [5:0] empty_67_fu_617_p2;
wire  signed [23:0] shl_ln_fu_630_p3;
wire  signed [23:0] shl_ln51_s_fu_638_p3;
wire   [47:0] mul_ln51_fu_366_p2;
wire   [30:0] tmp_s_fu_664_p4;
wire   [0:0] tmp_586_fu_656_p3;
wire   [31:0] acc_fu_674_p3;
wire   [9:0] add_ln47_8_fu_689_p2;
wire   [9:0] add_ln47_9_fu_707_p2;
wire   [11:0] zext_ln42_11_fu_627_p1;
wire   [11:0] tmp_69_fu_610_p3;
wire   [5:0] empty_68_fu_731_p2;
wire   [23:0] shl_ln51_235_fu_741_p3;
wire   [23:0] shl_ln51_236_fu_749_p3;
wire   [5:0] empty_69_fu_767_p2;
wire   [47:0] shl_ln51_237_fu_782_p3;
wire  signed [48:0] sext_ln51_347_fu_789_p1;
wire  signed [48:0] sext_ln51_348_fu_793_p1;
wire  signed [48:0] add_ln51_fu_797_p2;
wire  signed [56:0] sext_ln51_349_fu_803_p1;
wire   [32:0] tmp_590_fu_815_p4;
wire  signed [39:0] acc_264_fu_825_p1;
wire   [39:0] zext_ln51_fu_837_p1;
wire   [0:0] tmp_593_fu_846_p3;
wire   [0:0] tmp_592_fu_829_p3;
wire   [0:0] xor_ln51_fu_854_p2;
wire   [0:0] xor_ln51_515_fu_866_p2;
wire   [0:0] tmp_589_fu_807_p3;
wire   [0:0] or_ln51_fu_872_p2;
wire   [0:0] xor_ln51_516_fu_878_p2;
wire   [0:0] xor_ln51_518_fu_890_p2;
wire   [0:0] or_ln51_176_fu_896_p2;
wire   [0:0] xor_ln51_517_fu_884_p2;
wire   [0:0] and_ln51_fu_860_p2;
wire   [0:0] or_ln51_265_fu_908_p2;
wire   [0:0] xor_ln51_519_fu_914_p2;
wire   [0:0] and_ln51_320_fu_920_p2;
wire   [0:0] and_ln51_319_fu_902_p2;
wire   [0:0] or_ln51_177_fu_926_p2;
wire   [0:0] xor_ln48_fu_777_p2;
wire   [23:0] shl_ln51_238_fu_946_p3;
wire   [23:0] shl_ln51_239_fu_954_p3;
wire   [23:0] shl_i_i_i241_3_fu_972_p3;
wire   [5:0] empty_70_fu_985_p2;
wire  signed [39:0] acc_266_fu_1004_p4;
wire   [39:0] acc_266_fu_1004_p7;
wire   [1:0] acc_266_fu_1004_p8;
wire   [55:0] shl_ln51_240_fu_1022_p3;
wire  signed [56:0] sext_ln51_352_fu_1030_p1;
wire  signed [56:0] sext_ln51_353_fu_1034_p1;
wire   [56:0] add_ln51_184_fu_1038_p2;
wire   [39:0] acc_267_fu_1052_p4;
wire   [39:0] zext_ln51_85_fu_1070_p1;
wire   [23:0] shl_ln51_241_fu_1087_p3;
wire   [0:0] xor_ln51_520_fu_1104_p2;
wire   [0:0] xor_ln51_521_fu_1114_p2;
wire   [0:0] or_ln51_266_fu_1119_p2;
wire   [0:0] xor_ln51_522_fu_1124_p2;
wire   [0:0] xor_ln51_524_fu_1134_p2;
wire   [0:0] or_ln51_178_fu_1140_p2;
wire   [0:0] xor_ln51_523_fu_1129_p2;
wire   [0:0] and_ln51_322_fu_1109_p2;
wire   [0:0] or_ln51_267_fu_1151_p2;
wire   [0:0] xor_ln51_525_fu_1156_p2;
wire   [0:0] and_ln51_324_fu_1162_p2;
wire   [0:0] and_ln51_323_fu_1145_p2;
wire   [0:0] or_ln51_179_fu_1167_p2;
wire   [0:0] xor_ln48_5_fu_1099_p2;
wire   [0:0] and_ln51_325_fu_1181_p2;
wire   [39:0] acc_269_fu_1194_p2;
wire   [39:0] acc_269_fu_1194_p7;
wire   [1:0] acc_269_fu_1194_p8;
wire   [39:0] acc_269_fu_1194_p9;
wire   [55:0] shl_ln51_242_fu_1212_p3;
wire  signed [56:0] sext_ln51_355_fu_1220_p1;
wire  signed [56:0] sext_ln51_356_fu_1224_p1;
wire   [56:0] add_ln51_186_fu_1228_p2;
wire   [23:0] shl_ln51_243_fu_1260_p3;
wire   [23:0] shl_ln51_244_fu_1267_p3;
wire   [39:0] zext_ln51_86_fu_1289_p1;
wire   [39:0] acc_271_fu_1292_p2;
wire   [0:0] tmp_602_fu_1297_p3;
wire   [0:0] xor_ln51_526_fu_1305_p2;
wire   [0:0] xor_ln51_527_fu_1316_p2;
wire   [0:0] or_ln51_268_fu_1321_p2;
wire   [0:0] xor_ln51_528_fu_1327_p2;
wire   [0:0] xor_ln51_530_fu_1337_p2;
wire   [0:0] or_ln51_180_fu_1343_p2;
wire   [0:0] xor_ln51_529_fu_1332_p2;
wire   [0:0] and_ln51_326_fu_1311_p2;
wire   [0:0] or_ln51_269_fu_1355_p2;
wire   [0:0] xor_ln51_531_fu_1361_p2;
wire   [0:0] and_ln51_327_fu_1349_p2;
wire   [0:0] and_ln51_328_fu_1367_p2;
wire   [0:0] or_ln51_181_fu_1380_p2;
wire   [39:0] select_ln51_110_fu_1372_p3;
wire   [23:0] shl_ln51_246_fu_1394_p3;
wire   [23:0] shl_ln51_247_fu_1402_p3;
wire   [55:0] shl_ln51_245_fu_1425_p3;
wire  signed [56:0] sext_ln51_359_fu_1432_p1;
wire  signed [56:0] sext_ln51_360_fu_1436_p1;
wire   [56:0] add_ln51_188_fu_1440_p2;
wire   [39:0] acc_273_fu_1454_p4;
wire   [39:0] zext_ln51_87_fu_1472_p1;
wire   [0:0] tmp_607_fu_1481_p3;
wire   [0:0] tmp_606_fu_1464_p3;
wire   [0:0] xor_ln51_532_fu_1489_p2;
wire   [0:0] xor_ln51_533_fu_1501_p2;
wire   [0:0] tmp_604_fu_1446_p3;
wire   [0:0] or_ln51_270_fu_1507_p2;
wire   [0:0] xor_ln51_534_fu_1513_p2;
wire   [0:0] xor_ln51_536_fu_1525_p2;
wire   [0:0] or_ln51_182_fu_1531_p2;
wire   [0:0] xor_ln51_535_fu_1519_p2;
wire   [0:0] and_ln51_329_fu_1495_p2;
wire   [0:0] or_ln51_271_fu_1543_p2;
wire   [0:0] xor_ln51_537_fu_1549_p2;
wire   [0:0] and_ln51_331_fu_1555_p2;
wire   [0:0] and_ln51_330_fu_1537_p2;
wire   [0:0] or_ln51_183_fu_1561_p2;
wire   [0:0] xor_ln48_6_fu_1420_p2;
wire   [23:0] shl_ln51_249_fu_1581_p3;
wire   [23:0] shl_ln51_250_fu_1588_p3;
wire  signed [17:0] shl_i_i_i_fu_1606_p3;
wire   [12:0] mul_i_fu_1617_p1;
wire   [30:0] mul_i_fu_1617_p2;
wire   [39:0] acc_275_fu_1647_p7;
wire   [1:0] acc_275_fu_1647_p8;
wire   [55:0] shl_ln51_248_fu_1664_p3;
wire  signed [56:0] sext_ln51_363_fu_1672_p1;
wire  signed [56:0] sext_ln51_364_fu_1676_p1;
wire   [56:0] add_ln51_190_fu_1679_p2;
wire   [39:0] acc_276_fu_1693_p4;
wire   [39:0] zext_ln51_88_fu_1711_p1;
wire   [0:0] xor_ln51_538_fu_1733_p2;
wire   [0:0] xor_ln51_539_fu_1743_p2;
wire   [0:0] or_ln51_272_fu_1748_p2;
wire   [0:0] xor_ln51_540_fu_1753_p2;
wire   [0:0] xor_ln51_542_fu_1763_p2;
wire   [0:0] or_ln51_184_fu_1769_p2;
wire   [0:0] xor_ln51_541_fu_1758_p2;
wire   [0:0] and_ln51_333_fu_1738_p2;
wire   [0:0] or_ln51_273_fu_1780_p2;
wire   [0:0] xor_ln51_543_fu_1785_p2;
wire   [0:0] and_ln51_335_fu_1791_p2;
wire   [0:0] and_ln51_334_fu_1774_p2;
wire   [0:0] or_ln51_185_fu_1796_p2;
wire   [0:0] xor_ln48_7_fu_1728_p2;
wire   [0:0] and_ln51_336_fu_1810_p2;
wire   [39:0] acc_278_fu_1823_p2;
wire   [39:0] acc_278_fu_1823_p7;
wire   [1:0] acc_278_fu_1823_p8;
wire   [55:0] shl_ln51_251_fu_1841_p3;
wire  signed [56:0] sext_ln51_367_fu_1849_p1;
wire  signed [56:0] sext_ln51_368_fu_1853_p1;
wire   [56:0] add_ln51_192_fu_1857_p2;
wire   [39:0] zext_ln51_89_fu_1894_p1;
wire   [39:0] acc_280_fu_1897_p2;
wire   [0:0] tmp_617_fu_1902_p3;
wire   [0:0] xor_ln51_544_fu_1910_p2;
wire   [0:0] xor_ln51_545_fu_1921_p2;
wire   [0:0] or_ln51_274_fu_1926_p2;
wire   [0:0] xor_ln51_546_fu_1932_p2;
wire   [0:0] xor_ln51_548_fu_1942_p2;
wire   [0:0] or_ln51_186_fu_1948_p2;
wire   [0:0] xor_ln51_547_fu_1937_p2;
wire   [0:0] and_ln51_337_fu_1916_p2;
wire   [0:0] or_ln51_275_fu_1960_p2;
wire   [0:0] xor_ln51_549_fu_1966_p2;
wire   [0:0] and_ln51_339_fu_1972_p2;
wire   [0:0] and_ln51_338_fu_1954_p2;
wire   [0:0] or_ln51_187_fu_1977_p2;
wire   [0:0] xor_ln48_8_fu_1889_p2;
wire   [0:0] and_ln51_340_fu_1991_p2;
wire   [39:0] acc_281_fu_2004_p2;
wire   [39:0] acc_281_fu_2004_p7;
wire   [1:0] acc_281_fu_2004_p8;
wire  signed [17:0] sext_ln55_fu_2023_p1;
wire   [17:0] p_cast_fu_2026_p1;
wire   [47:0] tmp_618_fu_2035_p3;
wire   [44:0] tmp_619_fu_2046_p3;
wire  signed [48:0] sext_ln55_6_fu_2042_p1;
wire  signed [48:0] sext_ln55_7_fu_2053_p1;
wire   [41:0] tmp_620_fu_2063_p3;
wire   [48:0] add_ln55_7_fu_2057_p2;
wire  signed [48:0] sext_ln55_8_fu_2070_p1;
wire   [33:0] shl_i_i16_i_fu_2080_p3;
wire  signed [48:0] sext_ln55_3_fu_2091_p1;
wire  signed [48:0] shl_i_i16_i_cast66_fu_2087_p1;
wire   [48:0] add_ln55_8_fu_2094_p2;
wire   [0:0] tmp_622_fu_2123_p3;
wire   [17:0] trunc_ln_fu_2113_p4;
wire   [17:0] zext_ln55_fu_2139_p1;
wire   [0:0] tmp_623_fu_2131_p3;
wire   [0:0] xor_ln55_fu_2157_p2;
wire   [7:0] tmp_270_fu_2169_p4;
wire   [8:0] tmp_271_fu_2185_p4;
wire   [0:0] tmp_625_fu_2207_p3;
wire   [0:0] xor_ln55_9_fu_2219_p2;
wire   [0:0] and_ln55_11_fu_2225_p2;
wire   [0:0] select_ln55_fu_2214_p3;
wire   [0:0] xor_ln55_10_fu_2240_p2;
wire   [0:0] or_ln55_fu_2246_p2;
wire   [0:0] xor_ln55_11_fu_2251_p2;
wire   [0:0] select_ln55_7_fu_2230_p3;
wire   [0:0] and_ln55_12_fu_2236_p2;
wire   [0:0] and_ln55_14_fu_2262_p2;
wire   [0:0] or_ln55_4_fu_2267_p2;
wire   [0:0] xor_ln55_12_fu_2273_p2;
wire   [0:0] and_ln55_13_fu_2256_p2;
wire   [0:0] and_ln55_15_fu_2279_p2;
wire   [0:0] or_ln55_3_fu_2292_p2;
wire   [17:0] select_ln55_8_fu_2284_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [7:0] ap_NS_fsm;
wire    ap_block_pp0_stage0_subdone;
reg    ap_idle_pp0_1to1;
wire    ap_block_pp0_stage1_subdone;
wire    ap_block_pp0_stage2_subdone;
wire    ap_block_pp0_stage3_subdone;
wire    ap_block_pp0_stage4_subdone;
wire    ap_block_pp0_stage5_subdone;
wire    ap_block_pp0_stage6_subdone;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire  signed [1:0] acc_266_fu_1004_p1;
wire   [1:0] acc_266_fu_1004_p3;
wire   [1:0] acc_266_fu_1004_p5;
wire  signed [1:0] acc_269_fu_1194_p1;
wire   [1:0] acc_269_fu_1194_p3;
wire   [1:0] acc_269_fu_1194_p5;
wire  signed [1:0] acc_275_fu_1647_p1;
wire   [1:0] acc_275_fu_1647_p3;
wire   [1:0] acc_275_fu_1647_p5;
wire  signed [1:0] acc_278_fu_1823_p1;
wire   [1:0] acc_278_fu_1823_p3;
wire   [1:0] acc_278_fu_1823_p5;
wire  signed [1:0] acc_281_fu_2004_p1;
wire   [1:0] acc_281_fu_2004_p3;
wire   [1:0] acc_281_fu_2004_p5;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 8'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter0_reg = 1'b0;
#0 i_fu_198 = 10'd0;
#0 oc_fu_202 = 4'd0;
#0 indvar_flatten_fu_206 = 13'd0;
#0 ap_done_reg = 1'b0;
end

phase2_rpm_cnn_conv1d_same_q_conv1_bias_q_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 8 ),
    .AddressWidth( 3 ))
conv1_bias_q_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_bias_q_address0),
    .ce0(conv1_bias_q_ce0_local),
    .q0(conv1_bias_q_q0)
);

phase2_rpm_cnn_conv1d_same_q_conv1_weight_q_ROM_AUTO_1R #(
    .DataWidth( 8 ),
    .AddressRange( 56 ),
    .AddressWidth( 6 ))
conv1_weight_q_U(
    .clk(ap_clk),
    .reset(ap_rst),
    .address0(conv1_weight_q_address0_local),
    .ce0(conv1_weight_q_ce0_local),
    .q0(conv1_weight_q_q0)
);

phase2_rpm_cnn_mul_24s_24s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 48 ))
mul_24s_24s_48_1_1_U39(
    .din0(shl_ln_fu_630_p3),
    .din1(shl_ln51_s_fu_638_p3),
    .dout(mul_ln51_fu_366_p2)
);

phase2_rpm_cnn_mul_24s_24s_48_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 24 ),
    .din1_WIDTH( 24 ),
    .dout_WIDTH( 48 ))
mul_24s_24s_48_1_1_U40(
    .din0(grp_fu_370_p0),
    .din1(grp_fu_370_p1),
    .dout(grp_fu_370_p2)
);

(* dissolve_hierarchy = "yes" *) phase2_rpm_cnn_sparsemux_7_2_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 40 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 40 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 40 ),
    .def_WIDTH( 40 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 40 ))
sparsemux_7_2_40_1_1_U41(
    .din0(select_ln51_reg_2502),
    .din1(acc_266_fu_1004_p4),
    .din2(acc_265_reg_2497),
    .def(acc_266_fu_1004_p7),
    .sel(acc_266_fu_1004_p8),
    .dout(acc_266_fu_1004_p9)
);

(* dissolve_hierarchy = "yes" *) phase2_rpm_cnn_sparsemux_7_2_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 40 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 40 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 40 ),
    .def_WIDTH( 40 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 40 ))
sparsemux_7_2_40_1_1_U42(
    .din0(acc_269_fu_1194_p2),
    .din1(acc_266_reg_2522),
    .din2(acc_268_reg_2540),
    .def(acc_269_fu_1194_p7),
    .sel(acc_269_fu_1194_p8),
    .dout(acc_269_fu_1194_p9)
);

phase2_rpm_cnn_mul_18s_13ns_31_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 18 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 31 ))
mul_18s_13ns_31_1_1_U43(
    .din0(shl_i_i_i_fu_1606_p3),
    .din1(mul_i_fu_1617_p1),
    .dout(mul_i_fu_1617_p2)
);

(* dissolve_hierarchy = "yes" *) phase2_rpm_cnn_sparsemux_7_2_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 40 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 40 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 40 ),
    .def_WIDTH( 40 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 40 ))
sparsemux_7_2_40_1_1_U44(
    .din0(select_ln51_112_reg_2612),
    .din1(acc_272_reg_2586),
    .din2(acc_274_reg_2607),
    .def(acc_275_fu_1647_p7),
    .sel(acc_275_fu_1647_p8),
    .dout(acc_275_fu_1647_p9)
);

(* dissolve_hierarchy = "yes" *) phase2_rpm_cnn_sparsemux_7_2_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 40 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 40 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 40 ),
    .def_WIDTH( 40 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 40 ))
sparsemux_7_2_40_1_1_U45(
    .din0(acc_278_fu_1823_p2),
    .din1(acc_275_reg_2637),
    .din2(acc_277_reg_2655),
    .def(acc_278_fu_1823_p7),
    .sel(acc_278_fu_1823_p8),
    .dout(acc_278_fu_1823_p9)
);

(* dissolve_hierarchy = "yes" *) phase2_rpm_cnn_sparsemux_7_2_40_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .CASE0( 2'h2 ),
    .din0_WIDTH( 40 ),
    .CASE1( 2'h1 ),
    .din1_WIDTH( 40 ),
    .CASE2( 2'h0 ),
    .din2_WIDTH( 40 ),
    .def_WIDTH( 40 ),
    .sel_WIDTH( 2 ),
    .dout_WIDTH( 40 ))
sparsemux_7_2_40_1_1_U46(
    .din0(acc_281_fu_2004_p2),
    .din1(acc_278_reg_2668),
    .din2(acc_280_fu_1897_p2),
    .def(acc_281_fu_2004_p7),
    .sel(acc_281_fu_2004_p8),
    .dout(acc_281_fu_2004_p9)
);

phase2_rpm_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage7),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter0_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
            ap_enable_reg_pp0_iter0_reg <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage7)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
            ap_enable_reg_pp0_iter1 <= ap_enable_reg_pp0_iter0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        i_fu_198 <= 10'd0;
    end else if (((icmp_ln41_reg_2331 == 1'd0) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        i_fu_198 <= add_ln47_7_fu_587_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_421_p2 == 1'd0))) begin
            indvar_flatten_fu_206 <= add_ln41_fu_427_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_206 <= 13'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((ap_enable_reg_pp0_iter0 == 1'b1) & (icmp_ln41_fu_421_p2 == 1'd0))) begin
            oc_fu_202 <= select_ln41_3_fu_459_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            oc_fu_202 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
            reg_394 <= input_r_q1;
        end else if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            reg_394 <= input_r_q0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        acc_265_reg_2497 <= acc_265_fu_840_p2;
        add_i_i_i_i74_reg_2699 <= add_i_i_i_i74_fu_2029_p2;
        and_ln51_321_reg_2507 <= and_ln51_321_fu_940_p2;
        select_ln51_reg_2502 <= select_ln51_fu_932_p3;
        sub_ln55_reg_2704[48 : 2] <= sub_ln55_fu_2074_p2[48 : 2];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        acc_266_reg_2522 <= acc_266_fu_1004_p9;
        acc_268_reg_2540 <= acc_268_fu_1073_p2;
        add_ln55_5_reg_2720 <= add_ln55_5_fu_2143_p2;
        add_ln55_reg_2709 <= add_ln55_fu_2099_p2;
        and_ln55_reg_2731 <= and_ln55_fu_2163_p2;
        icmp_ln55_5_reg_2743 <= icmp_ln55_5_fu_2195_p2;
        icmp_ln55_6_reg_2750 <= icmp_ln55_6_fu_2201_p2;
        icmp_ln55_reg_2738 <= icmp_ln55_fu_2179_p2;
        tmp_595_reg_2527 <= add_ln51_184_fu_1038_p2[32'd56];
        tmp_597_reg_2534 <= add_ln51_184_fu_1038_p2[32'd55];
        tmp_598_reg_2545 <= acc_268_fu_1073_p2[32'd39];
        tmp_621_reg_2714 <= add_ln55_fu_2099_p2[32'd48];
        tmp_624_reg_2725 <= add_ln55_5_fu_2143_p2[32'd17];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        acc_270_reg_2565 <= {{add_ln51_186_fu_1228_p2[55:16]}};
        tmp_599_reg_2558 <= add_ln51_186_fu_1228_p2[32'd56];
        tmp_601_reg_2570 <= add_ln51_186_fu_1228_p2[32'd55];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        acc_272_reg_2586 <= acc_272_fu_1386_p3;
        empty_64_reg_2356 <= empty_64_fu_494_p1;
        empty_reg_2351 <= empty_fu_471_p1;
        icmp_ln41_reg_2331 <= icmp_ln41_fu_421_p2;
        select_ln41_3_reg_2346 <= select_ln41_3_fu_459_p3;
        select_ln41_reg_2335 <= select_ln41_fu_445_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        acc_274_reg_2607 <= acc_274_fu_1475_p2;
        and_ln51_332_reg_2617 <= and_ln51_332_fu_1575_p2;
        conv1_bias_q_load_reg_2602 <= conv1_bias_q_q0;
        select_ln51_112_reg_2612 <= select_ln51_112_fu_1567_p3;
        tmp_587_reg_2386 <= add_ln47_fu_523_p2[32'd9];
        tmp_588_reg_2391 <= add_ln47_5_fu_541_p2[32'd9];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        acc_275_reg_2637 <= acc_275_fu_1647_p9;
        acc_277_reg_2655 <= acc_277_fu_1714_p2;
        tmp_594_reg_2412 <= add_ln47_6_fu_569_p2[32'd9];
        tmp_603_reg_2423 <= add_ln47_7_fu_587_p2[32'd9];
        tmp_609_reg_2642 <= add_ln51_190_fu_1679_p2[32'd56];
        tmp_611_reg_2649 <= add_ln51_190_fu_1679_p2[32'd55];
        tmp_612_reg_2660 <= acc_277_fu_1714_p2[32'd39];
        tmp_70_reg_2627 <= {{mul_i_fu_1617_p2[30:14]}};
        tmp_reg_2632 <= mul_i_fu_1617_p2[32'd13];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        acc_278_reg_2668 <= acc_278_fu_1823_p9;
        acc_279_reg_2680 <= {{add_ln51_192_fu_1857_p2[55:16]}};
        acc_4_reg_2439 <= acc_4_fu_682_p3;
        add_ln55_6_reg_2472 <= add_ln55_6_fu_725_p2;
        add_ln55_6_reg_2472_pp0_iter1_reg <= add_ln55_6_reg_2472;
        tmp_608_reg_2450 <= add_ln47_8_fu_689_p2[32'd9];
        tmp_613_reg_2461 <= add_ln47_9_fu_707_p2[32'd9];
        tmp_613_reg_2461_pp0_iter1_reg <= tmp_613_reg_2461;
        tmp_614_reg_2673 <= add_ln51_192_fu_1857_p2[32'd56];
        tmp_616_reg_2685 <= add_ln51_192_fu_1857_p2[32'd55];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        acc_281_reg_2691 <= acc_281_fu_2004_p9;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_load_3_reg_2402 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        input_load_4_reg_2445 <= input_r_q0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        input_load_6_reg_2487 <= input_r_q0;
        tmp_591_reg_2482 <= grp_fu_370_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        mul_ln51_91_reg_2592 <= grp_fu_370_p2;
        tmp_610_reg_2597 <= grp_fu_370_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_382 <= conv1_weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)))) begin
        reg_386 <= conv1_weight_q_q0;
    end
end

always @ (posedge ap_clk) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        reg_390 <= input_r_q1;
    end
end

always @ (posedge ap_clk) begin
    if ((((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)))) begin
        reg_399 <= grp_fu_370_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        tmp_596_reg_2512 <= grp_fu_370_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        tmp_600_reg_2553 <= grp_fu_370_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_11001) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        tmp_605_reg_2576 <= grp_fu_370_p2[32'd15];
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage1_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        tmp_615_reg_2622 <= grp_fu_370_p2[32'd15];
    end
end

always @ (*) begin
    if (((icmp_ln41_reg_2331 == 1'd1) & (ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage7 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_pp0_stage0)) begin
        ap_enable_reg_pp0_iter0 = ap_start_int;
    end else begin
        ap_enable_reg_pp0_iter0 = ap_enable_reg_pp0_iter0_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter1 == 1'b0)) begin
        ap_idle_pp0_1to1 = 1'b1;
    end else begin
        ap_idle_pp0_1to1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7_subdone) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 10'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_198;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 13'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_206;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_oc_load = 4'd0;
    end else begin
        ap_sig_allocacmp_oc_load = oc_fu_202;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_bias_q_ce0_local = 1'b1;
    end else begin
        conv1_bias_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        conv1_weight_q_address0_local = p_cast40_fu_990_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        conv1_weight_q_address0_local = p_cast39_fu_772_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        conv1_weight_q_address0_local = p_cast38_fu_736_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        conv1_weight_q_address0_local = p_cast37_fu_622_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        conv1_weight_q_address0_local = p_cast36_fu_564_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        conv1_weight_q_address0_local = p_cast35_fu_518_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv1_weight_q_address0_local = p_cast34_fu_489_p1;
    end else begin
        conv1_weight_q_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6_11001) & (1'b1 == ap_CS_fsm_pp0_stage6)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4_11001) & (1'b1 == ap_CS_fsm_pp0_stage4)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5_11001) & (1'b1 == ap_CS_fsm_pp0_stage5)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        conv1_weight_q_ce0_local = 1'b1;
    end else begin
        conv1_weight_q_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_370_p0 = sext_ln51_365_fu_1596_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_370_p0 = sext_ln51_361_fu_1410_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_370_p0 = sext_ln51_357_fu_1275_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_370_p0 = sext_ln51_354_fu_1094_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_370_p0 = sext_ln51_350_fu_962_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_370_p0 = sext_ln51_345_fu_757_p1;
    end else begin
        grp_fu_370_p0 = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        grp_fu_370_p1 = sext_ln51_366_fu_1601_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        grp_fu_370_p1 = sext_ln51_362_fu_1415_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage7) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        grp_fu_370_p1 = sext_ln51_358_fu_1280_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage6) & (1'b1 == ap_CS_fsm_pp0_stage6))) begin
        grp_fu_370_p1 = shl_i_i_i241_3_cast_fu_980_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage5) & (1'b1 == ap_CS_fsm_pp0_stage5))) begin
        grp_fu_370_p1 = sext_ln51_351_fu_967_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage4) & (1'b1 == ap_CS_fsm_pp0_stage4))) begin
        grp_fu_370_p1 = sext_ln51_346_fu_762_p1;
    end else begin
        grp_fu_370_p1 = 'bx;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
        input_r_address0_local = zext_ln48_6_fu_712_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
        input_r_address0_local = zext_ln48_4_fu_592_p1;
    end else if (((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
        input_r_address0_local = zext_ln48_2_fu_546_p1;
    end else if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        input_r_address0_local = zext_ln42_fu_498_p1;
    end else begin
        input_r_address0_local = 'bx;
    end
end

always @ (*) begin
    if ((ap_enable_reg_pp0_iter0_reg == 1'b1)) begin
        if (((1'b0 == ap_block_pp0_stage3) & (1'b1 == ap_CS_fsm_pp0_stage3))) begin
            input_r_address1_local = zext_ln48_5_fu_694_p1;
        end else if (((1'b0 == ap_block_pp0_stage2) & (1'b1 == ap_CS_fsm_pp0_stage2))) begin
            input_r_address1_local = zext_ln48_3_fu_574_p1;
        end else if (((1'b0 == ap_block_pp0_stage1) & (1'b1 == ap_CS_fsm_pp0_stage1))) begin
            input_r_address1_local = zext_ln48_fu_528_p1;
        end else begin
            input_r_address1_local = 'bx;
        end
    end else begin
        input_r_address1_local = 'bx;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)) | ((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0)))) begin
        input_r_ce0_local = 1'b1;
    end else begin
        input_r_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if ((((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage1_11001) & (1'b1 == ap_CS_fsm_pp0_stage1)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage2_11001) & (1'b1 == ap_CS_fsm_pp0_stage2)) | ((ap_enable_reg_pp0_iter0_reg == 1'b1) & (1'b0 == ap_block_pp0_stage3_11001) & (1'b1 == ap_CS_fsm_pp0_stage3)))) begin
        input_r_ce1_local = 1'b1;
    end else begin
        input_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        output_r_ce1_local = 1'b1;
    end else begin
        output_r_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage7_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage7))) begin
        output_r_we1_local = 1'b1;
    end else begin
        output_r_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            if ((~((ap_start_int == 1'b0) & (ap_idle_pp0_1to1 == 1'b1)) & (1'b0 == ap_block_pp0_stage0_subdone))) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end
        end
        ap_ST_fsm_pp0_stage1 : begin
            if ((1'b0 == ap_block_pp0_stage1_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            end
        end
        ap_ST_fsm_pp0_stage2 : begin
            if ((1'b0 == ap_block_pp0_stage2_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            end
        end
        ap_ST_fsm_pp0_stage3 : begin
            if ((1'b0 == ap_block_pp0_stage3_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            end
        end
        ap_ST_fsm_pp0_stage4 : begin
            if ((1'b0 == ap_block_pp0_stage4_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            end
        end
        ap_ST_fsm_pp0_stage5 : begin
            if ((1'b0 == ap_block_pp0_stage5_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage5;
            end
        end
        ap_ST_fsm_pp0_stage6 : begin
            if ((1'b0 == ap_block_pp0_stage6_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage6;
            end
        end
        ap_ST_fsm_pp0_stage7 : begin
            if ((1'b0 == ap_block_pp0_stage7_subdone)) begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            end else begin
                ap_NS_fsm = ap_ST_fsm_pp0_stage7;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign acc_264_fu_825_p1 = $signed(tmp_590_fu_815_p4);

assign acc_265_fu_840_p2 = ($signed(acc_264_fu_825_p1) + $signed(zext_ln51_fu_837_p1));

assign acc_266_fu_1004_p4 = acc_4_reg_2439;

assign acc_266_fu_1004_p7 = 'bx;

assign acc_266_fu_1004_p8 = {{and_ln51_321_reg_2507}, {tmp_588_reg_2391}};

assign acc_267_fu_1052_p4 = {{add_ln51_184_fu_1038_p2[55:16]}};

assign acc_268_fu_1073_p2 = (acc_267_fu_1052_p4 + zext_ln51_85_fu_1070_p1);

assign acc_269_fu_1194_p2 = ((and_ln51_323_fu_1145_p2[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign acc_269_fu_1194_p7 = 'bx;

assign acc_269_fu_1194_p8 = {{and_ln51_325_fu_1181_p2}, {tmp_594_reg_2412}};

assign acc_271_fu_1292_p2 = (acc_270_reg_2565 + zext_ln51_86_fu_1289_p1);

assign acc_272_fu_1386_p3 = ((or_ln51_181_fu_1380_p2[0:0] == 1'b1) ? select_ln51_110_fu_1372_p3 : acc_271_fu_1292_p2);

assign acc_273_fu_1454_p4 = {{add_ln51_188_fu_1440_p2[55:16]}};

assign acc_274_fu_1475_p2 = (acc_273_fu_1454_p4 + zext_ln51_87_fu_1472_p1);

assign acc_275_fu_1647_p7 = 'bx;

assign acc_275_fu_1647_p8 = {{and_ln51_332_reg_2617}, {tmp_603_reg_2423}};

assign acc_276_fu_1693_p4 = {{add_ln51_190_fu_1679_p2[55:16]}};

assign acc_277_fu_1714_p2 = (acc_276_fu_1693_p4 + zext_ln51_88_fu_1711_p1);

assign acc_278_fu_1823_p2 = ((and_ln51_334_fu_1774_p2[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign acc_278_fu_1823_p7 = 'bx;

assign acc_278_fu_1823_p8 = {{and_ln51_336_fu_1810_p2}, {tmp_608_reg_2450}};

assign acc_280_fu_1897_p2 = (acc_279_reg_2680 + zext_ln51_89_fu_1894_p1);

assign acc_281_fu_2004_p2 = ((and_ln51_338_fu_1954_p2[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign acc_281_fu_2004_p7 = 'bx;

assign acc_281_fu_2004_p8 = {{and_ln51_340_fu_1991_p2}, {tmp_613_reg_2461_pp0_iter1_reg}};

assign acc_4_fu_682_p3 = ((tmp_587_reg_2386[0:0] == 1'b1) ? 32'd0 : acc_fu_674_p3);

assign acc_fu_674_p3 = {{tmp_s_fu_664_p4}, {tmp_586_fu_656_p3}};

assign add_i_i_i_i74_fu_2029_p2 = ($signed(sext_ln55_fu_2023_p1) + $signed(p_cast_fu_2026_p1));

assign add_ln41_3_fu_453_p2 = (ap_sig_allocacmp_oc_load + 4'd1);

assign add_ln41_fu_427_p2 = (ap_sig_allocacmp_indvar_flatten_load + 13'd1);

assign add_ln47_5_fu_541_p2 = ($signed(select_ln41_reg_2335) + $signed(10'd1022));

assign add_ln47_6_fu_569_p2 = ($signed(select_ln41_reg_2335) + $signed(10'd1023));

assign add_ln47_7_fu_587_p2 = (select_ln41_reg_2335 + 10'd1);

assign add_ln47_8_fu_689_p2 = (select_ln41_reg_2335 + 10'd2);

assign add_ln47_9_fu_707_p2 = (select_ln41_reg_2335 + 10'd3);

assign add_ln47_fu_523_p2 = ($signed(select_ln41_reg_2335) + $signed(10'd1021));

assign add_ln51_184_fu_1038_p2 = ($signed(sext_ln51_352_fu_1030_p1) + $signed(sext_ln51_353_fu_1034_p1));

assign add_ln51_186_fu_1228_p2 = ($signed(sext_ln51_355_fu_1220_p1) + $signed(sext_ln51_356_fu_1224_p1));

assign add_ln51_188_fu_1440_p2 = ($signed(sext_ln51_359_fu_1432_p1) + $signed(sext_ln51_360_fu_1436_p1));

assign add_ln51_190_fu_1679_p2 = ($signed(sext_ln51_363_fu_1672_p1) + $signed(sext_ln51_364_fu_1676_p1));

assign add_ln51_192_fu_1857_p2 = ($signed(sext_ln51_367_fu_1849_p1) + $signed(sext_ln51_368_fu_1853_p1));

assign add_ln51_fu_797_p2 = ($signed(sext_ln51_347_fu_789_p1) + $signed(sext_ln51_348_fu_793_p1));

assign add_ln55_5_fu_2143_p2 = (trunc_ln_fu_2113_p4 + zext_ln55_fu_2139_p1);

assign add_ln55_6_fu_725_p2 = (zext_ln42_11_fu_627_p1 + tmp_69_fu_610_p3);

assign add_ln55_7_fu_2057_p2 = ($signed(sext_ln55_6_fu_2042_p1) + $signed(sext_ln55_7_fu_2053_p1));

assign add_ln55_8_fu_2094_p2 = ($signed(sub_ln55_reg_2704) + $signed(sext_ln55_3_fu_2091_p1));

assign add_ln55_fu_2099_p2 = ($signed(shl_i_i16_i_cast66_fu_2087_p1) + $signed(add_ln55_8_fu_2094_p2));

assign and_ln51_319_fu_902_p2 = (xor_ln51_517_fu_884_p2 & or_ln51_176_fu_896_p2);

assign and_ln51_320_fu_920_p2 = (xor_ln51_519_fu_914_p2 & tmp_589_fu_807_p3);

assign and_ln51_321_fu_940_p2 = (xor_ln48_fu_777_p2 & or_ln51_177_fu_926_p2);

assign and_ln51_322_fu_1109_p2 = (xor_ln51_520_fu_1104_p2 & tmp_597_reg_2534);

assign and_ln51_323_fu_1145_p2 = (xor_ln51_523_fu_1129_p2 & or_ln51_178_fu_1140_p2);

assign and_ln51_324_fu_1162_p2 = (xor_ln51_525_fu_1156_p2 & tmp_595_reg_2527);

assign and_ln51_325_fu_1181_p2 = (xor_ln48_5_fu_1099_p2 & or_ln51_179_fu_1167_p2);

assign and_ln51_326_fu_1311_p2 = (xor_ln51_526_fu_1305_p2 & tmp_601_reg_2570);

assign and_ln51_327_fu_1349_p2 = (xor_ln51_529_fu_1332_p2 & or_ln51_180_fu_1343_p2);

assign and_ln51_328_fu_1367_p2 = (xor_ln51_531_fu_1361_p2 & tmp_599_reg_2558);

assign and_ln51_329_fu_1495_p2 = (xor_ln51_532_fu_1489_p2 & tmp_606_fu_1464_p3);

assign and_ln51_330_fu_1537_p2 = (xor_ln51_535_fu_1519_p2 & or_ln51_182_fu_1531_p2);

assign and_ln51_331_fu_1555_p2 = (xor_ln51_537_fu_1549_p2 & tmp_604_fu_1446_p3);

assign and_ln51_332_fu_1575_p2 = (xor_ln48_6_fu_1420_p2 & or_ln51_183_fu_1561_p2);

assign and_ln51_333_fu_1738_p2 = (xor_ln51_538_fu_1733_p2 & tmp_611_reg_2649);

assign and_ln51_334_fu_1774_p2 = (xor_ln51_541_fu_1758_p2 & or_ln51_184_fu_1769_p2);

assign and_ln51_335_fu_1791_p2 = (xor_ln51_543_fu_1785_p2 & tmp_609_reg_2642);

assign and_ln51_336_fu_1810_p2 = (xor_ln48_7_fu_1728_p2 & or_ln51_185_fu_1796_p2);

assign and_ln51_337_fu_1916_p2 = (xor_ln51_544_fu_1910_p2 & tmp_616_reg_2685);

assign and_ln51_338_fu_1954_p2 = (xor_ln51_547_fu_1937_p2 & or_ln51_186_fu_1948_p2);

assign and_ln51_339_fu_1972_p2 = (xor_ln51_549_fu_1966_p2 & tmp_614_reg_2673);

assign and_ln51_340_fu_1991_p2 = (xor_ln48_8_fu_1889_p2 & or_ln51_187_fu_1977_p2);

assign and_ln51_fu_860_p2 = (xor_ln51_fu_854_p2 & tmp_592_fu_829_p3);

assign and_ln55_11_fu_2225_p2 = (xor_ln55_9_fu_2219_p2 & icmp_ln55_reg_2738);

assign and_ln55_12_fu_2236_p2 = (icmp_ln55_5_reg_2743 & and_ln55_reg_2731);

assign and_ln55_13_fu_2256_p2 = (xor_ln55_11_fu_2251_p2 & or_ln55_fu_2246_p2);

assign and_ln55_14_fu_2262_p2 = (tmp_624_reg_2725 & select_ln55_7_fu_2230_p3);

assign and_ln55_15_fu_2279_p2 = (xor_ln55_12_fu_2273_p2 & tmp_621_reg_2714);

assign and_ln55_fu_2163_p2 = (xor_ln55_fu_2157_p2 & tmp_623_fu_2131_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_pp0_stage1 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_pp0_stage2 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_pp0_stage3 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_pp0_stage4 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_pp0_stage5 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_pp0_stage6 = ap_CS_fsm[32'd6];

assign ap_CS_fsm_pp0_stage7 = ap_CS_fsm[32'd7];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage1_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage2_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage3_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage4_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage5_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage6_subdone = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage7_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage7;

assign ap_ready = ap_ready_sig;

assign conv1_bias_q_address0 = zext_ln41_fu_1285_p1;

assign empty_63_fu_483_p2 = (p_shl1_fu_475_p3 - zext_ln41_1_fu_467_p1);

assign empty_64_fu_494_p1 = empty_63_fu_483_p2[5:0];

assign empty_65_fu_513_p2 = (empty_64_reg_2356 + 6'd1);

assign empty_66_fu_559_p2 = (empty_64_reg_2356 + 6'd2);

assign empty_67_fu_617_p2 = (empty_64_reg_2356 + 6'd3);

assign empty_68_fu_731_p2 = (empty_64_reg_2356 + 6'd4);

assign empty_69_fu_767_p2 = (empty_64_reg_2356 + 6'd5);

assign empty_70_fu_985_p2 = (empty_64_reg_2356 + 6'd6);

assign empty_fu_471_p1 = select_ln41_3_fu_459_p3[2:0];

assign icmp_ln41_fu_421_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 13'd4096) ? 1'b1 : 1'b0);

assign icmp_ln42_fu_439_p2 = ((ap_sig_allocacmp_i_load == 10'd512) ? 1'b1 : 1'b0);

assign icmp_ln55_5_fu_2195_p2 = ((tmp_271_fu_2185_p4 == 9'd511) ? 1'b1 : 1'b0);

assign icmp_ln55_6_fu_2201_p2 = ((tmp_271_fu_2185_p4 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln55_fu_2179_p2 = ((tmp_270_fu_2169_p4 == 8'd255) ? 1'b1 : 1'b0);

assign input_r_address0 = input_r_address0_local;

assign input_r_address1 = input_r_address1_local;

assign input_r_ce0 = input_r_ce0_local;

assign input_r_ce1 = input_r_ce1_local;

assign mul_i_fu_1617_p1 = 31'd3079;

assign or_ln51_176_fu_896_p2 = (xor_ln51_518_fu_890_p2 | tmp_593_fu_846_p3);

assign or_ln51_177_fu_926_p2 = (and_ln51_320_fu_920_p2 | and_ln51_319_fu_902_p2);

assign or_ln51_178_fu_1140_p2 = (xor_ln51_524_fu_1134_p2 | tmp_598_reg_2545);

assign or_ln51_179_fu_1167_p2 = (and_ln51_324_fu_1162_p2 | and_ln51_323_fu_1145_p2);

assign or_ln51_180_fu_1343_p2 = (xor_ln51_530_fu_1337_p2 | tmp_602_fu_1297_p3);

assign or_ln51_181_fu_1380_p2 = (and_ln51_328_fu_1367_p2 | and_ln51_327_fu_1349_p2);

assign or_ln51_182_fu_1531_p2 = (xor_ln51_536_fu_1525_p2 | tmp_607_fu_1481_p3);

assign or_ln51_183_fu_1561_p2 = (and_ln51_331_fu_1555_p2 | and_ln51_330_fu_1537_p2);

assign or_ln51_184_fu_1769_p2 = (xor_ln51_542_fu_1763_p2 | tmp_612_reg_2660);

assign or_ln51_185_fu_1796_p2 = (and_ln51_335_fu_1791_p2 | and_ln51_334_fu_1774_p2);

assign or_ln51_186_fu_1948_p2 = (xor_ln51_548_fu_1942_p2 | tmp_617_fu_1902_p3);

assign or_ln51_187_fu_1977_p2 = (and_ln51_339_fu_1972_p2 | and_ln51_338_fu_1954_p2);

assign or_ln51_265_fu_908_p2 = (tmp_593_fu_846_p3 | and_ln51_fu_860_p2);

assign or_ln51_266_fu_1119_p2 = (xor_ln51_521_fu_1114_p2 | tmp_598_reg_2545);

assign or_ln51_267_fu_1151_p2 = (tmp_598_reg_2545 | and_ln51_322_fu_1109_p2);

assign or_ln51_268_fu_1321_p2 = (xor_ln51_527_fu_1316_p2 | tmp_602_fu_1297_p3);

assign or_ln51_269_fu_1355_p2 = (tmp_602_fu_1297_p3 | and_ln51_326_fu_1311_p2);

assign or_ln51_270_fu_1507_p2 = (xor_ln51_533_fu_1501_p2 | tmp_607_fu_1481_p3);

assign or_ln51_271_fu_1543_p2 = (tmp_607_fu_1481_p3 | and_ln51_329_fu_1495_p2);

assign or_ln51_272_fu_1748_p2 = (xor_ln51_539_fu_1743_p2 | tmp_612_reg_2660);

assign or_ln51_273_fu_1780_p2 = (tmp_612_reg_2660 | and_ln51_333_fu_1738_p2);

assign or_ln51_274_fu_1926_p2 = (xor_ln51_545_fu_1921_p2 | tmp_617_fu_1902_p3);

assign or_ln51_275_fu_1960_p2 = (tmp_617_fu_1902_p3 | and_ln51_337_fu_1916_p2);

assign or_ln51_fu_872_p2 = (xor_ln51_515_fu_866_p2 | tmp_593_fu_846_p3);

assign or_ln55_3_fu_2292_p2 = (and_ln55_15_fu_2279_p2 | and_ln55_13_fu_2256_p2);

assign or_ln55_4_fu_2267_p2 = (and_ln55_14_fu_2262_p2 | and_ln55_12_fu_2236_p2);

assign or_ln55_fu_2246_p2 = (xor_ln55_10_fu_2240_p2 | tmp_624_reg_2725);

assign output_r_address1 = zext_ln55_3_fu_2306_p1;

assign output_r_ce1 = output_r_ce1_local;

assign output_r_d1 = select_ln55_9_fu_2298_p3;

assign output_r_we1 = output_r_we1_local;

assign p_cast34_fu_489_p1 = empty_63_fu_483_p2;

assign p_cast35_fu_518_p1 = empty_65_fu_513_p2;

assign p_cast36_fu_564_p1 = empty_66_fu_559_p2;

assign p_cast37_fu_622_p1 = empty_67_fu_617_p2;

assign p_cast38_fu_736_p1 = empty_68_fu_731_p2;

assign p_cast39_fu_772_p1 = empty_69_fu_767_p2;

assign p_cast40_fu_990_p1 = empty_70_fu_985_p2;

assign p_cast_fu_2026_p1 = tmp_reg_2632;

assign p_shl1_fu_475_p3 = {{select_ln41_3_fu_459_p3}, {3'd0}};

assign select_ln41_3_fu_459_p3 = ((icmp_ln42_fu_439_p2[0:0] == 1'b1) ? add_ln41_3_fu_453_p2 : ap_sig_allocacmp_oc_load);

assign select_ln41_fu_445_p3 = ((icmp_ln42_fu_439_p2[0:0] == 1'b1) ? 10'd0 : ap_sig_allocacmp_i_load);

assign select_ln51_110_fu_1372_p3 = ((and_ln51_327_fu_1349_p2[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign select_ln51_112_fu_1567_p3 = ((and_ln51_330_fu_1537_p2[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign select_ln51_fu_932_p3 = ((and_ln51_319_fu_902_p2[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign select_ln55_7_fu_2230_p3 = ((and_ln55_reg_2731[0:0] == 1'b1) ? and_ln55_11_fu_2225_p2 : icmp_ln55_5_reg_2743);

assign select_ln55_8_fu_2284_p3 = ((and_ln55_13_fu_2256_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln55_9_fu_2298_p3 = ((or_ln55_3_fu_2292_p2[0:0] == 1'b1) ? select_ln55_8_fu_2284_p3 : add_ln55_5_reg_2720);

assign select_ln55_fu_2214_p3 = ((and_ln55_reg_2731[0:0] == 1'b1) ? icmp_ln55_5_reg_2743 : icmp_ln55_6_reg_2750);

assign sext_ln51_345_fu_757_p1 = $signed(shl_ln51_235_fu_741_p3);

assign sext_ln51_346_fu_762_p1 = $signed(shl_ln51_236_fu_749_p3);

assign sext_ln51_347_fu_789_p1 = $signed(shl_ln51_237_fu_782_p3);

assign sext_ln51_348_fu_793_p1 = reg_399;

assign sext_ln51_349_fu_803_p1 = add_ln51_fu_797_p2;

assign sext_ln51_350_fu_962_p1 = $signed(shl_ln51_238_fu_946_p3);

assign sext_ln51_351_fu_967_p1 = $signed(shl_ln51_239_fu_954_p3);

assign sext_ln51_352_fu_1030_p1 = $signed(shl_ln51_240_fu_1022_p3);

assign sext_ln51_353_fu_1034_p1 = reg_399;

assign sext_ln51_354_fu_1094_p1 = $signed(shl_ln51_241_fu_1087_p3);

assign sext_ln51_355_fu_1220_p1 = $signed(shl_ln51_242_fu_1212_p3);

assign sext_ln51_356_fu_1224_p1 = reg_399;

assign sext_ln51_357_fu_1275_p1 = $signed(shl_ln51_243_fu_1260_p3);

assign sext_ln51_358_fu_1280_p1 = $signed(shl_ln51_244_fu_1267_p3);

assign sext_ln51_359_fu_1432_p1 = $signed(shl_ln51_245_fu_1425_p3);

assign sext_ln51_360_fu_1436_p1 = reg_399;

assign sext_ln51_361_fu_1410_p1 = $signed(shl_ln51_246_fu_1394_p3);

assign sext_ln51_362_fu_1415_p1 = $signed(shl_ln51_247_fu_1402_p3);

assign sext_ln51_363_fu_1672_p1 = $signed(shl_ln51_248_fu_1664_p3);

assign sext_ln51_364_fu_1676_p1 = mul_ln51_91_reg_2592;

assign sext_ln51_365_fu_1596_p1 = $signed(shl_ln51_249_fu_1581_p3);

assign sext_ln51_366_fu_1601_p1 = $signed(shl_ln51_250_fu_1588_p3);

assign sext_ln51_367_fu_1849_p1 = $signed(shl_ln51_251_fu_1841_p3);

assign sext_ln51_368_fu_1853_p1 = reg_399;

assign sext_ln55_3_fu_2091_p1 = acc_281_reg_2691;

assign sext_ln55_6_fu_2042_p1 = $signed(tmp_618_fu_2035_p3);

assign sext_ln55_7_fu_2053_p1 = $signed(tmp_619_fu_2046_p3);

assign sext_ln55_8_fu_2070_p1 = $signed(tmp_620_fu_2063_p3);

assign sext_ln55_fu_2023_p1 = $signed(tmp_70_reg_2627);

assign shl_i_i16_i_cast66_fu_2087_p1 = $signed(shl_i_i16_i_fu_2080_p3);

assign shl_i_i16_i_fu_2080_p3 = {{add_i_i_i_i74_reg_2699}, {16'd0}};

assign shl_i_i_i241_3_cast_fu_980_p1 = $signed(shl_i_i_i241_3_fu_972_p3);

assign shl_i_i_i241_3_fu_972_p3 = {{reg_386}, {16'd0}};

assign shl_i_i_i_fu_1606_p3 = {{conv1_bias_q_load_reg_2602}, {10'd0}};

assign shl_ln51_235_fu_741_p3 = {{reg_394}, {6'd0}};

assign shl_ln51_236_fu_749_p3 = {{reg_386}, {16'd0}};

assign shl_ln51_237_fu_782_p3 = {{acc_4_reg_2439}, {16'd0}};

assign shl_ln51_238_fu_946_p3 = {{reg_390}, {6'd0}};

assign shl_ln51_239_fu_954_p3 = {{reg_382}, {16'd0}};

assign shl_ln51_240_fu_1022_p3 = {{acc_266_fu_1004_p9}, {16'd0}};

assign shl_ln51_241_fu_1087_p3 = {{input_load_3_reg_2402}, {6'd0}};

assign shl_ln51_242_fu_1212_p3 = {{acc_269_fu_1194_p9}, {16'd0}};

assign shl_ln51_243_fu_1260_p3 = {{input_load_4_reg_2445}, {6'd0}};

assign shl_ln51_244_fu_1267_p3 = {{reg_382}, {16'd0}};

assign shl_ln51_245_fu_1425_p3 = {{acc_272_reg_2586}, {16'd0}};

assign shl_ln51_246_fu_1394_p3 = {{reg_394}, {6'd0}};

assign shl_ln51_247_fu_1402_p3 = {{reg_386}, {16'd0}};

assign shl_ln51_248_fu_1664_p3 = {{acc_275_fu_1647_p9}, {16'd0}};

assign shl_ln51_249_fu_1581_p3 = {{input_load_6_reg_2487}, {6'd0}};

assign shl_ln51_250_fu_1588_p3 = {{reg_382}, {16'd0}};

assign shl_ln51_251_fu_1841_p3 = {{acc_278_fu_1823_p9}, {16'd0}};

assign shl_ln51_s_fu_638_p3 = {{reg_382}, {16'd0}};

assign shl_ln_fu_630_p3 = {{reg_390}, {6'd0}};

assign sub_ln55_fu_2074_p2 = ($signed(add_ln55_7_fu_2057_p2) - $signed(sext_ln55_8_fu_2070_p1));

assign tmp_270_fu_2169_p4 = {{add_ln55_fu_2099_p2[48:41]}};

assign tmp_271_fu_2185_p4 = {{add_ln55_fu_2099_p2[48:40]}};

assign tmp_586_fu_656_p3 = mul_ln51_fu_366_p2[32'd15];

assign tmp_589_fu_807_p3 = sext_ln51_349_fu_803_p1[32'd56];

assign tmp_590_fu_815_p4 = {{add_ln51_fu_797_p2[48:16]}};

assign tmp_592_fu_829_p3 = sext_ln51_349_fu_803_p1[32'd55];

assign tmp_593_fu_846_p3 = acc_265_fu_840_p2[32'd39];

assign tmp_602_fu_1297_p3 = acc_271_fu_1292_p2[32'd39];

assign tmp_604_fu_1446_p3 = add_ln51_188_fu_1440_p2[32'd56];

assign tmp_606_fu_1464_p3 = add_ln51_188_fu_1440_p2[32'd55];

assign tmp_607_fu_1481_p3 = acc_274_fu_1475_p2[32'd39];

assign tmp_617_fu_1902_p3 = acc_280_fu_1897_p2[32'd39];

assign tmp_618_fu_2035_p3 = {{acc_281_reg_2691}, {8'd0}};

assign tmp_619_fu_2046_p3 = {{acc_281_reg_2691}, {5'd0}};

assign tmp_620_fu_2063_p3 = {{acc_281_reg_2691}, {2'd0}};

assign tmp_622_fu_2123_p3 = add_ln55_fu_2099_p2[32'd21];

assign tmp_623_fu_2131_p3 = add_ln55_fu_2099_p2[32'd39];

assign tmp_624_fu_2149_p3 = add_ln55_5_fu_2143_p2[32'd17];

assign tmp_625_fu_2207_p3 = add_ln55_reg_2709[32'd40];

assign tmp_69_fu_610_p3 = {{empty_reg_2351}, {9'd0}};

assign tmp_s_fu_664_p4 = {{mul_ln51_fu_366_p2[47:17]}};

assign trunc_ln_fu_2113_p4 = {{add_ln55_fu_2099_p2[39:22]}};

assign xor_ln48_5_fu_1099_p2 = (tmp_594_reg_2412 ^ 1'd1);

assign xor_ln48_6_fu_1420_p2 = (tmp_603_reg_2423 ^ 1'd1);

assign xor_ln48_7_fu_1728_p2 = (tmp_608_reg_2450 ^ 1'd1);

assign xor_ln48_8_fu_1889_p2 = (tmp_613_reg_2461_pp0_iter1_reg ^ 1'd1);

assign xor_ln48_fu_777_p2 = (tmp_588_reg_2391 ^ 1'd1);

assign xor_ln51_515_fu_866_p2 = (tmp_592_fu_829_p3 ^ 1'd1);

assign xor_ln51_516_fu_878_p2 = (tmp_589_fu_807_p3 ^ or_ln51_fu_872_p2);

assign xor_ln51_517_fu_884_p2 = (tmp_589_fu_807_p3 ^ 1'd1);

assign xor_ln51_518_fu_890_p2 = (xor_ln51_516_fu_878_p2 ^ 1'd1);

assign xor_ln51_519_fu_914_p2 = (or_ln51_265_fu_908_p2 ^ 1'd1);

assign xor_ln51_520_fu_1104_p2 = (tmp_598_reg_2545 ^ 1'd1);

assign xor_ln51_521_fu_1114_p2 = (tmp_597_reg_2534 ^ 1'd1);

assign xor_ln51_522_fu_1124_p2 = (tmp_595_reg_2527 ^ or_ln51_266_fu_1119_p2);

assign xor_ln51_523_fu_1129_p2 = (tmp_595_reg_2527 ^ 1'd1);

assign xor_ln51_524_fu_1134_p2 = (xor_ln51_522_fu_1124_p2 ^ 1'd1);

assign xor_ln51_525_fu_1156_p2 = (or_ln51_267_fu_1151_p2 ^ 1'd1);

assign xor_ln51_526_fu_1305_p2 = (tmp_602_fu_1297_p3 ^ 1'd1);

assign xor_ln51_527_fu_1316_p2 = (tmp_601_reg_2570 ^ 1'd1);

assign xor_ln51_528_fu_1327_p2 = (tmp_599_reg_2558 ^ or_ln51_268_fu_1321_p2);

assign xor_ln51_529_fu_1332_p2 = (tmp_599_reg_2558 ^ 1'd1);

assign xor_ln51_530_fu_1337_p2 = (xor_ln51_528_fu_1327_p2 ^ 1'd1);

assign xor_ln51_531_fu_1361_p2 = (or_ln51_269_fu_1355_p2 ^ 1'd1);

assign xor_ln51_532_fu_1489_p2 = (tmp_607_fu_1481_p3 ^ 1'd1);

assign xor_ln51_533_fu_1501_p2 = (tmp_606_fu_1464_p3 ^ 1'd1);

assign xor_ln51_534_fu_1513_p2 = (tmp_604_fu_1446_p3 ^ or_ln51_270_fu_1507_p2);

assign xor_ln51_535_fu_1519_p2 = (tmp_604_fu_1446_p3 ^ 1'd1);

assign xor_ln51_536_fu_1525_p2 = (xor_ln51_534_fu_1513_p2 ^ 1'd1);

assign xor_ln51_537_fu_1549_p2 = (or_ln51_271_fu_1543_p2 ^ 1'd1);

assign xor_ln51_538_fu_1733_p2 = (tmp_612_reg_2660 ^ 1'd1);

assign xor_ln51_539_fu_1743_p2 = (tmp_611_reg_2649 ^ 1'd1);

assign xor_ln51_540_fu_1753_p2 = (tmp_609_reg_2642 ^ or_ln51_272_fu_1748_p2);

assign xor_ln51_541_fu_1758_p2 = (tmp_609_reg_2642 ^ 1'd1);

assign xor_ln51_542_fu_1763_p2 = (xor_ln51_540_fu_1753_p2 ^ 1'd1);

assign xor_ln51_543_fu_1785_p2 = (or_ln51_273_fu_1780_p2 ^ 1'd1);

assign xor_ln51_544_fu_1910_p2 = (tmp_617_fu_1902_p3 ^ 1'd1);

assign xor_ln51_545_fu_1921_p2 = (tmp_616_reg_2685 ^ 1'd1);

assign xor_ln51_546_fu_1932_p2 = (tmp_614_reg_2673 ^ or_ln51_274_fu_1926_p2);

assign xor_ln51_547_fu_1937_p2 = (tmp_614_reg_2673 ^ 1'd1);

assign xor_ln51_548_fu_1942_p2 = (xor_ln51_546_fu_1932_p2 ^ 1'd1);

assign xor_ln51_549_fu_1966_p2 = (or_ln51_275_fu_1960_p2 ^ 1'd1);

assign xor_ln51_fu_854_p2 = (tmp_593_fu_846_p3 ^ 1'd1);

assign xor_ln55_10_fu_2240_p2 = (select_ln55_fu_2214_p3 ^ 1'd1);

assign xor_ln55_11_fu_2251_p2 = (tmp_621_reg_2714 ^ 1'd1);

assign xor_ln55_12_fu_2273_p2 = (or_ln55_4_fu_2267_p2 ^ 1'd1);

assign xor_ln55_9_fu_2219_p2 = (tmp_625_fu_2207_p3 ^ 1'd1);

assign xor_ln55_fu_2157_p2 = (tmp_624_fu_2149_p3 ^ 1'd1);

assign zext_ln41_1_fu_467_p1 = select_ln41_3_fu_459_p3;

assign zext_ln41_fu_1285_p1 = select_ln41_3_reg_2346;

assign zext_ln42_11_fu_627_p1 = select_ln41_reg_2335;

assign zext_ln42_fu_498_p1 = select_ln41_fu_445_p3;

assign zext_ln48_2_fu_546_p1 = add_ln47_5_fu_541_p2;

assign zext_ln48_3_fu_574_p1 = add_ln47_6_fu_569_p2;

assign zext_ln48_4_fu_592_p1 = add_ln47_7_fu_587_p2;

assign zext_ln48_5_fu_694_p1 = add_ln47_8_fu_689_p2;

assign zext_ln48_6_fu_712_p1 = add_ln47_9_fu_707_p2;

assign zext_ln48_fu_528_p1 = add_ln47_fu_523_p2;

assign zext_ln51_85_fu_1070_p1 = tmp_596_reg_2512;

assign zext_ln51_86_fu_1289_p1 = tmp_600_reg_2553;

assign zext_ln51_87_fu_1472_p1 = tmp_605_reg_2576;

assign zext_ln51_88_fu_1711_p1 = tmp_610_reg_2597;

assign zext_ln51_89_fu_1894_p1 = tmp_615_reg_2622;

assign zext_ln51_fu_837_p1 = tmp_591_reg_2482;

assign zext_ln55_3_fu_2306_p1 = add_ln55_6_reg_2472_pp0_iter1_reg;

assign zext_ln55_fu_2139_p1 = tmp_622_fu_2123_p3;

always @ (posedge ap_clk) begin
    sub_ln55_reg_2704[1:0] <= 2'b00;
end

endmodule //phase2_rpm_cnn_conv1d_same_q
