// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module phase2_rpm_cnn_phase2_rpm_cnn_Pipeline_VITIS_LOOP_85_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        tmp_27,
        conv3_out_address0,
        conv3_out_ce0,
        conv3_out_q0,
        sum_out,
        sum_out_ap_vld
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [11:0] tmp_27;
output  [11:0] conv3_out_address0;
output   conv3_out_ce0;
input  [17:0] conv3_out_q0;
output  [39:0] sum_out;
output   sum_out_ap_vld;

reg ap_idle;
reg sum_out_ap_vld;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln85_fu_109_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
reg   [0:0] icmp_ln85_reg_253;
reg   [17:0] conv3_out_load_reg_262;
wire   [63:0] zext_ln87_fu_131_p1;
wire    ap_block_pp0_stage0;
reg   [39:0] sum_fu_62;
wire   [39:0] sum_2_fu_221_p3;
wire    ap_loop_init;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg   [7:0] i_fu_66;
wire   [7:0] add_ln85_fu_115_p2;
reg   [7:0] ap_sig_allocacmp_i_1;
wire    ap_block_pp0_stage0_01001;
reg    conv3_out_ce0_local;
wire   [11:0] zext_ln85_fu_121_p1;
wire   [11:0] add_ln87_fu_125_p2;
wire  signed [23:0] shl_ln2_fu_144_p3;
wire  signed [39:0] sext_ln87_1_fu_155_p0;
wire  signed [39:0] sext_ln87_fu_151_p1;
wire  signed [39:0] add_ln87_2_fu_163_p1;
wire  signed [40:0] sext_ln87_2_fu_159_p1;
wire  signed [40:0] sext_ln87_1_fu_155_p1;
wire   [40:0] add_ln87_1_fu_169_p2;
wire   [39:0] add_ln87_2_fu_163_p2;
wire   [0:0] tmp_fu_175_p3;
wire   [0:0] tmp_1_fu_187_p3;
wire   [0:0] xor_ln87_fu_195_p2;
wire   [0:0] and_ln87_fu_201_p2;
wire   [0:0] xor_ln87_1_fu_207_p2;
wire   [39:0] select_ln87_fu_213_p3;
wire   [39:0] sum_1_fu_183_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 sum_fu_62 = 40'd0;
#0 i_fu_66 = 8'd0;
#0 ap_done_reg = 1'b0;
end

phase2_rpm_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln85_fu_109_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_66 <= add_ln85_fu_115_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_66 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        if (((ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            sum_fu_62 <= 40'd0;
        end else if ((ap_enable_reg_pp0_iter2 == 1'b1)) begin
            sum_fu_62 <= sum_2_fu_221_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        conv3_out_load_reg_262 <= conv3_out_q0;
        icmp_ln85_reg_253 <= icmp_ln85_fu_109_p2;
    end
end

always @ (*) begin
    if (((icmp_ln85_fu_109_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_66;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        conv3_out_ce0_local = 1'b1;
    end else begin
        conv3_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready_pp0_iter1_reg == 1'b1) & (icmp_ln85_reg_253 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        sum_out_ap_vld = 1'b1;
    end else begin
        sum_out_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln85_fu_115_p2 = (ap_sig_allocacmp_i_1 + 8'd1);

assign add_ln87_1_fu_169_p2 = ($signed(sext_ln87_2_fu_159_p1) + $signed(sext_ln87_1_fu_155_p1));

assign add_ln87_2_fu_163_p1 = sum_fu_62;

assign add_ln87_2_fu_163_p2 = ($signed(sext_ln87_fu_151_p1) + $signed(add_ln87_2_fu_163_p1));

assign add_ln87_fu_125_p2 = (zext_ln85_fu_121_p1 + tmp_27);

assign and_ln87_fu_201_p2 = (xor_ln87_fu_195_p2 & tmp_1_fu_187_p3);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_01001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv3_out_address0 = zext_ln87_fu_131_p1;

assign conv3_out_ce0 = conv3_out_ce0_local;

assign icmp_ln85_fu_109_p2 = ((ap_sig_allocacmp_i_1 == 8'd128) ? 1'b1 : 1'b0);

assign select_ln87_fu_213_p3 = ((and_ln87_fu_201_p2[0:0] == 1'b1) ? 40'd549755813887 : 40'd549755813888);

assign sext_ln87_1_fu_155_p0 = sum_fu_62;

assign sext_ln87_1_fu_155_p1 = sext_ln87_1_fu_155_p0;

assign sext_ln87_2_fu_159_p1 = shl_ln2_fu_144_p3;

assign sext_ln87_fu_151_p1 = shl_ln2_fu_144_p3;

assign shl_ln2_fu_144_p3 = {{conv3_out_load_reg_262}, {6'd0}};

assign sum_1_fu_183_p1 = add_ln87_1_fu_169_p2[39:0];

assign sum_2_fu_221_p3 = ((xor_ln87_1_fu_207_p2[0:0] == 1'b1) ? select_ln87_fu_213_p3 : sum_1_fu_183_p1);

assign sum_out = sum_fu_62;

assign tmp_1_fu_187_p3 = add_ln87_2_fu_163_p2[32'd39];

assign tmp_fu_175_p3 = add_ln87_1_fu_169_p2[32'd40];

assign xor_ln87_1_fu_207_p2 = (tmp_fu_175_p3 ^ tmp_1_fu_187_p3);

assign xor_ln87_fu_195_p2 = (tmp_fu_175_p3 ^ 1'd1);

assign zext_ln85_fu_121_p1 = ap_sig_allocacmp_i_1;

assign zext_ln87_fu_131_p1 = add_ln87_fu_125_p2;

endmodule //phase2_rpm_cnn_phase2_rpm_cnn_Pipeline_VITIS_LOOP_85_2
