// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module phase2_rpm_cnn_dense_q_1 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        input_0_val,
        input_1_val,
        input_2_val,
        input_3_val,
        input_4_val,
        input_5_val,
        input_6_val,
        input_7_val,
        input_8_val,
        input_9_val,
        input_10_val,
        input_11_val,
        input_12_val,
        input_13_val,
        input_14_val,
        input_15_val,
        output_r,
        output_r_ap_vld
);

parameter    ap_ST_fsm_state1 = 5'd1;
parameter    ap_ST_fsm_state2 = 5'd2;
parameter    ap_ST_fsm_state3 = 5'd4;
parameter    ap_ST_fsm_state4 = 5'd8;
parameter    ap_ST_fsm_state5 = 5'd16;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input  [16:0] input_0_val;
input  [16:0] input_1_val;
input  [16:0] input_2_val;
input  [16:0] input_3_val;
input  [16:0] input_4_val;
input  [16:0] input_5_val;
input  [16:0] input_6_val;
input  [16:0] input_7_val;
input  [16:0] input_8_val;
input  [16:0] input_9_val;
input  [16:0] input_10_val;
input  [16:0] input_11_val;
input  [16:0] input_12_val;
input  [16:0] input_13_val;
input  [16:0] input_14_val;
input  [16:0] input_15_val;
output  [17:0] output_r;
output   output_r_ap_vld;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg output_r_ap_vld;

(* fsm_encoding = "none" *) reg   [4:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [48:0] add_ln109_2_fu_267_p2;
reg   [48:0] add_ln109_2_reg_585;
wire    ap_CS_fsm_state3;
wire   [48:0] add_ln109_fu_289_p2;
reg   [48:0] add_ln109_reg_590;
wire    ap_CS_fsm_state4;
reg   [0:0] tmp_57_reg_595;
wire   [17:0] add_ln109_1_fu_333_p2;
reg   [17:0] add_ln109_1_reg_601;
wire   [0:0] tmp_60_fu_339_p3;
reg   [0:0] tmp_60_reg_606;
wire   [0:0] and_ln109_fu_353_p2;
reg   [0:0] and_ln109_reg_612;
wire   [0:0] icmp_ln109_fu_369_p2;
reg   [0:0] icmp_ln109_reg_619;
wire   [0:0] icmp_ln109_1_fu_385_p2;
reg   [0:0] icmp_ln109_1_reg_624;
wire   [0:0] icmp_ln109_2_fu_391_p2;
reg   [0:0] icmp_ln109_2_reg_631;
wire    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start;
wire    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done;
wire    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_idle;
wire    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_ready;
wire   [39:0] grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out;
wire    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out_ap_vld;
reg    grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg;
wire    ap_CS_fsm_state2;
wire    ap_CS_fsm_state5;
wire   [47:0] tmp_fu_243_p3;
wire   [43:0] tmp_55_fu_255_p3;
wire  signed [48:0] sext_ln109_fu_251_p1;
wire  signed [48:0] sext_ln109_1_fu_263_p1;
wire   [41:0] tmp_56_fu_273_p3;
wire  signed [48:0] sext_ln109_2_fu_280_p1;
wire   [48:0] sub_ln109_fu_284_p2;
wire   [0:0] tmp_58_fu_313_p3;
wire   [17:0] trunc_ln_fu_303_p4;
wire   [17:0] zext_ln109_fu_329_p1;
wire   [0:0] tmp_59_fu_321_p3;
wire   [0:0] xor_ln109_fu_347_p2;
wire   [7:0] tmp_23_fu_359_p4;
wire   [8:0] tmp_24_fu_375_p4;
wire   [0:0] tmp_61_fu_397_p3;
wire   [0:0] xor_ln109_1_fu_409_p2;
wire   [0:0] and_ln109_1_fu_415_p2;
wire   [0:0] select_ln109_fu_404_p3;
wire   [0:0] xor_ln109_2_fu_430_p2;
wire   [0:0] or_ln109_fu_436_p2;
wire   [0:0] xor_ln109_3_fu_441_p2;
wire   [0:0] select_ln109_1_fu_420_p3;
wire   [0:0] and_ln109_2_fu_426_p2;
wire   [0:0] and_ln109_4_fu_452_p2;
wire   [0:0] or_ln109_2_fu_457_p2;
wire   [0:0] xor_ln109_4_fu_463_p2;
wire   [0:0] and_ln109_3_fu_446_p2;
wire   [0:0] and_ln109_5_fu_469_p2;
wire   [0:0] or_ln109_1_fu_482_p2;
wire   [17:0] select_ln109_2_fu_474_p3;
reg   [4:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
reg    ap_ST_fsm_state2_blk;
wire    ap_ST_fsm_state3_blk;
wire    ap_ST_fsm_state4_blk;
wire    ap_ST_fsm_state5_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 5'd1;
#0 grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg = 1'b0;
end

phase2_rpm_cnn_dense_q_1_Pipeline_VITIS_LOOP_105_2 grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start),
    .ap_done(grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done),
    .ap_idle(grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_idle),
    .ap_ready(grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_ready),
    .input_0_val(input_0_val),
    .input_1_val(input_1_val),
    .input_2_val(input_2_val),
    .input_3_val(input_3_val),
    .input_4_val(input_4_val),
    .input_5_val(input_5_val),
    .input_6_val(input_6_val),
    .input_7_val(input_7_val),
    .input_8_val(input_8_val),
    .input_9_val(input_9_val),
    .input_10_val(input_10_val),
    .input_11_val(input_11_val),
    .input_12_val(input_12_val),
    .input_13_val(input_13_val),
    .input_14_val(input_14_val),
    .input_15_val(input_15_val),
    .acc_out(grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out),
    .acc_out_ap_vld(grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out_ap_vld)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg <= 1'b0;
    end else begin
        if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
            grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg <= 1'b1;
        end else if ((grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_ready == 1'b1)) begin
            grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state4)) begin
        add_ln109_1_reg_601 <= add_ln109_1_fu_333_p2;
        add_ln109_reg_590[48 : 2] <= add_ln109_fu_289_p2[48 : 2];
        and_ln109_reg_612 <= and_ln109_fu_353_p2;
        icmp_ln109_1_reg_624 <= icmp_ln109_1_fu_385_p2;
        icmp_ln109_2_reg_631 <= icmp_ln109_2_fu_391_p2;
        icmp_ln109_reg_619 <= icmp_ln109_fu_369_p2;
        tmp_57_reg_595 <= add_ln109_fu_289_p2[32'd48];
        tmp_60_reg_606 <= add_ln109_1_fu_333_p2[32'd17];
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        add_ln109_2_reg_585[48 : 4] <= add_ln109_2_fu_267_p2[48 : 4];
    end
end

always @ (*) begin
    if ((ap_start == 1'b0)) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done == 1'b0)) begin
        ap_ST_fsm_state2_blk = 1'b1;
    end else begin
        ap_ST_fsm_state2_blk = 1'b0;
    end
end

assign ap_ST_fsm_state3_blk = 1'b0;

assign ap_ST_fsm_state4_blk = 1'b0;

assign ap_ST_fsm_state5_blk = 1'b0;

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state5) | ((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0)))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        output_r_ap_vld = 1'b1;
    end else begin
        output_r_ap_vld = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if (((1'b1 == ap_CS_fsm_state1) & (ap_start == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((1'b1 == ap_CS_fsm_state2) & (grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_done == 1'b1))) begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            ap_NS_fsm = ap_ST_fsm_state5;
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln109_1_fu_333_p2 = (trunc_ln_fu_303_p4 + zext_ln109_fu_329_p1);

assign add_ln109_2_fu_267_p2 = ($signed(sext_ln109_fu_251_p1) + $signed(sext_ln109_1_fu_263_p1));

assign add_ln109_fu_289_p2 = ($signed(sub_ln109_fu_284_p2) + $signed(49'd562949131010048));

assign and_ln109_1_fu_415_p2 = (xor_ln109_1_fu_409_p2 & icmp_ln109_reg_619);

assign and_ln109_2_fu_426_p2 = (icmp_ln109_1_reg_624 & and_ln109_reg_612);

assign and_ln109_3_fu_446_p2 = (xor_ln109_3_fu_441_p2 & or_ln109_fu_436_p2);

assign and_ln109_4_fu_452_p2 = (tmp_60_reg_606 & select_ln109_1_fu_420_p3);

assign and_ln109_5_fu_469_p2 = (xor_ln109_4_fu_463_p2 & tmp_57_reg_595);

assign and_ln109_fu_353_p2 = (xor_ln109_fu_347_p2 & tmp_59_fu_321_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start = grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_ap_start_reg;

assign icmp_ln109_1_fu_385_p2 = ((tmp_24_fu_375_p4 == 9'd511) ? 1'b1 : 1'b0);

assign icmp_ln109_2_fu_391_p2 = ((tmp_24_fu_375_p4 == 9'd0) ? 1'b1 : 1'b0);

assign icmp_ln109_fu_369_p2 = ((tmp_23_fu_359_p4 == 8'd255) ? 1'b1 : 1'b0);

assign or_ln109_1_fu_482_p2 = (and_ln109_5_fu_469_p2 | and_ln109_3_fu_446_p2);

assign or_ln109_2_fu_457_p2 = (and_ln109_4_fu_452_p2 | and_ln109_2_fu_426_p2);

assign or_ln109_fu_436_p2 = (xor_ln109_2_fu_430_p2 | tmp_60_reg_606);

assign output_r = ((or_ln109_1_fu_482_p2[0:0] == 1'b1) ? select_ln109_2_fu_474_p3 : add_ln109_1_reg_601);

assign select_ln109_1_fu_420_p3 = ((and_ln109_reg_612[0:0] == 1'b1) ? and_ln109_1_fu_415_p2 : icmp_ln109_1_reg_624);

assign select_ln109_2_fu_474_p3 = ((and_ln109_3_fu_446_p2[0:0] == 1'b1) ? 18'd131071 : 18'd131072);

assign select_ln109_fu_404_p3 = ((and_ln109_reg_612[0:0] == 1'b1) ? icmp_ln109_1_reg_624 : icmp_ln109_2_reg_631);

assign sext_ln109_1_fu_263_p1 = $signed(tmp_55_fu_255_p3);

assign sext_ln109_2_fu_280_p1 = $signed(tmp_56_fu_273_p3);

assign sext_ln109_fu_251_p1 = $signed(tmp_fu_243_p3);

assign sub_ln109_fu_284_p2 = ($signed(add_ln109_2_reg_585) - $signed(sext_ln109_2_fu_280_p1));

assign tmp_23_fu_359_p4 = {{add_ln109_fu_289_p2[48:41]}};

assign tmp_24_fu_375_p4 = {{add_ln109_fu_289_p2[48:40]}};

assign tmp_55_fu_255_p3 = {{grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out}, {4'd0}};

assign tmp_56_fu_273_p3 = {{grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out}, {2'd0}};

assign tmp_58_fu_313_p3 = add_ln109_fu_289_p2[32'd21];

assign tmp_59_fu_321_p3 = add_ln109_fu_289_p2[32'd39];

assign tmp_60_fu_339_p3 = add_ln109_1_fu_333_p2[32'd17];

assign tmp_61_fu_397_p3 = add_ln109_reg_590[32'd40];

assign tmp_fu_243_p3 = {{grp_dense_q_1_Pipeline_VITIS_LOOP_105_2_fu_201_acc_out}, {8'd0}};

assign trunc_ln_fu_303_p4 = {{add_ln109_fu_289_p2[39:22]}};

assign xor_ln109_1_fu_409_p2 = (tmp_61_fu_397_p3 ^ 1'd1);

assign xor_ln109_2_fu_430_p2 = (select_ln109_fu_404_p3 ^ 1'd1);

assign xor_ln109_3_fu_441_p2 = (tmp_57_reg_595 ^ 1'd1);

assign xor_ln109_4_fu_463_p2 = (or_ln109_2_fu_457_p2 ^ 1'd1);

assign xor_ln109_fu_347_p2 = (tmp_60_fu_339_p3 ^ 1'd1);

assign zext_ln109_fu_329_p1 = tmp_58_fu_313_p3;

always @ (posedge ap_clk) begin
    add_ln109_2_reg_585[3:0] <= 4'b0000;
    add_ln109_reg_590[1:0] <= 2'b00;
end

endmodule //phase2_rpm_cnn_dense_q_1
