// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module phase2_rpm_cnn_phase2_rpm_cnn_Pipeline_VITIS_LOOP_67_1_VITIS_LOOP_68_21 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool2_out_8_address1,
        pool2_out_8_ce1,
        pool2_out_8_we1,
        pool2_out_8_d1,
        pool2_out_7_address1,
        pool2_out_7_ce1,
        pool2_out_7_we1,
        pool2_out_7_d1,
        pool2_out_6_address1,
        pool2_out_6_ce1,
        pool2_out_6_we1,
        pool2_out_6_d1,
        pool2_out_5_address1,
        pool2_out_5_ce1,
        pool2_out_5_we1,
        pool2_out_5_d1,
        pool2_out_4_address1,
        pool2_out_4_ce1,
        pool2_out_4_we1,
        pool2_out_4_d1,
        pool2_out_3_address1,
        pool2_out_3_ce1,
        pool2_out_3_we1,
        pool2_out_3_d1,
        pool2_out_2_address1,
        pool2_out_2_ce1,
        pool2_out_2_we1,
        pool2_out_2_d1,
        pool2_out_1_address1,
        pool2_out_1_ce1,
        pool2_out_1_we1,
        pool2_out_1_d1,
        pool2_out_address1,
        pool2_out_ce1,
        pool2_out_we1,
        pool2_out_d1,
        conv2_out_address0,
        conv2_out_ce0,
        conv2_out_q0,
        conv2_out_address1,
        conv2_out_ce1,
        conv2_out_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [7:0] pool2_out_8_address1;
output   pool2_out_8_ce1;
output   pool2_out_8_we1;
output  [17:0] pool2_out_8_d1;
output  [7:0] pool2_out_7_address1;
output   pool2_out_7_ce1;
output   pool2_out_7_we1;
output  [17:0] pool2_out_7_d1;
output  [7:0] pool2_out_6_address1;
output   pool2_out_6_ce1;
output   pool2_out_6_we1;
output  [17:0] pool2_out_6_d1;
output  [7:0] pool2_out_5_address1;
output   pool2_out_5_ce1;
output   pool2_out_5_we1;
output  [17:0] pool2_out_5_d1;
output  [7:0] pool2_out_4_address1;
output   pool2_out_4_ce1;
output   pool2_out_4_we1;
output  [17:0] pool2_out_4_d1;
output  [7:0] pool2_out_3_address1;
output   pool2_out_3_ce1;
output   pool2_out_3_we1;
output  [17:0] pool2_out_3_d1;
output  [7:0] pool2_out_2_address1;
output   pool2_out_2_ce1;
output   pool2_out_2_we1;
output  [17:0] pool2_out_2_d1;
output  [7:0] pool2_out_1_address1;
output   pool2_out_1_ce1;
output   pool2_out_1_we1;
output  [17:0] pool2_out_1_d1;
output  [7:0] pool2_out_address1;
output   pool2_out_ce1;
output   pool2_out_we1;
output  [17:0] pool2_out_d1;
output  [11:0] conv2_out_address0;
output   conv2_out_ce0;
input  [17:0] conv2_out_q0;
output  [11:0] conv2_out_address1;
output   conv2_out_ce1;
input  [17:0] conv2_out_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln67_fu_308_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] select_ln67_fu_332_p3;
reg   [7:0] select_ln67_reg_537;
wire   [4:0] select_ln67_1_fu_346_p3;
reg   [4:0] select_ln67_1_reg_542;
wire   [3:0] empty_fu_354_p1;
reg   [3:0] empty_reg_548;
reg   [3:0] empty_reg_548_pp0_iter1_reg;
reg   [3:0] empty_reg_548_pp0_iter2_reg;
reg   [3:0] empty_reg_548_pp0_iter3_reg;
reg   [3:0] empty_reg_548_pp0_iter4_reg;
reg   [3:0] empty_reg_548_pp0_iter5_reg;
reg   [3:0] empty_reg_548_pp0_iter6_reg;
reg   [3:0] empty_reg_548_pp0_iter7_reg;
reg   [3:0] empty_reg_548_pp0_iter8_reg;
reg   [3:0] empty_reg_548_pp0_iter9_reg;
reg   [3:0] empty_reg_548_pp0_iter10_reg;
wire   [6:0] trunc_ln70_fu_358_p1;
reg   [6:0] trunc_ln70_reg_555;
reg   [6:0] trunc_ln70_reg_555_pp0_iter1_reg;
reg   [6:0] trunc_ln70_reg_555_pp0_iter2_reg;
reg   [6:0] trunc_ln70_reg_555_pp0_iter3_reg;
reg   [6:0] trunc_ln70_reg_555_pp0_iter4_reg;
reg   [6:0] trunc_ln70_reg_555_pp0_iter5_reg;
reg   [6:0] trunc_ln70_reg_555_pp0_iter6_reg;
reg   [6:0] trunc_ln70_reg_555_pp0_iter7_reg;
reg   [6:0] trunc_ln70_reg_555_pp0_iter8_reg;
reg   [6:0] trunc_ln70_reg_555_pp0_iter9_reg;
reg   [6:0] trunc_ln70_reg_555_pp0_iter10_reg;
wire   [7:0] add_ln72_fu_392_p2;
wire   [10:0] add_ln72_1_fu_425_p2;
reg   [10:0] add_ln72_1_reg_566;
reg   [7:0] tmp_2_reg_571;
reg   [7:0] tmp_2_reg_571_pp0_iter3_reg;
reg   [7:0] tmp_2_reg_571_pp0_iter4_reg;
reg   [7:0] tmp_2_reg_571_pp0_iter5_reg;
reg   [7:0] tmp_2_reg_571_pp0_iter6_reg;
reg   [7:0] tmp_2_reg_571_pp0_iter7_reg;
reg   [7:0] tmp_2_reg_571_pp0_iter8_reg;
reg   [7:0] tmp_2_reg_571_pp0_iter9_reg;
reg   [7:0] tmp_2_reg_571_pp0_iter10_reg;
reg   [7:0] tmp_2_reg_571_pp0_iter11_reg;
reg   [7:0] tmp_2_reg_571_pp0_iter12_reg;
wire   [3:0] trunc_ln72_fu_488_p1;
reg   [3:0] trunc_ln72_reg_586;
wire   [17:0] select_ln72_fu_492_p3;
reg   [17:0] select_ln72_reg_590;
wire   [63:0] zext_ln70_fu_464_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln71_fu_477_p1;
wire   [63:0] zext_ln72_3_fu_500_p1;
reg   [7:0] i_fu_100;
wire   [7:0] add_ln68_fu_362_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_load;
reg   [4:0] c_fu_104;
reg   [4:0] ap_sig_allocacmp_c_load;
reg   [11:0] indvar_flatten6_fu_108;
wire   [11:0] add_ln67_fu_314_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten6_load;
reg    conv2_out_ce1_local;
reg    conv2_out_ce0_local;
reg    pool2_out_7_we1_local;
reg    pool2_out_7_ce1_local;
reg    pool2_out_6_we1_local;
reg    pool2_out_6_ce1_local;
reg    pool2_out_5_we1_local;
reg    pool2_out_5_ce1_local;
reg    pool2_out_4_we1_local;
reg    pool2_out_4_ce1_local;
reg    pool2_out_3_we1_local;
reg    pool2_out_3_ce1_local;
reg    pool2_out_2_we1_local;
reg    pool2_out_2_ce1_local;
reg    pool2_out_1_we1_local;
reg    pool2_out_1_ce1_local;
reg    pool2_out_we1_local;
reg    pool2_out_ce1_local;
reg    pool2_out_8_we1_local;
reg    pool2_out_8_ce1_local;
wire   [0:0] icmp_ln68_fu_326_p2;
wire   [4:0] add_ln67_1_fu_340_p2;
wire   [4:0] empty_62_fu_383_p2;
wire   [7:0] zext_ln68_fu_388_p1;
wire   [5:0] tmp_fu_408_p3;
wire   [10:0] p_shl_fu_401_p3;
wire   [10:0] zext_ln72_1_fu_415_p1;
wire   [10:0] zext_ln72_fu_397_p1;
wire   [10:0] sub_ln72_fu_419_p2;
wire   [4:0] grp_fu_431_p1;
wire   [10:0] mul_ln72_fu_440_p0;
wire   [12:0] mul_ln72_fu_440_p1;
wire   [22:0] mul_ln72_fu_440_p2;
wire   [11:0] add_ln70_1_fu_456_p4;
wire   [11:0] or_ln71_1_fu_469_p4;
wire   [3:0] grp_fu_431_p2;
wire   [0:0] icmp_ln72_fu_482_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [22:0] mul_ln72_fu_440_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 i_fu_100 = 8'd0;
#0 c_fu_104 = 5'd0;
#0 indvar_flatten6_fu_108 = 12'd0;
#0 ap_done_reg = 1'b0;
end

phase2_rpm_cnn_urem_8ns_5ns_4_12_1 #(
    .ID( 1 ),
    .NUM_STAGE( 12 ),
    .din0_WIDTH( 8 ),
    .din1_WIDTH( 5 ),
    .dout_WIDTH( 4 ))
urem_8ns_5ns_4_12_1_U167(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln72_fu_392_p2),
    .din1(grp_fu_431_p1),
    .ce(1'b1),
    .dout(grp_fu_431_p2)
);

phase2_rpm_cnn_mul_11ns_13ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
mul_11ns_13ns_23_1_1_U168(
    .din0(mul_ln72_fu_440_p0),
    .din1(mul_ln72_fu_440_p1),
    .dout(mul_ln72_fu_440_p2)
);

phase2_rpm_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln67_fu_308_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            c_fu_104 <= select_ln67_1_fu_346_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            c_fu_104 <= 5'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln67_fu_308_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_100 <= add_ln68_fu_362_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_100 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln67_fu_308_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten6_fu_108 <= add_ln67_fu_314_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten6_fu_108 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln72_1_reg_566 <= add_ln72_1_fu_425_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        empty_reg_548 <= empty_fu_354_p1;
        empty_reg_548_pp0_iter1_reg <= empty_reg_548;
        select_ln67_1_reg_542 <= select_ln67_1_fu_346_p3;
        select_ln67_reg_537 <= select_ln67_fu_332_p3;
        trunc_ln70_reg_555 <= trunc_ln70_fu_358_p1;
        trunc_ln70_reg_555_pp0_iter1_reg <= trunc_ln70_reg_555;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        empty_reg_548_pp0_iter10_reg <= empty_reg_548_pp0_iter9_reg;
        empty_reg_548_pp0_iter2_reg <= empty_reg_548_pp0_iter1_reg;
        empty_reg_548_pp0_iter3_reg <= empty_reg_548_pp0_iter2_reg;
        empty_reg_548_pp0_iter4_reg <= empty_reg_548_pp0_iter3_reg;
        empty_reg_548_pp0_iter5_reg <= empty_reg_548_pp0_iter4_reg;
        empty_reg_548_pp0_iter6_reg <= empty_reg_548_pp0_iter5_reg;
        empty_reg_548_pp0_iter7_reg <= empty_reg_548_pp0_iter6_reg;
        empty_reg_548_pp0_iter8_reg <= empty_reg_548_pp0_iter7_reg;
        empty_reg_548_pp0_iter9_reg <= empty_reg_548_pp0_iter8_reg;
        select_ln72_reg_590 <= select_ln72_fu_492_p3;
        tmp_2_reg_571 <= {{mul_ln72_fu_440_p2[22:15]}};
        tmp_2_reg_571_pp0_iter10_reg <= tmp_2_reg_571_pp0_iter9_reg;
        tmp_2_reg_571_pp0_iter11_reg <= tmp_2_reg_571_pp0_iter10_reg;
        tmp_2_reg_571_pp0_iter12_reg <= tmp_2_reg_571_pp0_iter11_reg;
        tmp_2_reg_571_pp0_iter3_reg <= tmp_2_reg_571;
        tmp_2_reg_571_pp0_iter4_reg <= tmp_2_reg_571_pp0_iter3_reg;
        tmp_2_reg_571_pp0_iter5_reg <= tmp_2_reg_571_pp0_iter4_reg;
        tmp_2_reg_571_pp0_iter6_reg <= tmp_2_reg_571_pp0_iter5_reg;
        tmp_2_reg_571_pp0_iter7_reg <= tmp_2_reg_571_pp0_iter6_reg;
        tmp_2_reg_571_pp0_iter8_reg <= tmp_2_reg_571_pp0_iter7_reg;
        tmp_2_reg_571_pp0_iter9_reg <= tmp_2_reg_571_pp0_iter8_reg;
        trunc_ln70_reg_555_pp0_iter10_reg <= trunc_ln70_reg_555_pp0_iter9_reg;
        trunc_ln70_reg_555_pp0_iter2_reg <= trunc_ln70_reg_555_pp0_iter1_reg;
        trunc_ln70_reg_555_pp0_iter3_reg <= trunc_ln70_reg_555_pp0_iter2_reg;
        trunc_ln70_reg_555_pp0_iter4_reg <= trunc_ln70_reg_555_pp0_iter3_reg;
        trunc_ln70_reg_555_pp0_iter5_reg <= trunc_ln70_reg_555_pp0_iter4_reg;
        trunc_ln70_reg_555_pp0_iter6_reg <= trunc_ln70_reg_555_pp0_iter5_reg;
        trunc_ln70_reg_555_pp0_iter7_reg <= trunc_ln70_reg_555_pp0_iter6_reg;
        trunc_ln70_reg_555_pp0_iter8_reg <= trunc_ln70_reg_555_pp0_iter7_reg;
        trunc_ln70_reg_555_pp0_iter9_reg <= trunc_ln70_reg_555_pp0_iter8_reg;
        trunc_ln72_reg_586 <= trunc_ln72_fu_488_p1;
    end
end

always @ (*) begin
    if (((icmp_ln67_fu_308_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_c_load = 5'd0;
    end else begin
        ap_sig_allocacmp_c_load = c_fu_104;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 8'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_100;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten6_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten6_load = indvar_flatten6_fu_108;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        conv2_out_ce0_local = 1'b1;
    end else begin
        conv2_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        conv2_out_ce1_local = 1'b1;
    end else begin
        conv2_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_1_ce1_local = 1'b1;
    end else begin
        pool2_out_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_reg_586 == 4'd1))) begin
        pool2_out_1_we1_local = 1'b1;
    end else begin
        pool2_out_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_2_ce1_local = 1'b1;
    end else begin
        pool2_out_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_reg_586 == 4'd2))) begin
        pool2_out_2_we1_local = 1'b1;
    end else begin
        pool2_out_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_3_ce1_local = 1'b1;
    end else begin
        pool2_out_3_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_reg_586 == 4'd3))) begin
        pool2_out_3_we1_local = 1'b1;
    end else begin
        pool2_out_3_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_4_ce1_local = 1'b1;
    end else begin
        pool2_out_4_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_reg_586 == 4'd4))) begin
        pool2_out_4_we1_local = 1'b1;
    end else begin
        pool2_out_4_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_5_ce1_local = 1'b1;
    end else begin
        pool2_out_5_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_reg_586 == 4'd5))) begin
        pool2_out_5_we1_local = 1'b1;
    end else begin
        pool2_out_5_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_6_ce1_local = 1'b1;
    end else begin
        pool2_out_6_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_reg_586 == 4'd6))) begin
        pool2_out_6_we1_local = 1'b1;
    end else begin
        pool2_out_6_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_7_ce1_local = 1'b1;
    end else begin
        pool2_out_7_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_reg_586 == 4'd7))) begin
        pool2_out_7_we1_local = 1'b1;
    end else begin
        pool2_out_7_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_8_ce1_local = 1'b1;
    end else begin
        pool2_out_8_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln72_reg_586 == 4'd0) & ~(trunc_ln72_reg_586 == 4'd1) & ~(trunc_ln72_reg_586 == 4'd2) & ~(trunc_ln72_reg_586 == 4'd3) & ~(trunc_ln72_reg_586 == 4'd4) & ~(trunc_ln72_reg_586 == 4'd5) & ~(trunc_ln72_reg_586 == 4'd6) & ~(trunc_ln72_reg_586 == 4'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_8_we1_local = 1'b1;
    end else begin
        pool2_out_8_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool2_out_ce1_local = 1'b1;
    end else begin
        pool2_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_reg_586 == 4'd0))) begin
        pool2_out_we1_local = 1'b1;
    end else begin
        pool2_out_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln67_1_fu_340_p2 = (ap_sig_allocacmp_c_load + 5'd1);

assign add_ln67_fu_314_p2 = (ap_sig_allocacmp_indvar_flatten6_load + 12'd1);

assign add_ln68_fu_362_p2 = (select_ln67_fu_332_p3 + 8'd1);

assign add_ln70_1_fu_456_p4 = {{{empty_reg_548_pp0_iter10_reg}, {trunc_ln70_reg_555_pp0_iter10_reg}}, {1'd0}};

assign add_ln72_1_fu_425_p2 = (zext_ln72_fu_397_p1 + sub_ln72_fu_419_p2);

assign add_ln72_fu_392_p2 = (select_ln67_reg_537 + zext_ln68_fu_388_p1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv2_out_address0 = zext_ln71_fu_477_p1;

assign conv2_out_address1 = zext_ln70_fu_464_p1;

assign conv2_out_ce0 = conv2_out_ce0_local;

assign conv2_out_ce1 = conv2_out_ce1_local;

assign empty_62_fu_383_p2 = select_ln67_1_reg_542 << 5'd1;

assign empty_fu_354_p1 = select_ln67_1_fu_346_p3[3:0];

assign grp_fu_431_p1 = 8'd9;

assign icmp_ln67_fu_308_p2 = ((ap_sig_allocacmp_indvar_flatten6_load == 12'd2048) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_326_p2 = ((ap_sig_allocacmp_i_load == 8'd128) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_482_p2 = (($signed(conv2_out_q1) > $signed(conv2_out_q0)) ? 1'b1 : 1'b0);

assign mul_ln72_fu_440_p0 = mul_ln72_fu_440_p00;

assign mul_ln72_fu_440_p00 = add_ln72_1_reg_566;

assign mul_ln72_fu_440_p1 = 23'd3641;

assign or_ln71_1_fu_469_p4 = {{{empty_reg_548_pp0_iter10_reg}, {trunc_ln70_reg_555_pp0_iter10_reg}}, {1'd1}};

assign p_shl_fu_401_p3 = {{empty_reg_548}, {7'd0}};

assign pool2_out_1_address1 = zext_ln72_3_fu_500_p1;

assign pool2_out_1_ce1 = pool2_out_1_ce1_local;

assign pool2_out_1_d1 = select_ln72_reg_590;

assign pool2_out_1_we1 = pool2_out_1_we1_local;

assign pool2_out_2_address1 = zext_ln72_3_fu_500_p1;

assign pool2_out_2_ce1 = pool2_out_2_ce1_local;

assign pool2_out_2_d1 = select_ln72_reg_590;

assign pool2_out_2_we1 = pool2_out_2_we1_local;

assign pool2_out_3_address1 = zext_ln72_3_fu_500_p1;

assign pool2_out_3_ce1 = pool2_out_3_ce1_local;

assign pool2_out_3_d1 = select_ln72_reg_590;

assign pool2_out_3_we1 = pool2_out_3_we1_local;

assign pool2_out_4_address1 = zext_ln72_3_fu_500_p1;

assign pool2_out_4_ce1 = pool2_out_4_ce1_local;

assign pool2_out_4_d1 = select_ln72_reg_590;

assign pool2_out_4_we1 = pool2_out_4_we1_local;

assign pool2_out_5_address1 = zext_ln72_3_fu_500_p1;

assign pool2_out_5_ce1 = pool2_out_5_ce1_local;

assign pool2_out_5_d1 = select_ln72_reg_590;

assign pool2_out_5_we1 = pool2_out_5_we1_local;

assign pool2_out_6_address1 = zext_ln72_3_fu_500_p1;

assign pool2_out_6_ce1 = pool2_out_6_ce1_local;

assign pool2_out_6_d1 = select_ln72_reg_590;

assign pool2_out_6_we1 = pool2_out_6_we1_local;

assign pool2_out_7_address1 = zext_ln72_3_fu_500_p1;

assign pool2_out_7_ce1 = pool2_out_7_ce1_local;

assign pool2_out_7_d1 = select_ln72_reg_590;

assign pool2_out_7_we1 = pool2_out_7_we1_local;

assign pool2_out_8_address1 = zext_ln72_3_fu_500_p1;

assign pool2_out_8_ce1 = pool2_out_8_ce1_local;

assign pool2_out_8_d1 = select_ln72_reg_590;

assign pool2_out_8_we1 = pool2_out_8_we1_local;

assign pool2_out_address1 = zext_ln72_3_fu_500_p1;

assign pool2_out_ce1 = pool2_out_ce1_local;

assign pool2_out_d1 = select_ln72_reg_590;

assign pool2_out_we1 = pool2_out_we1_local;

assign select_ln67_1_fu_346_p3 = ((icmp_ln68_fu_326_p2[0:0] == 1'b1) ? add_ln67_1_fu_340_p2 : ap_sig_allocacmp_c_load);

assign select_ln67_fu_332_p3 = ((icmp_ln68_fu_326_p2[0:0] == 1'b1) ? 8'd0 : ap_sig_allocacmp_i_load);

assign select_ln72_fu_492_p3 = ((icmp_ln72_fu_482_p2[0:0] == 1'b1) ? conv2_out_q1 : conv2_out_q0);

assign sub_ln72_fu_419_p2 = (p_shl_fu_401_p3 - zext_ln72_1_fu_415_p1);

assign tmp_fu_408_p3 = {{select_ln67_1_reg_542}, {1'd0}};

assign trunc_ln70_fu_358_p1 = select_ln67_fu_332_p3[6:0];

assign trunc_ln72_fu_488_p1 = grp_fu_431_p2[3:0];

assign zext_ln68_fu_388_p1 = empty_62_fu_383_p2;

assign zext_ln70_fu_464_p1 = add_ln70_1_fu_456_p4;

assign zext_ln71_fu_477_p1 = or_ln71_1_fu_469_p4;

assign zext_ln72_1_fu_415_p1 = tmp_fu_408_p3;

assign zext_ln72_3_fu_500_p1 = tmp_2_reg_571_pp0_iter12_reg;

assign zext_ln72_fu_397_p1 = add_ln72_fu_392_p2;

endmodule //phase2_rpm_cnn_phase2_rpm_cnn_Pipeline_VITIS_LOOP_67_1_VITIS_LOOP_68_21
