// ==============================================================
// Generated by Vitis HLS v2024.2
// Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// Copyright 2022-2024 Advanced Micro Devices, Inc. All Rights Reserved.
// ==============================================================

`timescale 1 ns / 1 ps 

module phase2_rpm_cnn_phase2_rpm_cnn_Pipeline_VITIS_LOOP_67_1_VITIS_LOOP_68_2 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        pool1_out_2_address1,
        pool1_out_2_ce1,
        pool1_out_2_we1,
        pool1_out_2_d1,
        pool1_out_1_address1,
        pool1_out_1_ce1,
        pool1_out_1_we1,
        pool1_out_1_d1,
        pool1_out_address1,
        pool1_out_ce1,
        pool1_out_we1,
        pool1_out_d1,
        conv1_out_address0,
        conv1_out_ce0,
        conv1_out_q0,
        conv1_out_address1,
        conv1_out_ce1,
        conv1_out_q1
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [9:0] pool1_out_2_address1;
output   pool1_out_2_ce1;
output   pool1_out_2_we1;
output  [17:0] pool1_out_2_d1;
output  [9:0] pool1_out_1_address1;
output   pool1_out_1_ce1;
output   pool1_out_1_we1;
output  [17:0] pool1_out_1_d1;
output  [9:0] pool1_out_address1;
output   pool1_out_ce1;
output   pool1_out_we1;
output  [17:0] pool1_out_d1;
output  [11:0] conv1_out_address0;
output   conv1_out_ce0;
input  [17:0] conv1_out_q0;
output  [11:0] conv1_out_address1;
output   conv1_out_ce1;
input  [17:0] conv1_out_q1;

reg ap_idle;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_enable_reg_pp0_iter2;
reg    ap_enable_reg_pp0_iter3;
reg    ap_enable_reg_pp0_iter4;
reg    ap_enable_reg_pp0_iter5;
reg    ap_enable_reg_pp0_iter6;
reg    ap_enable_reg_pp0_iter7;
reg    ap_enable_reg_pp0_iter8;
reg    ap_enable_reg_pp0_iter9;
reg    ap_enable_reg_pp0_iter10;
reg    ap_enable_reg_pp0_iter11;
reg    ap_enable_reg_pp0_iter12;
reg    ap_enable_reg_pp0_iter13;
reg    ap_idle_pp0;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln67_fu_180_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire    ap_block_pp0_stage0_11001;
wire   [7:0] trunc_ln70_fu_239_p1;
reg   [7:0] trunc_ln70_reg_393;
reg   [7:0] trunc_ln70_reg_393_pp0_iter2_reg;
reg   [7:0] trunc_ln70_reg_393_pp0_iter3_reg;
reg   [7:0] trunc_ln70_reg_393_pp0_iter4_reg;
reg   [7:0] trunc_ln70_reg_393_pp0_iter5_reg;
reg   [7:0] trunc_ln70_reg_393_pp0_iter6_reg;
reg   [7:0] trunc_ln70_reg_393_pp0_iter7_reg;
reg   [7:0] trunc_ln70_reg_393_pp0_iter8_reg;
reg   [7:0] trunc_ln70_reg_393_pp0_iter9_reg;
reg   [7:0] trunc_ln70_reg_393_pp0_iter10_reg;
wire   [2:0] trunc_ln70_1_fu_243_p1;
reg   [2:0] trunc_ln70_1_reg_399;
reg   [2:0] trunc_ln70_1_reg_399_pp0_iter2_reg;
reg   [2:0] trunc_ln70_1_reg_399_pp0_iter3_reg;
reg   [2:0] trunc_ln70_1_reg_399_pp0_iter4_reg;
reg   [2:0] trunc_ln70_1_reg_399_pp0_iter5_reg;
reg   [2:0] trunc_ln70_1_reg_399_pp0_iter6_reg;
reg   [2:0] trunc_ln70_1_reg_399_pp0_iter7_reg;
reg   [2:0] trunc_ln70_1_reg_399_pp0_iter8_reg;
reg   [2:0] trunc_ln70_1_reg_399_pp0_iter9_reg;
reg   [2:0] trunc_ln70_1_reg_399_pp0_iter10_reg;
wire   [8:0] add_ln72_fu_247_p2;
wire   [10:0] add_ln72_1_fu_271_p2;
reg   [10:0] add_ln72_1_reg_410;
reg   [9:0] tmp_reg_415;
reg   [9:0] tmp_reg_415_pp0_iter3_reg;
reg   [9:0] tmp_reg_415_pp0_iter4_reg;
reg   [9:0] tmp_reg_415_pp0_iter5_reg;
reg   [9:0] tmp_reg_415_pp0_iter6_reg;
reg   [9:0] tmp_reg_415_pp0_iter7_reg;
reg   [9:0] tmp_reg_415_pp0_iter8_reg;
reg   [9:0] tmp_reg_415_pp0_iter9_reg;
reg   [9:0] tmp_reg_415_pp0_iter10_reg;
reg   [9:0] tmp_reg_415_pp0_iter11_reg;
reg   [9:0] tmp_reg_415_pp0_iter12_reg;
wire   [17:0] select_ln72_fu_350_p3;
reg   [17:0] select_ln72_reg_430;
wire   [63:0] zext_ln70_fu_326_p1;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln71_fu_339_p1;
wire   [63:0] zext_ln72_2_fu_358_p1;
reg   [8:0] i_fu_74;
wire   [8:0] add_ln68_fu_283_p2;
wire    ap_loop_init;
reg   [3:0] c_fu_78;
wire   [3:0] select_ln67_1_fu_223_p3;
reg   [11:0] indvar_flatten_fu_82;
wire   [11:0] add_ln67_1_fu_186_p2;
reg   [11:0] ap_sig_allocacmp_indvar_flatten_load;
reg    conv1_out_ce1_local;
reg    conv1_out_ce0_local;
reg    pool1_out_1_we1_local;
wire   [1:0] trunc_ln72_fu_364_p1;
reg    pool1_out_1_ce1_local;
reg    pool1_out_we1_local;
reg    pool1_out_ce1_local;
reg    pool1_out_2_we1_local;
reg    pool1_out_2_ce1_local;
wire   [0:0] icmp_ln68_fu_203_p2;
wire   [3:0] add_ln6711_fu_217_p2;
wire   [8:0] select_ln67_fu_209_p3;
wire   [8:0] zext_ln67_fu_231_p1;
wire   [10:0] p_shl_fu_257_p3;
wire   [10:0] zext_ln72_1_fu_235_p1;
wire   [10:0] zext_ln72_fu_253_p1;
wire   [10:0] sub_ln72_fu_265_p2;
wire   [2:0] grp_fu_277_p1;
wire   [10:0] mul_ln72_fu_302_p0;
wire   [12:0] mul_ln72_fu_302_p1;
wire   [22:0] mul_ln72_fu_302_p2;
wire   [11:0] add_ln_fu_318_p4;
wire   [11:0] or_ln_fu_331_p4;
wire   [0:0] icmp_ln72_fu_344_p2;
wire   [1:0] grp_fu_277_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg    ap_loop_exit_ready_pp0_iter1_reg;
reg    ap_loop_exit_ready_pp0_iter2_reg;
reg    ap_loop_exit_ready_pp0_iter3_reg;
reg    ap_loop_exit_ready_pp0_iter4_reg;
reg    ap_loop_exit_ready_pp0_iter5_reg;
reg    ap_loop_exit_ready_pp0_iter6_reg;
reg    ap_loop_exit_ready_pp0_iter7_reg;
reg    ap_loop_exit_ready_pp0_iter8_reg;
reg    ap_loop_exit_ready_pp0_iter9_reg;
reg    ap_loop_exit_ready_pp0_iter10_reg;
reg    ap_loop_exit_ready_pp0_iter11_reg;
reg    ap_loop_exit_ready_pp0_iter12_reg;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ready_sig;
wire    ap_done_sig;
wire   [22:0] mul_ln72_fu_302_p00;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_enable_reg_pp0_iter2 = 1'b0;
#0 ap_enable_reg_pp0_iter3 = 1'b0;
#0 ap_enable_reg_pp0_iter4 = 1'b0;
#0 ap_enable_reg_pp0_iter5 = 1'b0;
#0 ap_enable_reg_pp0_iter6 = 1'b0;
#0 ap_enable_reg_pp0_iter7 = 1'b0;
#0 ap_enable_reg_pp0_iter8 = 1'b0;
#0 ap_enable_reg_pp0_iter9 = 1'b0;
#0 ap_enable_reg_pp0_iter10 = 1'b0;
#0 ap_enable_reg_pp0_iter11 = 1'b0;
#0 ap_enable_reg_pp0_iter12 = 1'b0;
#0 ap_enable_reg_pp0_iter13 = 1'b0;
#0 i_fu_74 = 9'd0;
#0 c_fu_78 = 4'd0;
#0 indvar_flatten_fu_82 = 12'd0;
#0 ap_done_reg = 1'b0;
end

phase2_rpm_cnn_urem_9ns_3ns_2_13_1 #(
    .ID( 1 ),
    .NUM_STAGE( 13 ),
    .din0_WIDTH( 9 ),
    .din1_WIDTH( 3 ),
    .dout_WIDTH( 2 ))
urem_9ns_3ns_2_13_1_U56(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(add_ln72_fu_247_p2),
    .din1(grp_fu_277_p1),
    .ce(1'b1),
    .dout(grp_fu_277_p2)
);

phase2_rpm_cnn_mul_11ns_13ns_23_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 11 ),
    .din1_WIDTH( 13 ),
    .dout_WIDTH( 23 ))
mul_11ns_13ns_23_1_1_U57(
    .din0(mul_ln72_fu_302_p0),
    .din1(mul_ln72_fu_302_p1),
    .dout(mul_ln72_fu_302_p2)
);

phase2_rpm_cnn_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready_sig),
    .ap_done(ap_done_sig),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter10 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter10 <= ap_enable_reg_pp0_iter9;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter11 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter11 <= ap_enable_reg_pp0_iter10;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter12 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter12 <= ap_enable_reg_pp0_iter11;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter13 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter13 <= ap_enable_reg_pp0_iter12;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter2 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter2 <= ap_enable_reg_pp0_iter1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter3 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter3 <= ap_enable_reg_pp0_iter2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter4 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter4 <= ap_enable_reg_pp0_iter3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter5 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter5 <= ap_enable_reg_pp0_iter4;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter6 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter6 <= ap_enable_reg_pp0_iter5;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter7 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter7 <= ap_enable_reg_pp0_iter6;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter8 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter8 <= ap_enable_reg_pp0_iter7;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter9 <= 1'b0;
    end else begin
        if ((1'b0 == ap_block_pp0_stage0_subdone)) begin
            ap_enable_reg_pp0_iter9 <= ap_enable_reg_pp0_iter8;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            c_fu_78 <= 4'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            c_fu_78 <= select_ln67_1_fu_223_p3;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if ((ap_loop_init == 1'b1)) begin
            i_fu_74 <= 9'd0;
        end else if ((ap_enable_reg_pp0_iter1 == 1'b1)) begin
            i_fu_74 <= add_ln68_fu_283_p2;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln67_fu_180_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_82 <= add_ln67_1_fu_186_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_82 <= 12'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        add_ln72_1_reg_410 <= add_ln72_1_fu_271_p2;
        ap_loop_exit_ready_pp0_iter1_reg <= ap_loop_exit_ready;
        ap_loop_exit_ready_pp0_iter2_reg <= ap_loop_exit_ready_pp0_iter1_reg;
        trunc_ln70_1_reg_399 <= trunc_ln70_1_fu_243_p1;
        trunc_ln70_reg_393 <= trunc_ln70_fu_239_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b0 == ap_block_pp0_stage0_11001)) begin
        ap_loop_exit_ready_pp0_iter10_reg <= ap_loop_exit_ready_pp0_iter9_reg;
        ap_loop_exit_ready_pp0_iter11_reg <= ap_loop_exit_ready_pp0_iter10_reg;
        ap_loop_exit_ready_pp0_iter12_reg <= ap_loop_exit_ready_pp0_iter11_reg;
        ap_loop_exit_ready_pp0_iter3_reg <= ap_loop_exit_ready_pp0_iter2_reg;
        ap_loop_exit_ready_pp0_iter4_reg <= ap_loop_exit_ready_pp0_iter3_reg;
        ap_loop_exit_ready_pp0_iter5_reg <= ap_loop_exit_ready_pp0_iter4_reg;
        ap_loop_exit_ready_pp0_iter6_reg <= ap_loop_exit_ready_pp0_iter5_reg;
        ap_loop_exit_ready_pp0_iter7_reg <= ap_loop_exit_ready_pp0_iter6_reg;
        ap_loop_exit_ready_pp0_iter8_reg <= ap_loop_exit_ready_pp0_iter7_reg;
        ap_loop_exit_ready_pp0_iter9_reg <= ap_loop_exit_ready_pp0_iter8_reg;
        select_ln72_reg_430 <= select_ln72_fu_350_p3;
        tmp_reg_415 <= {{mul_ln72_fu_302_p2[22:13]}};
        tmp_reg_415_pp0_iter10_reg <= tmp_reg_415_pp0_iter9_reg;
        tmp_reg_415_pp0_iter11_reg <= tmp_reg_415_pp0_iter10_reg;
        tmp_reg_415_pp0_iter12_reg <= tmp_reg_415_pp0_iter11_reg;
        tmp_reg_415_pp0_iter3_reg <= tmp_reg_415;
        tmp_reg_415_pp0_iter4_reg <= tmp_reg_415_pp0_iter3_reg;
        tmp_reg_415_pp0_iter5_reg <= tmp_reg_415_pp0_iter4_reg;
        tmp_reg_415_pp0_iter6_reg <= tmp_reg_415_pp0_iter5_reg;
        tmp_reg_415_pp0_iter7_reg <= tmp_reg_415_pp0_iter6_reg;
        tmp_reg_415_pp0_iter8_reg <= tmp_reg_415_pp0_iter7_reg;
        tmp_reg_415_pp0_iter9_reg <= tmp_reg_415_pp0_iter8_reg;
        trunc_ln70_1_reg_399_pp0_iter10_reg <= trunc_ln70_1_reg_399_pp0_iter9_reg;
        trunc_ln70_1_reg_399_pp0_iter2_reg <= trunc_ln70_1_reg_399;
        trunc_ln70_1_reg_399_pp0_iter3_reg <= trunc_ln70_1_reg_399_pp0_iter2_reg;
        trunc_ln70_1_reg_399_pp0_iter4_reg <= trunc_ln70_1_reg_399_pp0_iter3_reg;
        trunc_ln70_1_reg_399_pp0_iter5_reg <= trunc_ln70_1_reg_399_pp0_iter4_reg;
        trunc_ln70_1_reg_399_pp0_iter6_reg <= trunc_ln70_1_reg_399_pp0_iter5_reg;
        trunc_ln70_1_reg_399_pp0_iter7_reg <= trunc_ln70_1_reg_399_pp0_iter6_reg;
        trunc_ln70_1_reg_399_pp0_iter8_reg <= trunc_ln70_1_reg_399_pp0_iter7_reg;
        trunc_ln70_1_reg_399_pp0_iter9_reg <= trunc_ln70_1_reg_399_pp0_iter8_reg;
        trunc_ln70_reg_393_pp0_iter10_reg <= trunc_ln70_reg_393_pp0_iter9_reg;
        trunc_ln70_reg_393_pp0_iter2_reg <= trunc_ln70_reg_393;
        trunc_ln70_reg_393_pp0_iter3_reg <= trunc_ln70_reg_393_pp0_iter2_reg;
        trunc_ln70_reg_393_pp0_iter4_reg <= trunc_ln70_reg_393_pp0_iter3_reg;
        trunc_ln70_reg_393_pp0_iter5_reg <= trunc_ln70_reg_393_pp0_iter4_reg;
        trunc_ln70_reg_393_pp0_iter6_reg <= trunc_ln70_reg_393_pp0_iter5_reg;
        trunc_ln70_reg_393_pp0_iter7_reg <= trunc_ln70_reg_393_pp0_iter6_reg;
        trunc_ln70_reg_393_pp0_iter8_reg <= trunc_ln70_reg_393_pp0_iter7_reg;
        trunc_ln70_reg_393_pp0_iter9_reg <= trunc_ln70_reg_393_pp0_iter8_reg;
    end
end

always @ (*) begin
    if (((icmp_ln67_fu_180_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_loop_exit_ready_pp0_iter12_reg == 1'b1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter13 == 1'b0) & (ap_enable_reg_pp0_iter12 == 1'b0) & (ap_enable_reg_pp0_iter11 == 1'b0) & (ap_enable_reg_pp0_iter10 == 1'b0) & (ap_enable_reg_pp0_iter9 == 1'b0) & (ap_enable_reg_pp0_iter8 == 1'b0) & (ap_enable_reg_pp0_iter7 == 1'b0) & (ap_enable_reg_pp0_iter6 == 1'b0) & (ap_enable_reg_pp0_iter5 == 1'b0) & (ap_enable_reg_pp0_iter4 == 1'b0) & (ap_enable_reg_pp0_iter3 == 1'b0) & (ap_enable_reg_pp0_iter2 == 1'b0) & (ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 12'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_82;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        conv1_out_ce0_local = 1'b1;
    end else begin
        conv1_out_ce0_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter11 == 1'b1))) begin
        conv1_out_ce1_local = 1'b1;
    end else begin
        conv1_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool1_out_1_ce1_local = 1'b1;
    end else begin
        pool1_out_1_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_fu_364_p1 == 2'd1))) begin
        pool1_out_1_we1_local = 1'b1;
    end else begin
        pool1_out_1_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool1_out_2_ce1_local = 1'b1;
    end else begin
        pool1_out_2_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if ((~(trunc_ln72_fu_364_p1 == 2'd0) & ~(trunc_ln72_fu_364_p1 == 2'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool1_out_2_we1_local = 1'b1;
    end else begin
        pool1_out_2_we1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1))) begin
        pool1_out_ce1_local = 1'b1;
    end else begin
        pool1_out_ce1_local = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter13 == 1'b1) & (trunc_ln72_fu_364_p1 == 2'd0))) begin
        pool1_out_we1_local = 1'b1;
    end else begin
        pool1_out_we1_local = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign add_ln6711_fu_217_p2 = (c_fu_78 + 4'd1);

assign add_ln67_1_fu_186_p2 = (ap_sig_allocacmp_indvar_flatten_load + 12'd1);

assign add_ln68_fu_283_p2 = (select_ln67_fu_209_p3 + 9'd1);

assign add_ln72_1_fu_271_p2 = (zext_ln72_fu_253_p1 + sub_ln72_fu_265_p2);

assign add_ln72_fu_247_p2 = (select_ln67_fu_209_p3 + zext_ln67_fu_231_p1);

assign add_ln_fu_318_p4 = {{{trunc_ln70_1_reg_399_pp0_iter10_reg}, {trunc_ln70_reg_393_pp0_iter10_reg}}, {1'd0}};

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_done = ap_done_sig;

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign ap_ready = ap_ready_sig;

assign conv1_out_address0 = zext_ln71_fu_339_p1;

assign conv1_out_address1 = zext_ln70_fu_326_p1;

assign conv1_out_ce0 = conv1_out_ce0_local;

assign conv1_out_ce1 = conv1_out_ce1_local;

assign grp_fu_277_p1 = 9'd3;

assign icmp_ln67_fu_180_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 12'd2048) ? 1'b1 : 1'b0);

assign icmp_ln68_fu_203_p2 = ((i_fu_74 == 9'd256) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_344_p2 = (($signed(conv1_out_q1) > $signed(conv1_out_q0)) ? 1'b1 : 1'b0);

assign mul_ln72_fu_302_p0 = mul_ln72_fu_302_p00;

assign mul_ln72_fu_302_p00 = add_ln72_1_reg_410;

assign mul_ln72_fu_302_p1 = 23'd2731;

assign or_ln_fu_331_p4 = {{{trunc_ln70_1_reg_399_pp0_iter10_reg}, {trunc_ln70_reg_393_pp0_iter10_reg}}, {1'd1}};

assign p_shl_fu_257_p3 = {{trunc_ln70_1_fu_243_p1}, {8'd0}};

assign pool1_out_1_address1 = zext_ln72_2_fu_358_p1;

assign pool1_out_1_ce1 = pool1_out_1_ce1_local;

assign pool1_out_1_d1 = select_ln72_reg_430;

assign pool1_out_1_we1 = pool1_out_1_we1_local;

assign pool1_out_2_address1 = zext_ln72_2_fu_358_p1;

assign pool1_out_2_ce1 = pool1_out_2_ce1_local;

assign pool1_out_2_d1 = select_ln72_reg_430;

assign pool1_out_2_we1 = pool1_out_2_we1_local;

assign pool1_out_address1 = zext_ln72_2_fu_358_p1;

assign pool1_out_ce1 = pool1_out_ce1_local;

assign pool1_out_d1 = select_ln72_reg_430;

assign pool1_out_we1 = pool1_out_we1_local;

assign select_ln67_1_fu_223_p3 = ((icmp_ln68_fu_203_p2[0:0] == 1'b1) ? add_ln6711_fu_217_p2 : c_fu_78);

assign select_ln67_fu_209_p3 = ((icmp_ln68_fu_203_p2[0:0] == 1'b1) ? 9'd0 : i_fu_74);

assign select_ln72_fu_350_p3 = ((icmp_ln72_fu_344_p2[0:0] == 1'b1) ? conv1_out_q1 : conv1_out_q0);

assign sub_ln72_fu_265_p2 = (p_shl_fu_257_p3 - zext_ln72_1_fu_235_p1);

assign trunc_ln70_1_fu_243_p1 = select_ln67_1_fu_223_p3[2:0];

assign trunc_ln70_fu_239_p1 = select_ln67_fu_209_p3[7:0];

assign trunc_ln72_fu_364_p1 = grp_fu_277_p2[1:0];

assign zext_ln67_fu_231_p1 = select_ln67_1_fu_223_p3;

assign zext_ln70_fu_326_p1 = add_ln_fu_318_p4;

assign zext_ln71_fu_339_p1 = or_ln_fu_331_p4;

assign zext_ln72_1_fu_235_p1 = select_ln67_1_fu_223_p3;

assign zext_ln72_2_fu_358_p1 = tmp_reg_415_pp0_iter12_reg;

assign zext_ln72_fu_253_p1 = add_ln72_fu_247_p2;

endmodule //phase2_rpm_cnn_phase2_rpm_cnn_Pipeline_VITIS_LOOP_67_1_VITIS_LOOP_68_2
